(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.card = function() {
	this.initialize(img.card);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,176,115);


(lib.legal = function() {
	this.initialize(img.legal);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,135,97);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt0303 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAJB3QgQgFgJgJQgKgJgEgIQgFgJAAgHIA4AAIADAGQADADAGADQAHADALAAQAPAAAHgEQAHgFAAgGQAAgGgEgEQgEgEgLgBIgJgBIgKgBQgdgEgPgMQgQgNAAgYQAAgPAJgNQAJgNARgHQASgIAaAAQAZAAAQAGQAQAFAJAIQAJAIAEAIQAEAJABAGIg4AAIgEgFQgDgDgFgCQgGgCgKgBQgMABgHAEQgGAEAAAGQAAAEAEAEQADADAJABIAKABIAKABQAXADAOAGQAOAGAGAMQAGALAAARQAAAQgIANQgJANgTAIQgTAIgdAAQgaAAgQgGgADCBzQgPgJgIgSQgJgRAAgZQAAgeAMgWQAMgWAUgMQAUgMAZAAQAPAAALAEQALAEAHAHQAHAGADAHIAFgZIA1AAIgiCqIg0AAIAFgZQgEAHgIAGQgHAHgKAEQgLAEgOAAQgTAAgPgJgADsAAQgKAGgFALQgFALAAANQAAARAJAKQAJALARAAQANAAAKgHQAJgHAGgLQAFgMAAgNQAAgQgJgLQgJgJgRAAQgOAAgJAHgAkvB6Ig7jrIA8AAIAmClIBgilIA9AAIiLDrgAh/B5IAhiqIA2AAIgiCqgAhahHIAKg1IA3AAIgKA1g");
	this.shape.setTransform(-0.725,3.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0303, new cjs.Rectangle(-40.6,-27.3,79.80000000000001,54.7), null);


(lib.txt0302 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AErBxQgUgKgKgSQgKgTAAgYQAAgdAMgVQAMgWAXgMQAWgNAcAAQAcAAAVALQAUALAJAVQAKAUgEAfIgBAFIiBAAQAAARAKALQAJAKASAAQAKAAAHgDQAHgCAEgDIAFgGIA1AAQgBAIgHAKQgFAJgLAJQgLAIgOAGQgQAFgVABQgdgBgTgKgAGHALQgCgNgKgHQgIgHgOAAQgPAAgLAHQgKAIgFAMIBLAAIAAAAgAh4ByQgQgKgIgRQgIgSAAgYQAAgfAMgVQALgXAVgMQATgMAaAAQAPAAALAFQAKAEAIAGQAGAHAEAGIAEgZIA0AAIghCqIgzAAIAEgYQgEAGgHAHQgHAGgLAEQgKAFgOAAQgUAAgOgJgAhPgCQgKAGgEAMQgGALAAANQAAAQAJALQAKAKARAAQANAAAJgHQAKgHAFgLQAGgLAAgNQgBgRgIgKQgJgJgRgBQgOABgKAGgABsB5IgtisIA5AAIAXBrIA+hrIA5AAIhlCsgAHHB3IAwjyIA1AAIgwDygAlLB3IAhiqIA2AAIgGAbQADgFAGgGQAGgHALgEQALgFARAAIAoAAIgLA0IgyAAQgPAAgJAEQgJADgEAIQgFAIgDAMIgQBTgAn3B3IAki5IhYAAIAKgwIDnAAIgKAwIhYAAIgkC5g");
	this.shape.setTransform(-0.45,2.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0302, new cjs.Rectangle(-59.1,-27.3,117.1,54.7), null);


(lib.txt0301 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADNByQgPgJgIgSQgJgRABgZQAAgeAMgWQALgWAUgMQAUgMAZAAQAPAAALAEQALAEAHAHQAHAGADAHIAFgZIA1AAIgiCqIg0AAIAFgZQgEAHgHAGQgIAHgKAEQgLAEgNAAQgUAAgPgJgAD3gBQgKAGgFALQgFALAAANQAAARAJAKQAKALAQAAQANAAAKgHQAKgHAFgLQAGgMgBgNQAAgQgJgLQgJgJgRAAQgOAAgJAHgAAfB4IAYh/IgrAAIAIgrIAsAAIAFgYQADgWAOgNQANgNAaAAIBTAAIgIAoIg5AAQgLAAgGAFQgFAFgCALIgCALIA4AAIgIArIg5AAIgYB/gAhdB4IAvjyIA0AAIguDygAiqB4IgLgpIhtAAIgYApIg7AAICPjrIA5AAIA8DrgAjAAgIgWhSIgxBSIBHAAg");
	this.shape.setTransform(-0.6,2.325);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0301, new cjs.Rectangle(-39.6,-27.3,77.80000000000001,54.7), null);


(lib.txt0202 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ar6CAIAAgdIhKAAIAAAdIgdAAIAAg4IAKAAQAFgHADgKQADgKACgRIAEggIBYAAIAABMIARAAIAAA4gAssAdIgDATIgDAOIgFAKIAoAAIAAgyIgcAAgAjwBgQgIgFgFgJQgGgIAAgLQAAgLAGgIQAFgJAIgFQAJgFALAAQALAAAJAFQAJAFAFAJQAFAIAAALQAAALgFAIQgFAJgJAFQgJAFgLAAQgLAAgJgFgAjmA1QgEAEAAAGQAAAGAEAFQAEAEAGAAQAHAAAEgEQAEgFAAgGQAAgGgEgEQgEgFgHAAQgGAAgEAFgAMtBeQgNgHgHgMQgHgMAAgRQAAgPAHgNQAHgMANgGQANgHAQAAQARAAANAHQAMAGAIAMQAHANAAAPQAAARgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAM+AYQgGADgDAHQgDAFAAAHQAAAIADAGQADAGAGAEQAFADAHAAQAIAAAFgDQAGgEADgGQADgGAAgIQAAgHgDgFQgDgHgGgDQgFgDgIgBQgHABgFADgAFOBeQgMgGgHgNQgHgMAAgRQAAgQAHgMQAHgMAMgGQAMgGAPgBQAOAAAKAFQAJACAHAGQAGAGADAGQADAHAAAGIgfAAIgDgEQgCgCgEgDQgEgCgHAAQgGABgFADQgFADgDAHQgDAFAAAHQAAAMAGAHQAGAIALAAQAGAAAEgCIAHgFIACgDIAfAAQAAAFgDAGQgDAHgGAGQgGAGgKAEQgJAEgOAAQgQAAgMgHgADSBeQgNgHgHgMQgIgMAAgRQAAgPAIgNQAHgMANgGQAMgHARAAQAQAAANAHQANAGAHAMQAIANAAAPQAAARgIAMQgHAMgNAHQgNAHgQAAQgRAAgMgHgADiAYQgFADgDAHQgDAFAAAHQAAAIADAGQADAGAFAEQAGADAHAAQAHAAAGgDQAFgEADgGQADgGAAgIQAAgHgDgFQgDgHgFgDQgGgDgHgBQgHABgGADgAq9BeQgNgHgHgMQgHgMAAgRQAAgPAHgNQAHgMANgGQANgHAQAAQARAAANAHQAMAGAIAMQAHANAAAPQAAARgHAMQgIAMgMAHQgNAHgRAAQgQAAgNgHgAqsAYQgGADgDAHQgDAFAAAHQAAAIADAGQADAGAGAEQAFADAHAAQAIAAAFgDQAGgEADgGQADgGAAgIQAAgHgDgFQgDgHgGgDQgFgDgIgBQgHABgFADgAIzBeQgKgHgHgMQgGgMAAgRQAAgQAGgMQAHgMAKgGQALgGANAAQALAAAHAEQAHACADADIAFAHIAAgOIAgAAIAABnIggAAIAAgQIgEAHQgEADgHAEQgHADgLAAQgNAAgLgGgAJIAYQgFADgDAHQgDAFAAAHQAAAIADAGQADAGAFAEQAFADAIAAQAHAAAFgDQAFgEADgGQADgGAAgIQAAgHgDgFQgDgHgFgDQgFgDgHgBQgIABgFADgAAeBeQgLgHgGgMQgGgMgBgRQABgQAGgMQAGgMALgGQAKgGAOAAQAKAAAHAEQAHACAEADIAEAHIAAgOIAhAAIAABnIggAAIAAgQIgFAHQgEADgHAEQgHADgLAAQgNAAgKgGgAAyAYQgFADgDAHQgDAFAAAHQAAAIADAGQADAGAFAEQAGADAHAAQAHAAAGgDQAFgEADgGQADgGAAgIQAAgHgDgFQgDgHgFgDQgGgDgHgBQgHABgGADgAPgBjIgrgtIAAAtIggAAIAAhnIAgAAIAAApIAqgpIApAAIgyAwIA1A3gALCBjIAAhNIgnAAIAAgaIBuAAIAAAaIgnAAIAABNgAHMBjIAAhNIgnAAIAAgaIBuAAIAAAaIgnAAIAABNgAgrBjIAAgoIgqAAIAAAoIggAAIAAhnIAgAAIAAAkIAqAAIAAgkIAgAAIAABngAlSBjIBoiOIAdAAIhoCOgAobBjIBgizIhtAAIAAgvICtAAIAAAhIhkDBgAwKAxIAAgVIBwAAIAAAVgAlXAaQgJgGgFgIQgFgJAAgKQAAgLAFgIQAFgJAJgFQAJgFALAAQALAAAJAFQAJAFAFAJQAFAIAAALQAAAKgFAJQgFAIgJAGQgJAEgLAAQgLAAgJgEgAlNgRQgEAEgBAGQABAHAEADQADAEAHABQAGgBAEgEQAEgDAAgHQAAgGgEgEQgEgEgGgBQgHABgDAEg");
	this.shape.setTransform(107.475,30.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0202, new cjs.Rectangle(0,0,212,53.1), null);


(lib.txt0201 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqJCBIAAgeIhKAAIAAAeIgdAAIAAg5IAKAAQAEgHAEgJQADgLACgQIAEggIBXAAIAABLIASAAIAAA5gAq8AeIgDATIgDANIgEAKIAoAAIAAgxIgdAAgAgeBgQgJgEgFgJQgFgJAAgLQAAgKAFgJQAFgJAJgEQAJgGALAAQAKAAAIAGQAJAEAFAJQAFAJABAKQgBALgFAJQgFAJgJAEQgIAFgKABQgLgBgJgFgAgVA1QgEAEAAAGQAAAHAEAFQAEADAHAAQAGAAAEgDQADgFAAgHQAAgGgDgEQgEgFgGABQgHgBgEAFgApMBfQgNgHgHgMQgIgNAAgQQAAgQAIgMQAHgNANgGQAMgGARAAQAQAAANAGQANAGAHANQAIAMAAAQQAAAQgIANQgHAMgNAHQgNAGgQABQgRgBgMgGgAo8AYQgFAEgDAGQgDAGAAAHQAAAIADAFQADAGAFAEQAGAEAHAAQAHAAAGgEQAFgEADgGQADgFAAgIQAAgHgDgGQgDgGgFgEQgGgDgHAAQgHAAgGADgAGABjIAAgdIACAAQAFAAADgCQADgBABgFQACgEAAgHIAGg2IBZAAIAABmIggAAIAAhMIgfAAIgDAgQgBAPgEAKQgDAJgIAGQgIAEgNAAgAN6BjIAAg9IgsA9IggAAIAAhmIAgAAIAAA8IAsg8IAgAAIAABmgAL2BjIAAhJIgfBJIgVAAIgghJIAABJIgdAAIAAhmIAtAAIAcA9IAcg9IAsAAIAABmgAJMBjIAAggIgRAAIgXAgIgkAAIAcglQgMgDgGgJQgGgIAAgLQAAgKAEgIQAFgIAJgFQAJgDAOAAIBAAAIAABmgAIoAXQgDADAAAFQAAAFADADQADADAGAAIAbAAIAAgWIgbAAQgGAAgDADgAFRBjIAAg9IgtA9IggAAIAAhmIAgAAIAAA8IAtg8IAgAAIAABmgADNBjIAAhJIgfBJIgVAAIgghJIAABJIgeAAIAAhmIAtAAIAdA9IAbg9IAtAAIAABmgAiABjIBoiNIAbAAIhnCNgAjvBjIAAinIg4AeIAAgxIBFgpIAoAAIAADjgAmBBjIAAinIg4AeIAAgxIBFgpIAoAAIAADjgAuZAyIAAgWIBwAAIAAAWgAiFAaQgJgFgFgIQgFgKAAgJQAAgLAFgJQAFgIAJgFQAIgFAMgBQALABAIAFQAJAFAFAIQAFAJAAALQAAAJgFAKQgFAIgJAFQgIAFgLAAQgMAAgIgFgAh8gRQgEAFAAAGQAAAGAEAEQAEAEAHAAQAGAAAEgEQAEgEAAgGQAAgGgEgFQgEgEgGAAQgHAAgEAEg");
	this.shape.setTransform(96.225,30.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0201, new cjs.Rectangle(0,0,191.1,53.1), null);


(lib.txt0102 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJoBgIASgqIguhlIAkAAIAaA+IAbg+IAgAAIg8CPgAm/BgIASgqIguhlIAlAAIAaA+IAag+IAgAAIg8CPgAD8A0QgMgIgHgLQgIgNABgRQgBgPAIgMQAHgMAMgHQAMgHAPAAQAOABAJAEQAKADAGAGQAHAGACAGQADAIABAFIgfAAIgDgEQgCgCgFgCQgDgCgHAAQgGAAgFADQgGAEgCAFQgDAGAAAGQAAAMAGAIQAGAHALAAQAGAAAEgCIAHgEIACgFIAfAAQAAAGgEAHQgCAGgHAGQgFAGgKAEQgKAEgNAAQgQAAgMgGgAB+AzQgNgHgIgMQgGgMAAgRQAAgPAGgMQAIgMAMgHQANgHAQAAQARAAAMAHQAMAGAHANQAHAMAAARIAAAFIhPAAQACAKAGAGQAIAHAKAAQAGAAAEgCIAHgDIADgDIAgAAQAAAEgEAGQgDAGgGAFQgHAFgJADQgKAEgNAAQgSAAgMgHgACwgJQgBgIgHgEQgFgFgJAAQgJAAgGAFQgGAEgCAIIAtAAIAAAAgAjFAzQgNgHgHgMQgHgMAAgRQAAgPAHgMQAHgMANgHQAMgHARAAQAQAAAMAHQANAGAGANQAIAMgBARIAAAFIhOAAQABAKAHAGQAHAHAKAAQAHAAAEgCIAHgDIACgDIAhAAQgBAEgDAGQgDAGgHAFQgGAFgJADQgKAEgOAAQgRAAgNgHgAiSgJQgCgIgGgEQgGgFgIAAQgJAAgHAFQgGAEgCAIIAuAAIAAAAgArJAzQgLgGgGgMQgGgMAAgSQAAgPAGgMQAGgMALgHQALgGANAAQAKAAAHAEQAHACAEAFIAFAFIAAgOIAgAAIAABmIggAAIAAgOIgFAFQgDAFgIADQgHADgLAAQgMABgLgHgAq0gSQgGAEgCAFQgDAGgBAGQABAIADAGQACAGAGADQAFAEAHAAQAIAAAFgEQAFgDADgGQADgGAAgIQAAgGgDgGQgDgFgFgEQgFgDgIAAQgHAAgFADgANgA3IAAgjIAlAAIAAAjgAMhA3IAAg8IgsA8IghAAIAAhmIAhAAIAAA9IAsg9IAgAAIAABmgAHZA3IAAhmIBCAAQARAAAKAIQAJAGAAAOQAAAGgCAEQgDAFgDADIgHADQAFABAEADQADADAEAFQACAFAAAHQAAAOgKAHQgKAJgSgBgAH6AhIAbAAQAGAAADgDQAEgCgBgFQABgEgEgCQgDgDgGAAIgbAAgAH6gHIAZAAQAFAAAEgCQADgBAAgGQAAgEgDgCQgEgCgFgBIgZAAgAF+A3IAAhLIgmAAIAAgbIBtAAIAAAbIgmAAIAABLgAhbA3IAAhmIAgAAIAABLIAjAAIAAhLIAgAAIAABLIAjAAIAAhLIAgAAIAABmgAk1A3IAAhLIgmAAIAAgbIBtAAIAAAbIgmAAIAABLgAoLA3IAAhLIgoAAIAABLIggAAIAAhmIBoAAIAABmgAsdA3IAAg3IhFAAIAAA3IgiAAIAAiNIAiAAIAAA5IBFAAIAAg5IAjAAIAACNgANiAIIAAheIAhAAIAABegAL3g/QgHgEgEgIQgEgIAAgIIAAgEIAZAAIAAADQAAAEACAEQADADAFAAQAFAAACgDQACgDAAgFIAAgDIAZAAIAAAEQAAAIgDAIQgDAIgJAEQgHAEgMAAQgMAAgIgEg");
	this.shape.setTransform(94.1,20.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0102, new cjs.Rectangle(0,0,187.7,34.7), null);


(lib.txt0101 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA7BcIARgpIguhmIAlAAIAaA+IAag+IAgAAIg8CPgAjCAvQgNgGgHgNQgIgLAAgRQAAgPAIgMQAHgMANgHQAMgHARAAQAQAAANAHQANAHAHAMQAIAMAAAPQAAARgIALQgHANgNAGQgNAIgQgBQgRABgMgIgAiygWQgFAEgDAGQgDAFAAAHQAAAIADAFQADAHAFADQAGADAHABQAHgBAGgDQAFgDADgHQADgFAAgIQAAgHgDgFQgDgGgFgEQgGgDgHAAQgHAAgGADgAE+AvQgLgGgGgMQgGgMgBgRQABgPAGgMQAGgMALgHQAKgGAOgBQAKABAHADQAHADAEAEIAEAGIAAgPIAhAAIAABnIggAAIAAgPIgFAGQgEAEgHAEQgHADgLAAQgNAAgKgHgAFSgWQgFAEgDAGQgDAFAAAHQAAAIADAFQADAHAFADQAGADAHABQAHgBAGgDQAFgDADgHQADgFAAgIQAAgHgDgFQgDgGgFgEQgGgDgHAAQgHAAgGADgAnTAvQgLgGgGgMQgGgMgBgRQABgPAGgMQAGgMALgHQAKgGAOgBQAKABAHADQAHADAEAEIAEAGIAAgPIAhAAIAABnIggAAIAAgPIgFAGQgEAEgHAEQgHADgLAAQgNAAgKgHgAm/gWQgFAEgDAGQgDAFAAAHQAAAIADAFQADAHAFADQAGADAHABQAHgBAGgDQAFgDADgHQADgFAAgIQAAgHgDgFQgDgGgFgEQgGgDgHAAQgHAAgGADgAGrA1IAAgeIACAAQAFAAADgCQADgBABgEQACgFAAgHIAGg3IBZAAIAABnIggAAIAAhMIgfAAIgDAgQgBAPgEAKQgDAKgIAEQgIAGgNAAgAJCA0IAAgjIAmAAIAAAjgADvA0IAAhMIgoAAIAABMIggAAIAAhnIBoAAIAABngAgKA0IgrgtIAAAtIghAAIAAhnIAhAAIAAArIApgrIAoAAIgwAyIAzA1gAkVA0IAAhMIgoAAIAABMIggAAIAAhnIBoAAIAABngAonA0IAAg3IhFAAIAAA3IgiAAIAAiNIAiAAIAAA4IBFAAIAAg4IAiAAIAACNgAJFAEIAAgGQAAgGABgFQACgEADgDQAEgEAHgEIANgIQAGgDADgEQADgDAAgGQAAgFgEgFQgEgDgHAAQgHABgEADQgEAEAAAIIAAAFIggAAIAAgIQAAgMAGgIQAFgJALgGQAKgEAPAAQAXAAAMAKQAMALAAASQAAAKgDAHQgDAHgGAGQgGAFgJAGIgKAFQgDACgBADIgBAEIAAABg");
	this.shape.setTransform(69.525,21.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0101, new cjs.Rectangle(0,0,137.7,34.7), null);


(lib.Tween3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#DC433F","#EC9D87","#FFFFFF"],[0.114,0.482,0.871],0,640.8,0,-745.4).s().p("Egu+BvOQ1qpLwtwtQwtwtpL1qQpf2bAA4kQAA4iJf2cQJL1qQtwtQQtwtVqpLQWcpfYiAAQYkAAWbJfQVqJLQuQtQQtQtJKVqQJfWcAAYiQAAYkpfWbQpKVqwtQtQwuQt1qJLQ2bJf4kAAQ4iAA2cpfg");
	this.shape.setTransform(-0.05,0,0.15,0.15,0,0,0,-0.4,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-115.8,-115.9,231.7,231.8);


(lib.RED = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF321E").s().rr(-120,-200,240,400,2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.RED, new cjs.Rectangle(-120,-200,240,400), null);


(lib.legal_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.legal();
	this.instance.parent = this;
	this.instance.setTransform(-68,-49);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal_1, new cjs.Rectangle(-68,-49,135,97), null);


(lib.Footer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF321E").s().p("AMYA+QgLgDgHgGQgHgGgEgHQgDgHgBgHIAgAAQAAAEAEADQADAEAGACQAHADAKAAQAOgBAGgEQAGgFAAgGQAAgGgEgDQgFgDgIgBIgHgBIgHgBQgVgDgLgIQgLgJAAgRQAAgSAPgLQAOgKAbAAQAPAAAKADQALADAHAGQAGAFADAGQAEAHABAGIgfAAQgBgDgDgCQgDgDgGgCIgPgCQgLAAgGADQgGAEAAAGQAAAFAEACQAEADAIABIAHABIAHABQAOACAKAEQAKAEAFAHQAGAIAAAOQAAANgHAJQgHAJgNAGQgNAFgTAAQgRAAgLgEgAJHBAIggh/IAhAAIAUBZIA1hZIAhAAIhMB/gABoBAIggh/IAhAAIAUBZIA1hZIAhAAIhMB/gAPoBAIgFgXIg8AAIgNAXIggAAIBNiAIAfAAIAhCAgAPcAQIgLgsIgbAsIAmAAgAK0BAIAZh/IAeAAIgZB/gAFjBAIAZh/IAeAAIgUBkIBLAAIgFAbgADVBAIAZh/IBqAAIgFAZIhMAAIgEAXIAtAAIgFAZIgtAAIgGAbIBTAAIgFAbgAAIBAIgGgXIg6AAIgOAXIggAAIBOiAIAeAAIAhCAgAgDAQIgMgsIgaAsIAmAAgAiVBAIgSgxIgjAAIgJAxIgeAAIAYh/IBCAAQAYAAALAKQALAJAAATQAAAPgIAKQgIAJgQAEIATAzgAjFgKIAqAAQAKAAAFgEQAEgEAAgHQAAgGgEgDQgEgDgIAAIgnAAgAlcBAIAThlIgwAAIAGgaIB+AAIgGAaIgwAAIgTBlgAnuBAIgGgXIg7AAIgOAXIggAAIBOiAIAfAAIAhCAgAn6AQIgMgsIgaAsIAmAAgArbBAIAYh/IBwAAIgFAZIhRAAIgFAZIAuAAIgFAZIguAAIgKA0gAthBAIAZh/IAeAAIgUBkIBLAAIgFAbgAuYBAIgFgXIg8AAIgNAXIggAAIBNiAIAfAAIAhCAgAukAQIgLgsIgbAsIAmAAg");
	this.shape.setTransform(-3.875,-5.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AzZDFIAAmJMAmzAAAIAAGJg");
	this.shape_1.setTransform(0.2,3.65);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Footer, new cjs.Rectangle(-124,-22.6,248.4,45.900000000000006), null);


(lib.Whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(3).p("AAAl0IAALp");
	this.shape.setTransform(140.5,63.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AmHJ3QgFAAgEgDQgEgEAAgGIAAiPQAAgFAEgEQAEgDAFAAIMQAAQAFAAADADQAEAEAAAFIAACPQAAAGgEAEQgDADgFAAgAjsDWIiDgyQgEgCgDgFQgCgFACgEIDvqPQAWg6AWgbQAjgnA4AAQA6AAAiAnQAWAaAWA7IDwKPQABAEgBAFQgCAFgGACIiCAyQgMADgEgLIg4iZIlKAAIg4CZQgCAFgFADQgCABgDAAIgEgBgAhvhgIDgAAIhwlPIgBAAg");
	this.shape_1.setTransform(40.475,63.15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA0FtQg2gLgjgQIAiifQAwAWAdAJQA2APA/gBQAugBAfgQQAkgUAAgiQABgYgWgUQgWgUg3gbQhIgigmgmQg5g3ABhGQABhqBahDQBZhECMAAQBaABBYAgIghCaQg4gag7gGQgogEggADQgnAFgWATQgTARgBAUQAAAcApAbQAZAQBDAiQCFBKAABtQgBByhaBEQhaBDiVAAQg9AAg8gLgAPmFuIgXhtIj0AAIgnBtIjHAAIEcqjQAKgZAWgOQAWgOAbAAICiAAICZLYgAMSBrICdAAIg5kQgAllFuICdrYIC+AAIidLYgAsVFuIiXpGQgHgbgIgMQgJgNgVgMQhBgjh6gbIAFgUIFCAAQAgAAAYATQAZAVAHAiIBPGlIDGnvIDHAAIkzLYg");
	this.shape_2.setTransform(298.625,63.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Whitelogo, new cjs.Rectangle(0,0,415.9,126.3), null);


(lib.dashes_white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EEOnC3nIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEEHoCy4IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEEApCuJIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgED5rCpaIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDysCkrIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDruCf9IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDkvCbOIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDdwCWfIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDWyCRwIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDP0CNCIjgiYQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDgCYQAMAIADAOQADAPgJALQgIAMgOADIgHABQgKAAgJgGgEDI0CITIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDB1CDjIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEC62B+1IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgECz3B6GIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgECs5B1YIjgiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgECl5BwqIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgECe6Br8IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECX6BnOIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECQ6BigIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECJ6BdyIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECC6BZEIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEB76BUWIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEB06BPoIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBt6BK6IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBm6BGMIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBf6BBeIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBY6A8wIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBR6A4CIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBK6AzUIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBD6AumIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEA86Ap4IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEA16AlKIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAu6AgcIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAn6AbuIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAg6AXAIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAZ6SSIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAS6NkIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAL6I2IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAE6EIIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAiBg2IjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgApAllIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgAv/qUIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgA29vDIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgA98zyIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEgk6gYgIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEgr5gdPIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEgy4gh+IjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEg52gmtIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhA0grbIjgiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDgCYQAMAIACAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhH0gwKIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEhOzg06IjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhVyg5oIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEhcxg+XIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhjvhDFIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAPgIALQgIAMgPADIgHABQgKAAgJgGgEhquhHzIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEhxthMhIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEh4thRPIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEh/thV9IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiGtharIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiNthfZIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiUthkHIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEibtho1IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiithtjIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEipthyRIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiwth2/IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEi3th7tIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEi+tiAbIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjFtiFJIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjMtiJ3IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjTtiOlIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjatiTTIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjhtiYBIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjoticvIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjvtihdIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEj2timLIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEj9tiq5IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEkEtivnIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEkLti0VIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGg");
	this.shape.setTransform(-7.1938,-4.8414);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.dashes_white, new cjs.Rectangle(-1744.5,-1180.5,3474.7,2351.4), null);


(lib.dashes_red = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E63428").s().p("EEOnC3nIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEEHoCy4IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEEApCuJIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgED5rCpaIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDysCkrIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDruCf9IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDkvCbOIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDdwCWfIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDWyCRwIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEDP0CNCIjgiYQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDgCYQAMAIADAOQADAPgJALQgIAMgOADIgHABQgKAAgJgGgEDI0CITIjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgEDB1CDjIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEC62B+1IjfiYQgMgIgDgPQgDgOAJgMQAIgMAOgCQAOgDAMAIIDfCYQAMAIADAOQADAPgJAMQgIAMgOACIgHABQgKAAgJgGgECz3B6GIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgECs5B1YIjgiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgECl5BwqIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgECe6Br8IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECX6BnOIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECQ6BigIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECJ6BdyIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgECC6BZEIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEB76BUWIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEB06BPoIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBt6BK6IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBm6BGMIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBf6BBeIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBY6A8wIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBR6A4CIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBK6AzUIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEBD6AumIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEA86Ap4IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEA16AlKIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAu6AgcIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAn6AbuIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgEAg6AXAIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAZ6SSIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAS6NkIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAL6I2IjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAE6EIIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgAiBg2IjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgApAllIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgAv/qUIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgA29vDIjgiXQgMgIgCgOQgDgPAIgMQAIgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgIAMQgIAMgOADIgIABQgKAAgJgGgA98zyIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEgk6gYgIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEgr5gdPIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEgy4gh+IjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEg52gmtIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhA0grbIjgiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDgCYQAMAIACAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhH0gwKIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEhOzg06IjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhVyg5oIjfiYQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDAMAIIDfCYQAMAIACAOQADAPgIAMQgIAMgPACIgGABQgLAAgJgGgEhcxg+XIjfiXQgMgIgCgPQgDgOAIgMQAIgMAOgCQAPgDALAIIDfCXQAMAIADAOQADAOgIAMQgIAMgPADIgHABQgKAAgJgGgEhjvhDFIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAPgIALQgIAMgPADIgHABQgKAAgJgGgEhquhHzIjfiXQgMgIgDgPQgDgOAIgMQAJgMAOgCQAOgDAMAIIDfCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEhxthMhIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEh4thRPIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEh/thV9IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiGtharIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiNthfZIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiUthkHIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEibtho1IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiithtjIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEipthyRIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEiwth2/IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEi3th7tIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEi+tiAbIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjFtiFJIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjMtiJ3IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjTtiOlIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjatiTTIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjhtiYBIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjoticvIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEjvtihdIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEj2timLIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEj9tiq5IjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEkEtivnIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGgEkLti0VIjgiXQgMgIgDgOQgDgPAIgMQAJgMAOgCQAOgDAMAIIDgCXQAMAIADAOQADAOgJAMQgIAMgOADIgHABQgKAAgJgGg");
	this.shape.setTransform(-7.1938,-4.8414);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.dashes_red, new cjs.Rectangle(-1744.5,-1180.5,3474.7,2351.4), null);


(lib.card_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.card();
	this.instance.parent = this;
	this.instance.setTransform(-88,-57.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.card_1, new cjs.Rectangle(-88,-57.5,176,115), null);


(lib.button = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF321E").s().p("AjLAzQgNgHgHgOQgIgNgBgRQABgQAIgNQAHgOANgHQAOgIARAAQARAAANAIQAOAHAHAOQAJANgBAQQABARgJANQgHANgOAIQgNAIgRAAQgRAAgOgIgAjAghQgIAFgFAJQgEAJgBAKQABALAEAJQAFAJAIAFQAIAFAMAAQAMAAAIgFQAIgFAFgJQAEgJABgLQgBgKgEgJQgFgJgIgFQgIgFgMAAQgLAAgJAFgAn9AzQgNgHgHgOQgIgNgBgRQABgQAIgNQAHgOANgHQAOgIARAAQARAAANAIQAOAHAHAOQAJANgBAQQABARgJANQgHANgOAIQgNAIgRAAQgRAAgOgIgAnyghQgIAFgFAJQgEAJgBAKQABALAEAJQAFAJAIAFQAIAFAMAAQAMAAAIgFQAIgFAFgJQAEgJABgLQgBgKgEgJQgFgJgIgFQgIgFgMAAQgLAAgJAFgAlQA6IAAgUIgZAAQgWAAgLgLQgLgKAAgSQAAgSALgKQAKgKAWAAIAaAAIAAgSIAWAAIAAASIAaAAQAWAAAKAKQAMAKAAASQAAASgMAKQgKALgWAAIgaAAIAAAUgAk6ATIAZAAQALgBAGgFQAFgFAAgIQAAgKgFgFQgGgFgLAAIgZAAgAl6gPQgFAFgBAKQABAIAFAFQAGAFAMABIAYAAIAAgnIgYAAQgMAAgGAFgABWA5IgmhcIAABcIgUAAIAAhxIAhAAIAhBSIAihSIAfAAIAABxIgVAAIAAhcIgmBcgAG0A5IAAhxIAWAAIAAAoIAnAAQAVAAAKAKQALAIAAASQAAASgLAJQgKAKgVAAgAHKAmIAmAAQAKAAAGgFQAEgFAAgIQAAgIgEgFQgGgFgKAAIgmAAgAFhA5IAAheIgtAAIAAgTIBwAAIAAATIgtAAIAABegAEPA5IAAhUIhABUIgWAAIAAhxIAWAAIAABUIBAhUIAVAAIAABxgAhdA5IAAhxIA/AAQATAAALAJQAJAJAAARQAAAQgJAJQgLAJgTAAIgpAAIAAAsgAhHgFIAoAAQAKAAAFgEQAEgFAAgHQAAgHgEgFQgFgEgKAAIgoAAg");
	this.shape.setTransform(-0.15,0.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ApcCGQgUAAAAgUIAAjjQAAgUAUAAIS5AAQAUAAAAAUIAADjQAAAUgUAAg");
	this.shape_1.setTransform(0.475,0.425);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.button, new cjs.Rectangle(-62,-14.6,125,28.5), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.whiterplane = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// plane
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgmBkIgLiBIg1ghQgJgFgFgLQgGgNAFgKQAHgIAOAAQAMABAJAGIAyAlIB8gmIAPANIhhA5IAvAhIAqgIIAOAJIgxAZIgFA3IgOgKIgIgqIgvgeIgRBvg");
	this.shape.setTransform(415.0185,25.9736);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(136));

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("EgmAgSLIGApOMBGBAtlImAJOgABghmQgfALgZAYQgaAYgNAfQgMAdABAjQAAAjANAeQAQAkAgAYQAfAZAmAHQAmAHAmgKQAmgMAcgaQAcgbANglQAOgmgFgmQgFgkgXgiQgXgggigSQgegQgigCIgNgBQgcAAgaAJg");
	var mask_graphics_135 = new cjs.Graphics().p("EgmAgSLIGApOMBGBAtlImAJOgABghmQgfALgZAYQgaAYgNAfQgMAdABAjQAAAjANAeQAQAkAgAYQAfAZAmAHQAmAHAmgKQAmgMAcgaQAcgbANglQAOgmgFgmQgFgkgXgiQgXgggigSQgegQgigCIgNgBQgcAAgaAJg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:398.575,y:18.15}).wait(135).to({graphics:mask_graphics_135,x:398.575,y:18.15}).wait(1));

	// Layer 1
	this.instance = new lib.dashes_white();
	this.instance.parent = this;
	this.instance.setTransform(460.9,56.05,0.24,0.24,0,0,0,0.2,0.4);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:599.9,y:149.05},135).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(155.3,-157.2,486.59999999999997,350.7);


(lib.TXT03 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt0303
	this.instance = new lib.txt0303();
	this.instance.parent = this;
	this.instance.setTransform(0,133);
	this.instance.alpha = 0.5;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(9).to({_off:false},0).wait(1).to({regX:-0.7,regY:3.5,x:-0.7,y:81.25,alpha:0.7511},0).wait(1).to({y:61.55,alpha:0.8406},0).wait(1).to({y:50.1,alpha:0.8927},0).wait(1).to({y:42.6,alpha:0.9267},0).wait(1).to({y:37.45,alpha:0.95},0).wait(1).to({y:33.9,alpha:0.9664},0).wait(1).to({y:31.35,alpha:0.9779},0).wait(1).to({y:29.55,alpha:0.986},0).wait(1).to({y:28.35,alpha:0.9916},0).wait(1).to({y:27.5,alpha:0.9953},0).wait(1).to({y:27,alpha:0.9977},0).wait(1).to({y:26.65,alpha:0.9991},0).wait(1).to({y:26.5,alpha:0.9998},0).wait(1).to({regX:0,regY:0,x:0,y:23,alpha:1},0).wait(57).to({regX:-0.7,regY:3.5,x:-0.7,y:26.55,alpha:0.9991},0).wait(1).to({y:26.8,alpha:0.996},0).wait(1).to({y:27.25,alpha:0.9905},0).wait(1).to({y:27.9,alpha:0.982},0).wait(1).to({y:28.9,alpha:0.97},0).wait(1).to({y:30.2,alpha:0.9537},0).wait(1).to({y:31.9,alpha:0.9324},0).wait(1).to({y:34.1,alpha:0.9048},0).wait(1).to({y:36.9,alpha:0.8694},0).wait(1).to({y:40.55,alpha:0.824},0).wait(1).to({y:45.25,alpha:0.7652},0).wait(1).to({y:51.5,alpha:0.6873},0).wait(1).to({y:60.15,alpha:0.5794},0).wait(1).to({y:73.35,alpha:0.4138},0).wait(1).to({regX:0,regY:0,x:0,y:103,alpha:0},0).wait(9));

	// txt0302
	this.instance_1 = new lib.txt0302();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,107);
	this.instance_1.alpha = 0.5;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).wait(1).to({regX:-0.4,regY:2.4,x:-0.4,y:49.1,alpha:0.7511},0).wait(1).to({y:27.65,alpha:0.8406},0).wait(1).to({y:15.1,alpha:0.8927},0).wait(1).to({y:6.95,alpha:0.9267},0).wait(1).to({y:1.4,alpha:0.95},0).wait(1).to({y:-2.5,alpha:0.9664},0).wait(1).to({y:-5.25,alpha:0.9779},0).wait(1).to({y:-7.2,alpha:0.986},0).wait(1).to({y:-8.55,alpha:0.9916},0).wait(1).to({y:-9.45,alpha:0.9953},0).wait(1).to({y:-10.05,alpha:0.9977},0).wait(1).to({y:-10.35,alpha:0.9991},0).wait(1).to({y:-10.55,alpha:0.9998},0).wait(1).to({regX:0,regY:0,x:0,y:-13,alpha:1},0).wait(66).to({regX:-0.4,regY:2.4,x:-0.4,y:-10.5,alpha:0.9991},0).wait(1).to({y:-10.25,alpha:0.996},0).wait(1).to({y:-9.8,alpha:0.9905},0).wait(1).to({y:-9.15,alpha:0.982},0).wait(1).to({y:-8.15,alpha:0.97},0).wait(1).to({y:-6.85,alpha:0.9537},0).wait(1).to({y:-5.15,alpha:0.9324},0).wait(1).to({y:-2.95,alpha:0.9048},0).wait(1).to({y:-0.15,alpha:0.8694},0).wait(1).to({y:3.45,alpha:0.824},0).wait(1).to({y:8.15,alpha:0.7652},0).wait(1).to({y:14.4,alpha:0.6873},0).wait(1).to({y:23.05,alpha:0.5794},0).wait(1).to({y:36.25,alpha:0.4138},0).wait(1).to({regX:0,regY:0,x:0,y:67,alpha:0},0).wait(5));

	// txt0301
	this.instance_2 = new lib.txt0301();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,89);
	this.instance_2.alpha = 0.5;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:-0.6,regY:2.3,x:-0.6,y:20.95,alpha:0.7511},0).wait(1).to({y:-4.05,alpha:0.8406},0).wait(1).to({y:-18.65,alpha:0.8927},0).wait(1).to({y:-28.15,alpha:0.9267},0).wait(1).to({y:-34.7,alpha:0.95},0).wait(1).to({y:-39.25,alpha:0.9664},0).wait(1).to({y:-42.5,alpha:0.9779},0).wait(1).to({y:-44.75,alpha:0.986},0).wait(1).to({y:-46.3,alpha:0.9916},0).wait(1).to({y:-47.35,alpha:0.9953},0).wait(1).to({y:-48.05,alpha:0.9977},0).wait(1).to({y:-48.45,alpha:0.9991},0).wait(1).to({y:-48.6,alpha:0.9998},0).wait(1).to({regX:0,regY:0,x:0,y:-51,alpha:1},0).wait(74).to({regX:-0.6,regY:2.3,x:-0.6,y:-48.6,alpha:0.9991},0).wait(1).to({y:-48.35,alpha:0.996},0).wait(1).to({y:-47.9,alpha:0.9905},0).wait(1).to({y:-47.25,alpha:0.982},0).wait(1).to({y:-46.25,alpha:0.97},0).wait(1).to({y:-44.95,alpha:0.9537},0).wait(1).to({y:-43.25,alpha:0.9324},0).wait(1).to({y:-41.05,alpha:0.9048},0).wait(1).to({y:-38.25,alpha:0.8694},0).wait(1).to({y:-34.6,alpha:0.824},0).wait(1).to({y:-29.9,alpha:0.7652},0).wait(1).to({y:-23.65,alpha:0.6873},0).wait(1).to({y:-15,alpha:0.5794},0).wait(1).to({y:-1.8,alpha:0.4138},0).wait(1).to({regX:0,regY:0,x:0,y:29,alpha:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56,-61,111.1,210.1);


(lib.TXT02 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_18 = new cjs.Graphics().p("A0uiKMApdAAAIAAEcMgpdAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(18).to({graphics:mask_graphics_18,x:-17,y:14.6185}).wait(85));

	// txt0202
	this.instance = new lib.txt0202();
	this.instance.parent = this;
	this.instance.setTransform(0,-17.9,1,1,0,0,0,106,26.6);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(18).to({_off:false},0).wait(1).to({regX:107.5,regY:30.9,x:1.5,y:-2.3},0).wait(1).to({y:2.75},0).wait(1).to({y:6},0).wait(1).to({y:8.35},0).wait(1).to({y:10.1},0).wait(1).to({y:11.45},0).wait(1).to({y:12.45},0).wait(1).to({y:13.25},0).wait(1).to({y:13.85},0).wait(1).to({y:14.25},0).wait(1).to({y:14.6},0).wait(1).to({y:14.8},0).wait(1).to({y:14.9},0).wait(1).to({regX:106,regY:26.6,x:0,y:10.6},0).wait(52).to({regX:107.5,regY:30.9,x:1.5,y:15},0).wait(1).to({y:15.15},0).wait(1).to({y:15.45},0).wait(1).to({y:15.9},0).wait(1).to({y:16.5},0).wait(1).to({y:17.25},0).wait(1).to({y:18.2},0).wait(1).to({y:19.4},0).wait(1).to({y:20.85},0).wait(1).to({y:22.65},0).wait(1).to({y:24.85},0).wait(1).to({y:27.55},0).wait(1).to({y:31},0).wait(1).to({y:35.75},0).wait(1).to({regX:106,regY:26.6,x:0,y:39.1},0).wait(5));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("A0ujAMApdAAAIAAEcMgpdAAAg");
	var mask_1_graphics_87 = new cjs.Graphics().p("A0ujAMApdAAAIAAEcMgpdAAAg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:-17,y:-19.2815}).wait(87).to({graphics:mask_1_graphics_87,x:-17,y:-19.2815}).wait(16));

	// txt0201
	this.instance_1 = new lib.txt0201();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-10.5,-56.9,1,1,0,0,0,95.5,26.6);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:96.2,regY:30.9,x:-9.8,y:-41.3},0).wait(1).to({y:-36.25},0).wait(1).to({y:-33},0).wait(1).to({y:-30.65},0).wait(1).to({y:-28.9},0).wait(1).to({y:-27.55},0).wait(1).to({y:-26.55},0).wait(1).to({y:-25.75},0).wait(1).to({y:-25.15},0).wait(1).to({y:-24.75},0).wait(1).to({y:-24.4},0).wait(1).to({y:-24.2},0).wait(1).to({y:-24.1},0).wait(1).to({regX:95.5,regY:26.6,x:-10.5,y:-28.4},0).wait(74).to({regX:96.2,regY:30.9,x:-9.8,y:-24},0).wait(1).to({y:-23.85},0).wait(1).to({y:-23.55},0).wait(1).to({y:-23.1},0).wait(1).to({y:-22.5},0).wait(1).to({y:-21.75},0).wait(1).to({y:-20.8},0).wait(1).to({y:-19.6},0).wait(1).to({y:-18.15},0).wait(1).to({y:-16.35},0).wait(1).to({y:-14.15},0).wait(1).to({y:-11.45},0).wait(1).to({y:-7.95},0).wait(1).to({y:-3.2},0).wait(1).to({regX:95.5,regY:26.6,x:-10.5,y:0.1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-102,-38.5,207,67.8);


(lib.TXT01 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask copy (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_19 = new cjs.Graphics().p("A0uhnMApdAAAIAAEcMgpdAAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(19).to({graphics:mask_graphics_19,x:-3.95,y:18.0935}).wait(64).to({graphics:null,x:0,y:0}).wait(5));

	// txt0102
	this.instance = new lib.txt0102();
	this.instance.parent = this;
	this.instance.setTransform(-0.1,-8.75,1,1,0,0,0,93.9,17.4);
	this.instance._off = true;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(19).to({_off:false},0).wait(1).to({regX:94.1,regY:20.6,x:0.1,y:2.7},0).wait(1).to({y:7.65},0).wait(1).to({y:10.95},0).wait(1).to({y:13.25},0).wait(1).to({y:14.9},0).wait(1).to({y:16.1},0).wait(1).to({y:16.95},0).wait(1).to({y:17.55},0).wait(1).to({y:18},0).wait(1).to({y:18.25},0).wait(1).to({y:18.45},0).wait(1).to({y:18.55},0).wait(1).to({y:18.6},0).wait(1).to({regX:93.9,regY:17.4,x:-0.1,y:15.4},0).wait(35).to({regX:94.1,regY:20.6,x:0.1,y:18.7},0).wait(1).to({y:18.9},0).wait(1).to({y:19.25},0).wait(1).to({y:19.8},0).wait(1).to({y:20.45},0).wait(1).to({y:21.25},0).wait(1).to({y:22.3},0).wait(1).to({y:23.55},0).wait(1).to({y:25},0).wait(1).to({y:26.75},0).wait(1).to({y:28.9},0).wait(1).to({y:31.45},0).wait(1).to({y:34.65},0).wait(1).to({y:38.95},0).wait(1).to({regX:93.9,regY:17.4,x:-0.1,y:43.4},0).to({_off:true},1).wait(5));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A0uiSMApdAAAIAAEcMgpdAAAg");
	mask_1.setTransform(-3.95,-14.7065);

	// txt0101
	this.instance_1 = new lib.txt0101();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-25.2,-43.25,1,1,0,0,0,68.8,17.4);

	var maskedShapeInstanceList = [this.instance_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({regX:69.5,regY:21.3,x:-24.5,y:-32.3},0).wait(1).to({y:-28.05},0).wait(1).to({y:-25.2},0).wait(1).to({y:-23.25},0).wait(1).to({y:-21.85},0).wait(1).to({y:-20.85},0).wait(1).to({y:-20.1},0).wait(1).to({y:-19.6},0).wait(1).to({y:-19.2},0).wait(1).to({y:-19},0).wait(1).to({y:-18.8},0).wait(1).to({y:-18.75},0).wait(1).to({y:-18.7},0).wait(1).to({regX:68.8,regY:17.4,x:-25.2,y:-22.6},0).wait(59).to({regX:69.5,regY:21.3,x:-24.5,y:-18.6},0).wait(1).to({y:-18.4},0).wait(1).to({y:-18.05},0).wait(1).to({y:-17.5},0).wait(1).to({y:-16.85},0).wait(1).to({y:-16},0).wait(1).to({y:-14.95},0).wait(1).to({y:-13.7},0).wait(1).to({y:-12.25},0).wait(1).to({y:-10.5},0).wait(1).to({y:-8.35},0).wait(1).to({y:-5.8},0).wait(1).to({y:-2.6},0).wait(1).to({y:1.7},0).wait(1).to({regX:68.8,regY:17.4,x:-25.2,y:5.4},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-90,-29.4,180.2,65.6);


(lib.sun = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween3("synched",0);
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sun, new cjs.Rectangle(-115.8,-115.9,231.7,231.8), null);


(lib.redplane = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// plane
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E63428").s().p("AgmBkIgLiBIg1ghQgJgFgFgLQgGgNAFgKQAHgIAOAAQAMABAJAGIAyAlIB8gmIAPANIhhA5IAvAhIAqgIIAOAJIgxAZIgFA3IgOgKIgIgqIgvgeIgRBvg");
	this.shape.setTransform(415.0185,25.9736);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(136));

	// Layer 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AMslTIGApOIfcUdImAJNg");
	mask.setTransform(320.8005,96.9371);

	// Layer 1
	this.instance = new lib.dashes_red();
	this.instance.parent = this;
	this.instance.setTransform(460.9,56.05,0.24,0.24,0,0,0,0.2,0.4);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:599.9,y:149.05},135).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(402,4,239.60000000000002,189.9);


(lib.planeAnimation = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Whiteplane copy
	this.instance = new lib.redplane("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(380.2,-710.1,1.82,1.82,110.9985,0,0,-0.1,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:494.2,y:-787.1,startPosition:88},224).wait(76));

	// SUN
	this.instance_1 = new lib.sun();
	this.instance_1.parent = this;
	this.instance_1.setTransform(108,-19);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:65},224).wait(76));

	// Whiteplane
	this.instance_2 = new lib.whiterplane("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(-435,-69);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:-470,y:-134,startPosition:89},224).wait(76));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-342.8,-291.2,566.7,583.7);


(lib.LOGOgroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Whitelogo();
	this.instance.parent = this;
	this.instance.setTransform(0.5,0.25,0.32,0.32,0,0,0,207.8,63.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGOgroup, new cjs.Rectangle(-66,-20,133.1,40.4), null);


(lib.legall = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.legal_1();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regX:-0.5,regY:-0.5,x:-0.5,y:-0.5,alpha:0.2671},0).wait(1).to({alpha:0.4243},0).wait(1).to({alpha:0.5412},0).wait(1).to({alpha:0.6346},0).wait(1).to({alpha:0.7116},0).wait(1).to({alpha:0.7762},0).wait(1).to({alpha:0.8305},0).wait(1).to({alpha:0.8762},0).wait(1).to({alpha:0.914},0).wait(1).to({alpha:0.9447},0).wait(1).to({alpha:0.9686},0).wait(1).to({alpha:0.9859},0).wait(1).to({alpha:0.9964},0).wait(1).to({regX:0,regY:0,x:0,y:0,alpha:1},0).wait(56).to({regX:-0.5,regY:-0.5,x:-0.5,y:-0.5,alpha:0.9972},0).wait(1).to({alpha:0.9887},0).wait(1).to({alpha:0.9749},0).wait(1).to({alpha:0.9555},0).wait(1).to({alpha:0.9305},0).wait(1).to({alpha:0.8994},0).wait(1).to({alpha:0.862},0).wait(1).to({alpha:0.8173},0).wait(1).to({alpha:0.7644},0).wait(1).to({alpha:0.7018},0).wait(1).to({alpha:0.6271},0).wait(1).to({alpha:0.5364},0).wait(1).to({alpha:0.4222},0).wait(1).to({alpha:0.2675},0).wait(1).to({regX:0,regY:0,x:0,y:0,alpha:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68,-49,135,97);


(lib.butt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.button();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:1.05,scaleY:1.05},0).wait(1).to({scaleX:0.95,scaleY:0.95},0).wait(1).to({scaleX:1,scaleY:1},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-65.1,-13.6,131.2,28.2);


(lib.movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// footer
	this.instance = new lib.Footer();
	this.instance.parent = this;
	this.instance.setTransform(122.35,393.35);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(412));

	// LOGO
	this.instance_1 = new lib.LOGOgroup();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120.6,42.2,1,1,0,0,0,0.6,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(412));

	// BUTT
	this.instance_2 = new lib.butt();
	this.instance_2.parent = this;
	this.instance_2.setTransform(120.45,337.4,0.25,0.25);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;
	new cjs.ButtonHelper(this.instance_2, 0, 1, 2, false, new lib.butt(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(215).to({_off:false},0).wait(1).to({regX:0.5,regY:0.4,scaleX:0.5337,scaleY:0.5337,x:120.7,y:337.6,alpha:0.3783},0).wait(1).to({scaleX:0.6732,scaleY:0.6732,x:120.8,y:337.65,alpha:0.5643},0).wait(1).to({scaleX:0.7643,scaleY:0.7643,x:120.85,y:337.7,alpha:0.6857},0).wait(1).to({scaleX:0.829,scaleY:0.829,y:337.75,alpha:0.772},0).wait(1).to({scaleX:0.8767,scaleY:0.8767,x:120.9,alpha:0.8356},0).wait(1).to({scaleX:0.9125,scaleY:0.9125,alpha:0.8833},0).wait(1).to({scaleX:0.9394,scaleY:0.9394,y:337.8,alpha:0.9192},0).wait(1).to({scaleX:0.9596,scaleY:0.9596,x:120.95,alpha:0.9461},0).wait(1).to({scaleX:0.9744,scaleY:0.9744,alpha:0.9659},0).wait(1).to({scaleX:0.9851,scaleY:0.9851,alpha:0.9801},0).wait(1).to({scaleX:0.9923,scaleY:0.9923,alpha:0.9898},0).wait(1).to({scaleX:0.9969,scaleY:0.9969,alpha:0.9958},0).wait(1).to({scaleX:0.9993,scaleY:0.9993,alpha:0.9991},0).wait(1).to({regX:0,regY:0,scaleX:1,scaleY:1,x:120.45,y:337.4,alpha:1},0).wait(157).to({alpha:0},12).wait(14));

	// LEGAL
	this.instance_3 = new lib.legall("synched",0,false);
	this.instance_3.parent = this;
	this.instance_3.setTransform(120,182);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(312).to({_off:false},0).wait(100));

	// CARD
	this.instance_4 = new lib.card_1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(121,440);
	this.instance_4.alpha = 0.5;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(183).to({_off:false},0).wait(1).to({y:375.6432,alpha:0.6694},0).wait(1).to({y:344.969,alpha:0.7501},0).wait(1).to({y:324.2069,alpha:0.8047},0).wait(1).to({y:308.7598,alpha:0.8454},0).wait(1).to({y:296.7368,alpha:0.877},0).wait(1).to({y:287.1406,alpha:0.9023},0).wait(1).to({y:279.3685,alpha:0.9227},0).wait(1).to({y:273.0234,alpha:0.9394},0).wait(1).to({y:267.8268,alpha:0.9531},0).wait(1).to({y:263.5743,alpha:0.9643},0).wait(1).to({y:260.1105,alpha:0.9734},0).wait(1).to({y:257.3136,alpha:0.9808},0).wait(1).to({y:255.0863,alpha:0.9866},0).wait(1).to({y:253.3487,alpha:0.9912},0).wait(1).to({y:252.0345,alpha:0.9946},0).wait(1).to({y:251.0875,alpha:0.9971},0).wait(1).to({y:250.4597,alpha:0.9988},0).wait(1).to({y:250.1094,alpha:0.9997},0).wait(1).to({y:250,alpha:1},0).wait(87).to({y:250.5298,alpha:0.9967},0).wait(1).to({y:252.1867,alpha:0.9863},0).wait(1).to({y:255.0889,alpha:0.9682},0).wait(1).to({y:259.3839,alpha:0.9414},0).wait(1).to({y:265.2602,alpha:0.9046},0).wait(1).to({y:272.9668,alpha:0.8565},0).wait(1).to({y:282.8471,alpha:0.7947},0).wait(1).to({y:295.4015,alpha:0.7162},0).wait(1).to({y:311.4203,alpha:0.6161},0).wait(1).to({y:332.3128,alpha:0.4855},0).wait(1).to({y:361.1974,alpha:0.305},0).wait(1).to({y:410,alpha:0},0).to({_off:true},1).wait(111));

	// TXT03
	this.instance_5 = new lib.TXT03("synched",0,false);
	this.instance_5.parent = this;
	this.instance_5.setTransform(120.9,139.6);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(207).to({_off:false},0).to({_off:true},105).wait(100));

	// TXT02
	this.instance_6 = new lib.TXT02("synched",0,false);
	this.instance_6.parent = this;
	this.instance_6.setTransform(117.95,140.05);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(94).to({_off:false},0).to({_off:true},100).wait(218));

	// TXT01
	this.instance_7 = new lib.TXT01("synched",0,false);
	this.instance_7.parent = this;
	this.instance_7.setTransform(123.9,140.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},95).wait(317));

	// BG
	this.instance_8 = new lib.RED();
	this.instance_8.parent = this;
	this.instance_8.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({alpha:0},19).wait(144).to({alpha:1},30).to({_off:true},1).wait(218));

	// PLANE
	this.instance_9 = new lib.planeAnimation("synched",0);
	this.instance_9.parent = this;
	this.instance_9.setTransform(62.7,372.3,1,1,0,0,0,-0.3,0.3);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).to({_off:true},194).wait(218));

	// BG
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF321E").s().p("AybfQQgUAAAAgUMAAAg93QAAgUAUAAMAk3AAAQAUAAAAAUMAAAA93QAAAUgUAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(412));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-513,-13,1024,677.5);


// stage content:
(lib.alfa_travel19_2_240x400_rewiev = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("Ayv/PMAlfAAAMAAAA+fMglfAAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// movie
	this.instance = new lib.movie();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// button
	this.instance_1 = new lib.btn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(120,200);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape_1.setTransform(120,199.975);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-587,-287.5,1388.7,1592.1);
// library properties:
lib.properties = {
	id: '43753D276AC4104E8D026481CD8E8EE1',
	width: 240,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"card.png", id:"card"},
		{src:"legal.png", id:"legal"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['43753D276AC4104E8D026481CD8E8EE1'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;