(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"gpb_arflvisa_plane_300x600_review_atlas_P_", frames: [[0,0,520,754]]},
		{name:"gpb_arflvisa_plane_300x600_review_atlas_NP_", frames: [[0,0,481,481]]}
];


// symbols:



(lib.bndrchk = function() {
	this.initialize(ss["gpb_arflvisa_plane_300x600_review_atlas_NP_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.legal = function() {
	this.initialize(ss["gpb_arflvisa_plane_300x600_review_atlas_P_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txtS0301 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHqDJIAAgcIhOAAIAAhiIAPAAIAABVIAvAAIAAhVIAPAAIAABVIAQAAIAAApgADeCoQgMgHgHgLQgGgMAAgOQAAgOAGgMQAHgLAMgHQALgHAOAAQANAAALAGQAKAFAHAKIgLAJQgMgQgSAAQgJAAgJAFQgHAFgFAIQgFAJAAAKQAAAKAFAJQAFAIAHAFQAJAFAJAAQASAAAMgQIALAJQgHAKgKAFQgLAGgNAAQgOAAgLgHgABvCoQgMgGgHgMQgGgMgBgOQAAgOAHgMQAGgLAMgHQALgHAPAAQAMAAAKAGQAKAFAGAKQAFAKABANIgBAMIhOAAQACAOAKAJQAKAJAOAAQARAAANgNIAJAKQgIAIgKAFQgKAEgLAAQgPAAgLgHgABxBfQgIAIgDANIA+AAQAAgNgJgIQgIgIgMAAQgNAAgJAIgAliCoQgLgHgHgLQgGgMAAgOQAAgOAGgMQAHgLAMgHQALgHAOAAQAOAAAMAHQAMAHAGALQAIAMgBAOQABAOgIAMQgGALgMAHQgMAHgOAAQgOAAgMgHgAlaBcQgHAFgFAIQgFAJAAAKQAAALAFAIQAFAIAHAFQAJAFAJAAQAKAAAIgFQAIgFAFgIQAFgIgBgLQABgKgFgJQgEgIgJgFQgHgFgLAAQgJAAgJAFgAqbCoQgKgIAAgMQAAgNAKgHQAJgIAQAAIAfAAIAAgIQAAgMgHgHQgGgGgLAAQgJAAgHAEQgHAEgGAIIgJgJQAGgKALgGQAKgFAMAAQARAAAKAKQALALAAATIAAA8IgOAAIAAgNQgGAHgIAEQgIAEgLAAQgPAAgJgHgAqQCIQgFAEgBAHQAAAHAHAEQAFAEAJAAQAIAAAGgDQAIgEADgGQAFgHAAgHIAAgDIgdAAQgKAAgGAEgAvKCoQgMgHgHgLQgHgMAAgOQAAgOAHgMQAHgLAMgHQALgHAOAAQANAAAKAGQALAFAGAKIgLAJQgLgQgSAAQgKAAgIAFQgIAFgFAIQgEAJAAAKQAAAKAEAJQAFAIAIAFQAIAFAKAAQASAAALgQIALAJQgGAKgLAFQgKAGgNAAQgOAAgLgHgAw5CoQgNgGgGgMQgHgMAAgOQAAgOAGgMQAHgLALgHQAMgHAOAAQAMAAALAGQAKAFAGAKQAFAKAAANIgBAMIhNAAQABAOALAJQAKAJAOAAQAQAAAOgNIAJAKQgIAIgKAFQgKAEgMAAQgOAAgLgHgAw3BfQgJAIgCANIA9AAQAAgNgIgIQgJgIgMAAQgMAAgJAIgAyxCoQgLgHgHgMQgGgNAAgQIAAgRQAAgWAEgPQAFgOANgKQANgJAZgFQAZgEAIgDIAAANQgJAFgWADQgVADgKAIQgLAHgCALQgDAKAAAPQAGgJAKgFQAKgFALAAQANAAAMAGQALAHAGALQAHAMAAANQAAANgHAMQgHALgLAGQgMAHgOAAQgOAAgMgHgAyoBgQgIAEgEAIQgFAIgBAKQABAJAFAIQAEAJAIAEQAIAFAJAAQAKAAAIgFQAIgEAFgIQAEgIAAgKQAAgKgEgIQgFgIgIgEQgIgFgKAAQgJAAgIAFgAFuCtIAAgkIgTAAIgaAkIgSAAIAdgmQgMgDgFgHQgHgIAAgKQAAgPAJgIQAKgJAQAAIAmAAIAABigAFJBeQgFAFAAAIQAAAIAFAFQAGAFAJAAIAWAAIAAgkIgXAAQgIAAgGAFgAAvCtIAAhCIgiAoIgGAAIgggoIAABCIgQAAIAAhkIAGAAIAuA3IAtg3IAGAAIAABkgAjHCtIAAhiIAnAAQAPAAAJAHQAIAHAAAMQAAAGgDAFQgDAEgEAEQAJADAFAGQAEAGAAAIQABANgKAIQgKAJgPAAgAi4CgIAcAAQALAAAEgFQAGgEAAgIQAAgHgGgEQgEgEgLAAIgcAAgAi4BzIAZAAQAIAAAEgDQAEgEAAgGQAAgNgQAAIgZAAgAmiCtIAAgtIgwAAIAAAtIgPAAIAAhiIAPAAIAAAoIAwAAIAAgoIAQAAIAABigAojCtIAAhUIghAAIAAgOIBRAAIAAAOIghAAIAABUgArMCtIAAhUIgkAAIAAAMQAAAZgDAQQgDAPgHAIQgHAIgLAAIgGgBIAAgMIAFAAQAJAAAEgOQAEgPABgeIAAgaIBCAAIAABigAs0CtIAAhUIgvAAIAABUIgPAAIAAhiIBOAAIAABigAMygMIAAiFIAOAAIAAAQQAFgJAKgFQALgEAKAAQAOAAALAGQAMAHAFAMQAHALAAAOQAAAPgHALQgFAMgMAHQgLAGgOAAQgKAAgKgEQgJgEgGgIIAAAygANSiBQgIAEgEAIQgFAIgBAMQABANAFAIQAEAJAIAEQAHAEAJAAQALAAAHgFQAIgFAEgIQAFgJAAgKQAAgLgFgIQgEgJgIgFQgHgEgLAAQgJAAgHAEgAFbgMIAAiFIAPAAIAAAQQAFgJALgFQAKgEAKAAQAOAAAMAGQAKAHAHAMQAGALAAAOQAAAPgGALQgHAMgKAHQgMAGgOAAQgKAAgJgEQgKgEgGgIIAAAygAF8iBQgIAEgEAIQgGAIAAAMQAAANAGAIQAEAJAIAEQAHAEAKAAQAKAAAHgFQAIgFAEgIQAFgJAAgKQAAgLgFgIQgEgJgIgFQgHgEgKAAQgKAAgHAEgAQVg0QgLgHgHgMQgHgMAAgNQAAgOAHgMQAHgMALgHQAMgGAOAAQAOAAAMAGQAMAHAGAMQAHAMAAAOQAAANgHAMQgGAMgMAHQgMAGgOAAQgOAAgMgGgAQdiBQgIAFgFAJQgEAIAAALQAAAKAEAIQAFAJAIAFQAIAFAKAAQAJAAAJgFQAIgFAEgJQAFgIAAgKQAAgLgFgIQgEgJgIgFQgIgEgKAAQgKAAgIAEgALMg0QgLgHgHgMQgGgMAAgNQAAgOAGgMQAHgMAMgHQALgGAOAAQAOAAAMAGQAMAHAGAMQAIAMgBAOQABANgIAMQgGAMgMAHQgMAGgOAAQgOAAgMgGgALUiBQgHAFgFAJQgFAIAAALQAAAKAFAIQAFAJAHAFQAJAFAJAAQAKAAAIgFQAIgFAFgJQAFgIgBgKQABgLgFgIQgEgJgJgFQgHgEgLAAQgJAAgJAEgAHpg0QgMgHgGgMQgHgMAAgNQAAgOAHgMQAGgMAMgHQAMgGAOAAQAOAAAMAGQAMAHAGAMQAHAMAAAOQAAANgHAMQgGAMgMAHQgMAGgOAAQgOAAgMgGgAHxiBQgIAFgEAJQgFAIAAALQAAAKAFAIQAEAJAIAFQAIAFAKAAQAJAAAIgFQAJgFAEgJQAFgIAAgKQAAgLgFgIQgEgJgIgFQgIgEgKAAQgKAAgIAEgAD6gzQgLgGgGgKIALgIQAMAQAQAAQAPAAAJgJQAKgJABgOIgqAAIAAgNIAqAAQgCgNgKgIQgKgIgNAAQgRAAgLAQIgLgJQAGgKALgGQAKgFAMAAQAOAAAMAGQAMAHAHAMQAGALABAOQgBAOgGAMQgHAMgMAHQgMAGgOAAQgMAAgKgFgACMg1QgKgHAAgNQAAgMAKgIQAKgHAPAAIAfAAIAAgJQAAgMgGgGQgGgGgMAAQgJAAgGAEQgHAEgGAHIgKgIQAHgLAKgFQAKgFAMAAQARAAALAKQAKAKAAATIAAA8IgOAAIAAgMQgFAHgJAEQgIADgLAAQgOAAgKgHgACYhUQgGADAAAHQAAAIAGAEQAGAEAIAAQAJAAAGgEQAHgDAEgHQAEgGAAgIIAAgCIgdAAQgKAAgFAEgAj+g1QgKgHAAgNQAAgMAKgIQAKgHAPAAIAfAAIAAgJQAAgMgGgGQgHgGgLAAQgJAAgGAEQgHAEgGAHIgKgIQAGgLALgFQAKgFAMAAQARAAALAKQALAKgBATIAAA8IgOAAIAAgMQgFAHgJAEQgIADgLAAQgOAAgKgHgAjyhUQgGADAAAHQAAAIAGAEQAGAEAIAAQAIAAAHgEQAHgDAEgHQAEgGAAgIIAAgCIgdAAQgKAAgFAEgAlSgyQgKgFgGgJIALgJQAFAGAGAEQAGAEAJAAQAKAAAGgFQAFgFABgIQgBgHgFgEQgGgFgKAAIgLAAIAAgMIALAAQAJAAAEgEQAEgEAAgGQAAgHgEgEQgFgDgJAAQgIAAgFADQgGADgFAGIgKgJQAGgIAIgFQAJgEAMAAQAPAAAIAHQAJAHAAAMQAAAHgCAGQgDAFgGAEQAHADAFAGQAEAGAAAJQAAANgKAIQgKAIgQAAQgNAAgJgEgAn1g0QgMgHgGgMQgHgMAAgOQAAgOAHgLQAGgMAMgHQAMgGAOAAQANAAAKAFQAKAGAHAKIgLAJQgLgQgSAAQgKAAgIAFQgIAEgEAJQgFAIAAAKQAAALAFAIQAEAJAIAFQAIAFAKAAQASAAALgQIALAIQgHAKgKAGQgKAFgNAAQgOAAgMgGgApjg0QgMgHgHgMQgHgLAAgOQAAgOAHgMQAGgMAMgHQALgGAOAAQAMAAAKAFQAKAGAHAKQAFAKAAANIgBALIhNAAQABAPAKAJQALAJAOAAQAQAAANgOIAJALQgHAIgKAEQgKAEgLAAQgPAAgLgGgAphh9QgJAIgCANIA+AAQgBgOgIgIQgIgHgNAAQgMAAgJAIgAs2gyQgJgFgHgJIALgJQAEAGAHAEQAGAEAJAAQALAAAFgFQAFgFAAgIQAAgHgFgEQgFgFgLAAIgKAAIAAgMIAKAAQAJAAADgEQAFgEAAgGQAAgHgFgEQgEgDgIAAQgIAAgHADQgFADgFAGIgKgJQAGgIAIgFQAJgEAMAAQAPAAAIAHQAJAHAAAMQAAAHgDAGQgDAFgFAEQAIADAEAGQAEAGAAAJQAAANgKAIQgKAIgQAAQgMAAgKgEgAutguIAAhjIAQAAIAABFIA7hHIAFAAIAABjIgPAAIAAhFIg7BHgAwSg0QgLgHgHgNQgGgMAAgQIAAgRQAAgXAFgOQAEgPANgJQANgKAZgEQAZgFAIgDIAAAOQgKAEgVAEQgVADgKAHQgLAIgCAKQgDAKAAAQQAGgJAKgFQAKgGALAAQANAAAMAHQALAHAHALQAGALAAANQAAAOgHALQgGAMgMAGQgMAGgOAAQgPAAgLgGgAwJh9QgIAFgEAIQgGAIAAAJQAAAKAGAIQAEAIAIAFQAIAFAKAAQAJAAAIgFQAIgFAEgIQAFgIAAgKQAAgJgFgIQgEgIgIgFQgIgFgJAAQgKAAgIAFgAR6gwIAAhhIAoAAQAOAAAJAHQAIAHAAALQABAGgDAFQgDAFgFADQAJADAFAGQAFAGAAAJQAAANgJAIQgKAIgQAAgASKg8IAcAAQAKAAAFgFQAGgFgBgHQABgHgGgFQgFgEgKAAIgcAAgASKhpIAZAAQAHAAAEgEQAEgDAAgGQAAgNgPAAIgZAAgAPBgwIAAhTIghAAIAAgOIBRAAIAAAOIghAAIAABTgAKMgwIAAhTIgvAAIAABTIgPAAIAAhhIBOAAIAABhgAAngwIAAhhIAQAAIAABhgAgxgwIAAhhIAQAAIAAAhIAXAAQAPAAAKAJQAKAJAAAOQAAAPgKAJQgKAIgPAAgAghg8IAWAAQAKAAAEgFQAGgFAAgJQAAgKgGgFQgEgFgLAAIgVAAgAhggwIAAhTIgkAAIAAAMQAAAZgDAPQgEAQgGAIQgHAHgLAAIgFgBIAAgMIADABQAKAAAEgPQAEgPAAgeIABgZIBCAAIAABhgAqkgwIAAgtIgwAAIAAAtIgPAAIAAhhIAPAAIAAAoIAwAAIAAgoIAPAAIAABhgAzEgwIAAhhIAoAAQAOAAAJAHQAIAHAAALQABAGgDAFQgDAFgEADQAIADAFAGQAFAGAAAJQAAANgJAIQgKAIgQAAgAy0g8IAcAAQAKAAAFgFQAGgFgBgHQABgHgGgFQgFgEgKAAIgcAAgAy0hpIAZAAQAHAAAEgEQAEgDAAgGQAAgNgPAAIgZAAgAmjhoIAAgNIAxAAIAAANg");
	this.shape.setTransform(124.6,27.075);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtS0301, new cjs.Rectangle(-1.7,0,248.89999999999998,51.3), null);


(lib.txtS0201 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ALUBaIAAgcIhNAAIAAAcIgPAAIAAgoIALAAQAHgIADgOQADgOAAgVIAAgcIBEAAIAABVIAQAAIAAAogAKfgHQgBAUgDAPQgDAOgFAIIAxAAIAAhGIglAAgAIjA6QgMgIgGgLQgHgMAAgNQAAgOAHgLQAGgMAMgHQAMgGAOgBQAOABAMAGQAMAHAGAMQAHALAAAOQAAANgHAMQgGALgMAIQgMAGgOAAQgOAAgMgGgAIrgSQgIAFgEAJQgFAHAAALQAAAKAFAIQAEAJAIAEQAIAGAKAAQAJAAAJgGQAIgEAEgJQAFgIAAgKQAAgLgFgHQgEgJgIgFQgIgFgKABQgKgBgIAFgACEA6QgMgIgGgLQgHgMAAgNQAAgOAHgLQAGgMAMgHQAMgGAOgBQAOABAMAGQAMAHAGAMQAHALAAAOQAAANgHAMQgGALgMAIQgMAGgOAAQgOAAgMgGgACMgSQgIAFgEAJQgFAHAAALQAAAKAFAIQAEAJAIAEQAIAGAKAAQAJAAAJgGQAIgEAEgJQAFgIAAgKQAAgLgFgHQgEgJgIgFQgIgFgKABQgKgBgIAFgAi1A5QgKgHAAgNQAAgNAKgHQAJgIAQAAIAfAAIAAgIQAAgLgGgHQgGgFgLAAQgKAAgGADQgHAEgGAIIgKgJQAGgKALgFQALgGAMAAQARAAAKAKQAKALAAASIAAA8IgOAAIAAgMQgFAGgJAEQgIAEgKAAQgQAAgJgHgAiqAZQgFAEAAAHQAAAHAGAFQAFAEAJgBQAJAAAGgDQAHgEAEgGQAEgGAAgIIAAgCIgdAAQgKAAgGADgAnkA6QgMgIgHgLQgGgMAAgOQAAgNAGgLQAHgMAMgHQALgGAOgBQANABALAFQAKAGAHAJIgLAJQgMgPgSAAQgJAAgJAEQgHAFgFAJQgFAHAAAKQAAALAFAIQAFAJAHAEQAJAGAJAAQASgBAMgQIALAJQgHAKgKAGQgLAFgNAAQgOAAgLgGgApTA6QgMgHgHgMQgGgMgBgNQAAgOAHgLQAGgMAMgHQALgGAPgBQAMABAKAFQAKAGAGAJQAFAKABAMIgBAMIhOAAQACAOAKAKQAKAJAOAAQARAAANgOIAJALQgIAHgKAFQgKAEgLAAQgPAAgLgGgApRgOQgIAHgDANIA+AAQAAgNgJgIQgIgIgMABQgNAAgJAIgArKA6QgMgIgGgMQgGgMgBgRIAAgQQABgWAEgPQAFgOANgJQANgKAZgFQAZgEAIgDIAAAOQgKAEgWAEQgVADgJAHQgLAIgDAKQgCAKAAAQQAFgKALgFQAJgFAMAAQANAAAMAGQALAHAGALQAHALgBANQAAANgGAMQgHALgLAHQgMAGgOAAQgPAAgLgGgArBgOQgJAEgEAIQgFAIAAAJQAAAJAFAJQAEAIAJAEQAHAGAKAAQAJAAAJgGQAHgEAFgIQAFgIAAgKQAAgJgFgIQgFgIgHgEQgJgFgJAAQgKAAgHAFgAG9A+IAAhhIBBAAIAAAPIgxAAIAABSgAEeA+IAAhhIAoAAQAOABAJAGQAIAIAAALQABAGgDAEQgDAFgFADQAJADAFAGQAFAGAAAJQAAANgKAHQgJAJgQAAgAEuAyIAcAAQAKAAAFgGQAGgEgBgHQABgIgGgEQgFgEgKAAIgcAAgAEuAFIAZAAQAHgBAEgDQAEgCAAgHQAAgNgPABIgZAAgABEA+IAAgtIgwAAIAAAtIgPAAIAAhhIAPAAIAAAoIAwAAIAAgoIAPAAIAABhgAg8A+IAAhSIghAAIAAgPIBRAAIAAAPIgiAAIAABSgAjlA+IAAhSIgkAAIAAALQgBAYgDAQQgDAQgHAHQgHAIgLAAIgFgBIAAgMIAEABQAJAAAFgPQAEgPAAgdIAAgaIBDAAIAABhgAlOA+IAAhSIguAAIAABSIgQAAIAAhhIBOAAIAABhg");
	this.shape.setTransform(75.95,16);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtS0201, new cjs.Rectangle(0,0,153.7,29.2), null);


(lib.txtS0101 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjfDLIAAgNIAMABQAIAAAFgDQAFgEAEgJIAFgMIgoheIARAAIAgBOIAghOIAQAAIgwBvQgFANgIAGQgIAGgMAAQgHAAgIgCgAAKCiQgKgHgHgMQgHgLAAgOQAAgOAHgMQAHgLALgIQALgGAOAAQAOAAAMAGQAMAIAGALQAHAMAAAOQAAAOgHALQgGAMgMAHQgMAGgOABQgOgBgMgGgAASBWQgIAEgEAJQgFAIAAALQAAAKAFAIQAEAJAIAFQAIAFAKAAQAKAAAIgFQAIgFAFgJQAEgIAAgKQAAgLgEgIQgFgJgIgEQgIgFgKAAQgKAAgIAFgAmVCiQgMgHgGgMQgHgLAAgOQAAgOAHgMQAGgLAMgIQAMgGAOAAQAOAAALAGQAMAIAHALQAHAMAAAOQAAAOgHALQgHAMgMAHQgLAGgOABQgOgBgMgGgAmNBWQgIAEgFAJQgEAIAAALQAAAKAEAIQAFAJAIAFQAIAFAKAAQAJAAAIgFQAJgFAEgJQAFgIAAgKQAAgLgFgIQgEgJgIgEQgIgFgKAAQgKAAgIAFgAtJCVQgNgTAAgfQAAgeANgSQAMgTAYAAQAYAAAMATQAMASAAAeQAAAfgMATQgMAUgYAAQgYAAgMgUgAs+A9QgHANAAAZQAAAaAHAPQAIAPARAAQAQAAAIgPQAIgPAAgaQAAgZgIgNQgHgPgRAAQgRAAgIAPgAu9CVQgNgTAAgfQAAgeANgSQAMgTAYAAQAYAAAMATQAMASAAAeQAAAfgMATQgMAUgYAAQgYAAgMgUgAuyA9QgHANAAAZQAAAaAHAPQAIAPARAAQAQAAAIgPQAIgPAAgaQAAgZgIgNQgHgPgRAAQgRAAgIAPgAycChQgKgHAAgMQAAgNAKgHQAJgIAQAAIAfAAIAAgIQAAgMgGgHQgHgGgLAAQgJAAgGAEQgHAEgGAIIgKgJQAGgKALgGQAKgFAMAAQARAAALAKQAKAKAAAUIAAA8IgOAAIAAgNQgGAHgIAEQgIADgLABQgPAAgJgIgAyRCCQgFADAAAIQAAAHAGAEQAFAEAJAAQAIAAAHgDQAHgEAEgGQAEgHAAgIIAAgCIgdAAQgKAAgGAEgAzsCkQgKgFgGgJIAKgJQAFAHAHADQAGAEAJAAQAKAAAGgFQAFgEAAgJQAAgGgFgFQgGgFgKABIgLAAIAAgNIALAAQAIAAAEgDQAFgFAAgGQAAgGgFgFQgEgDgJAAQgIAAgGADQgFADgFAGIgKgJQAFgIAJgFQAJgEAMAAQAPAAAIAHQAJAHAAAMQAAAIgDAFQgDAGgGADQAIADAFAHQAEAFAAAJQAAANgKAJQgKAHgRABQgMgBgJgEgACqCnIgtg1IApgtIATAAIgqAtIAuA1gABrCnIAAhiIAQAAIAABigAgxCnIAAhUIgvAAIAABUIgPAAIAAhiIBOAAIAABigAj2CnIgtg1IApgtIATAAIgpAtIAuA1gAk0CnIAAhiIAPAAIAABigAnSCnIAAhUIguAAIAABUIgQAAIAAhiIBOAAIAABigAqpCnIAAgdIgQAAIAAgMIAQAAIAAgSIgQAAIAAgNIAQAAIAAg8IAtAAQASgBALALQALAKAAAQQAAARgLAKQgLAKgSAAIgdAAIAAASIA1AAIAAAMIg1AAIAAAdgAqZBfIAcAAQAMAAAHgGQAHgHAAgLQAAgKgHgIQgHgGgMAAIgcAAgAv1CnIAAhyIgdAIIgEgNIArgNIAFAAIAACEgAPjgSIAAgMIAMABQAHAAAGgEQAFgDAEgJIAFgMIgphfIARAAIAgBPIAghPIARAAIgwBvQgGANgIAHQgIAFgLAAQgIAAgHgCgADvgSIAAgiQgQAAgMgHQgNgGgHgMQgHgKAAgQQAAgPAHgLQAHgMANgFQAMgHAQAAIAAgzIAQAAIAAAzQAQAAAMAHQANAFAHAMQAHALAAAQQAAAPgHALQgIALgMAGQgNAHgPAAIAAAigAD+hAQATgBAKgKQALgLAAgRQAAgRgLgKQgKgKgTgBgADTiCQgLAKAAASQAAARALAKQAKAKASABIAAhNQgSABgKAKgAgqgSIAAiGIAOAAIAAARQAGgJAKgFQAKgEAKAAQAOAAALAGQALAHAGAMQAGALAAAOQAAAOgGAMQgGAMgLAGQgLAHgOAAQgKAAgJgEQgKgFgGgHIAAAygAgKiHQgHAEgFAHQgFAJAAAMQAAANAFAIQAEAJAIADQAIAFAIAAQAKgBAHgFQAIgEAFgIQAEgJAAgKQAAgLgEgJQgFgIgIgFQgHgFgKAAQgIABgIAEgAyogaIAAgcIhNAAIAAAcIgPAAIAAgoIALAAQAHgIACgOQADgNABgXIAAgcIBDAAIAABWIAQAAIAAAogAzeh8QAAAVgDAPQgDAOgFAIIAxAAIAAhHIglAAgARlg7QgMgGgHgMQgHgMAAgOQAAgOAHgLQAHgMAMgHQALgGAOAAQANAAAKAFQALAFAGAKIgLAJQgLgQgSAAQgKABgIAEQgIAFgEAIQgFAJAAAKQAAAKAFAJQAEAJAIAEQAIAFAKABQASAAALgQIALAIQgGAKgLAGQgKAFgNAAQgOAAgLgHgAMjg7QgMgGgGgMQgHgMAAgNQAAgOAHgMQAGgMAMgHQAMgGAOAAQAOAAALAGQAMAHAHAMQAHAMAAAOQAAANgHAMQgHAMgMAGQgLAHgOAAQgOAAgMgHgAMriHQgIAFgFAIQgEAJAAALQAAAKAEAIQAFAJAIAEQAIAFAKABQAJgBAIgFQAJgEAEgJQAFgIAAgKQAAgLgFgJQgEgIgIgFQgIgFgKAAQgKAAgIAFgAHAg7QgLgGgHgMQgHgMAAgNQAAgOAHgMQAHgMAMgHQALgGAOAAQAOAAAMAGQAMAHAGAMQAHAMAAAOQAAANgHAMQgGAMgMAGQgMAHgOAAQgOAAgMgHgAHIiHQgIAFgEAIQgFAJAAALQAAAKAFAIQAEAJAIAEQAIAFAKABQAKgBAIgFQAIgEAFgJQAEgIAAgKQAAgLgEgJQgFgIgIgFQgIgFgKAAQgKAAgIAFgABeg7QgLgGgHgMQgHgMAAgNQAAgOAHgMQAHgMAMgHQALgGAOAAQAOAAAMAGQAMAHAGAMQAHAMAAAOQAAANgHAMQgGAMgMAGQgMAHgOAAQgOAAgMgHgABmiHQgIAFgEAIQgFAJAAALQAAAKAFAIQAEAJAIAEQAIAFAKABQAKgBAIgFQAIgEAFgJQAEgIAAgKQAAgLgEgJQgFgIgIgFQgIgFgKAAQgKAAgIAFgAiIg5QgKgGgHgKIALgIQAMAQARAAQAOgBAJgIQAKgJACgOIgqAAIAAgNIApAAQgCgNgKgIQgJgJgNAAQgSAAgLAQIgLgJQAHgKAKgFQAKgFANAAQAOAAAMAGQALAHAHAMQAHALAAAOQAAAOgHAMQgHAMgLAGQgMAHgOAAQgNAAgKgFgArMg0IAAhkIAPAAIAABGIA8hHIAFAAIAABjIgPAAIAAhFIg8BHgAvdg8QgMgHgHgNIALgHQAHAJAIAGQAIAGALABQAOAAAIgJQAJgIAAgOQAAgNgJgIQgJgHgQAAIgNAAIAAgEIAjgsIg3AAIAAgOIBQAAIAAAFIgjAtQAKABAIAEQAJAGAGAIQAFAJAAAMQAAANgGALQgHAKgLAFQgKAFgNAAQgPAAgLgIgAx2g7QgLgGgHgMQgHgMAAgNQAAgOAHgMQAHgMAMgHQALgGAOAAQAOAAAMAGQAMAHAGAMQAHAMAAAOQAAANgHAMQgGAMgMAGQgMAHgOAAQgOAAgMgHgAxuiHQgIAFgEAIQgFAJAAALQAAAKAFAIQAEAJAIAEQAIAFAKABQAKgBAIgFQAIgEAFgJQAEgIAAgKQAAgLgEgJQgFgIgIgFQgIgFgKAAQgKAAgIAFgAPDg2IAAgtIgwAAIAAAtIgPAAIAAhiIAPAAIAAApIAwAAIAAgpIAPAAIAABigAKlg2IAAiEIBPAAIAAAOIg/AAIAAAoIAdAAQANAAAKAFQAKAFAGAJQAFAJAAALQAAALgFAJQgGAJgKAFQgKAFgNAAgAK1hEIAdAAQANAAAIgHQAHgHAAgLQAAgLgHgHQgIgHgNAAIgdAAgAI1g2IAAhTIghAAIAAgPIBRAAIAAAPIghAAIAABTgAGEg2IAAhTIgkAAIgBALQAAAagDAPQgDAQgHAHQgHAIgLAAIgFgBIAAgMIAEABQAJAAAEgPQAEgPABgeIAAgaIBCAAIAABigAiyg2IgLgbIhBAAIgLAbIgRAAIA6iGIAFAAIA6CGgAj4hfIA1AAIgbhBgAn9g2IAAhiIAQAAIAAAiIAXAAQAQAAAKAJQAKAJAAAOQAAAPgKAIQgKAJgQAAgAnthCIAWAAQAKAAAGgGQAFgFAAgJQAAgIgFgGQgGgFgKAAIgWAAgAong2IAAhTIgkAAIgBALQAAAagDAPQgDAQgHAHQgHAIgLAAIgFgBIAAgMIAEABQAJAAAEgPQAEgPABgeIAAgaIBCAAIAABigAr2g2IAAhCIgiAoIgGAAIghgoIAABCIgPAAIAAhjIAFAAIAvA2IAug2IAFAAIAABjgATYhNIAcgfIgcggIAKgIIAjAmIAAAEIgjAmgASwhNIAcgfIgcggIAKgIIAkAmIAAAEIgkAmgAlPhqIAAgEIAkgmIAKAIIgcAgIAcAfIgKAJgAl2hqIAAgEIAjgmIAKAIIgcAgIAcAfIgKAJg");
	this.shape.setTransform(130.525,27.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtS0101, new cjs.Rectangle(0,0,261.5,51.3), null);


(lib.txtM0203 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGQBlQgbgPgQgbQgPgbAAggQAAgfAPgbQAQgbAbgPQAcgQAhAAQAhAAAbAQQAbAPAQAbQARAbgBAfQABAggRAbQgQAbgbAPQgcAQggAAQgiAAgbgQgAGjgrQgQARAAAbQAAAaAQASQAQARAaAAQAZAAAQgRQAQgSAAgaQAAgagQgSQgQgSgZAAQgaAAgQASgAhpB1IAAjkIA9AAIAAB5IB7h9IAUAAIAADiIg9AAIAAh3Ih7B9gAlPBKIAigkQAXAYAkAAQARAAAKgGQAIgGABgKQgBgJgHgGQgJgFgPgBIgcAAIAAgoIAaAAQALABAHgGQAGgFAAgKQAAgJgGgFQgIgGgOAAQgfAAgVAYIgignQAPgTAXgLQAYgKAdAAQAnAAAVASQAWARAAAgQAAAdgWATQAQAHAHANQAJANgBAPQABAigYASQgXASgtAAQg/AAghgrgApCB1IAAjkIA9AAIAAB5IB9h9IATAAIAADiIg9AAIAAh3Ih8B9gAJtBvIAAjeIBnAAQAjAAAVARQAXASAAAdQAAAYgSARQAQAGAKANQAIANABASQAAAUgLAPQgKAPgTAJQgSAIgWAAgAKmBHIA3AAQAOgBAJgGQAHgIAAgMQAAgNgHgGQgJgHgOAAIg3AAgAKmgWIArAAQAbAAAAgXQAAgNgHgFQgGgHgOAAIgrAAgADEBvIAAimIhDAAIAAg4IDFAAIAAA4IhFAAIAACmgAsyBvIAAjeIBnAAQAiAAAWARQAWASABAdQgBAYgRARQAPAGAKANQAJANAAASQAAAUgLAPQgKAPgSAJQgTAIgWAAgAr5BHIA2AAQAPgBAIgGQAIgIAAgMQAAgNgIgGQgIgHgPAAIg2AAgAr5gWIArAAQAbAAAAgXQgBgNgGgFQgHgHgNAAIgrAAg");
	this.shape.setTransform(85.95,80.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtM0203, new cjs.Rectangle(-1,0,172.3,105.1), null);


(lib.txtM0202 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIeDRIAAkvIA4AAIAAAcQALgPATgJQASgJAYAAQAeAAAZAPQAYAPAOAbQAOAaABAgQgBAigOAaQgOAbgYAPQgZAQgeAAQgUAAgSgHQgRgHgMgNIAABmgAJqgdQgQAQAAAeQAAAeAQAQQARAQAYAAQAXAAARgRQARgRAAgcQAAgbgRgRQgQgRgYAAQgYAAgRAPgABEDRIAAhLQglgCgcgPQgcgOgQgZQgRgaAAgjQAAgjARgaQAQgaAcgNQAcgOAlgCIAAhtIA8AAIAABtQAkACAdAOQAdAPAQAZQAQAaAAAiQAAAkgQAaQgQAZgdAOQgdAOgkACIAABLgAB/BPQAfgCASgQQASgQAAgdQAAgbgTgQQgRgQgfgBgAAUgbQgTAQABAcQgBAcATAQQASAQAfACIAAh7QggACgRAPgAwgDRIAAkvIA4AAIAAAcQALgPATgJQATgJAWAAQAgAAAYAPQAZAPAOAbQAOAagBAgQABAigOAaQgOAbgZAPQgYAQggAAQgTAAgSgHQgRgHgMgNIAABmgAvTgdQgRAQAAAeQAAAeARAQQAQAQAXAAQAZAAAQgRQARgRAAgcQAAgbgQgRQgRgRgZAAQgXAAgQAPgANfB2QgbgPgPgbQgRgbABggQgBgfARgbQAPgbAbgQQAcgPAhAAQAgAAAcAQQAbAPARAbQAPAbAAAfQAAAggPAbQgRAbgbAPQgcAQghAAQggAAgcgQgANzgbQgRASAAAaQAAAbARARQAQASAZAAQAYAAARgSQAQgRABgbQgBgZgQgSQgRgSgYAAQgZAAgQARgAFVB2QgcgPgPgbQgRgbABggQAAggAPgaQAPgbAbgQQAbgPAgAAQAfAAAYAOQAYANANAYQANAYAAAcQAAAQgEARIicAAQAFAUAQALQARALAZAAQAgAAAdgVIAZAqQgnAigyAAQgiAAgcgQgAFqghQgPALgEATIBlAAQgBgTgOgLQgOgLgTAAQgTAAgPALgAjvB2QgcgPgQgbQgPgbgBghQABgfAPgbQAQgaAcgQQAbgPAhAAQAgAAAaAPQAYAOAOAaIgqAhQgKgQgNgIQgMgJgSAAQgaAAgQARQgRASAAAaQAAAbARARQAQASAaAAQARAAANgJQAMgIALgQIAqAhQgOAZgZAPQgZAPggAAQghAAgbgQgAsGBzQgVgTAAgdQAAgeAXgSQAXgRAmAAIA4AAIAAgJQAAgRgLgKQgKgKgVAAQgQAAgOAHQgNAHgPAPIgggmQAnguA7AAQArAAAaAZQAaAYAAAvIAACDIg4AAIAAgVQgMAMgRAHQgRAIgWAAQgkAAgUgTgArVAwQgJAGABANQAAAMAIAHQAJAHAOAAQAUAAANgOQAOgNAAgVIAAgDIgwAAQgPAAgHAGgAQ8CAIAAjeIBnAAQAjAAAWARQAWASAAAdQAAAYgSAQQAQAHAJANQAKANgBASQAAATgKAQQgKAPgSAJQgTAIgXAAgAR1BXIA2AAQAPAAAJgHQAHgHABgMQgBgNgHgHQgJgGgPAAIg2AAgAR1gFIArAAQAbAAAAgYQAAgMgHgGQgHgGgNAAIgrAAgAmQCAIAAhZIhSAAIAABZIg9AAIAAjeIA9AAIAABPIBSAAIAAhPIA9AAIAADegAy9CAIAAinIhFAAIAAg3IDGAAIAAA3IhFAAIAACng");
	this.shape.setTransform(132.25,78.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtM0202, new cjs.Rectangle(1.4,0,262.5,105.1), null);


(lib.txtM0201 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlOC3IAAhAIiZAAIAABAIg5AAIAAh3IAXAAQAOgMAGgbQAGgaACgvIABg2ICzAAIAACmIAlAAIAAB3gAm2gjQgBBAgUAjIBWAAIAAhvIhBAAgAFrBpQgbgWgNgjQgMgjAAgrQAAhFAdgpQAegqA6AAQA5AAAeAqQAfApAABFQgBArgNAjQgNAjgaAWQgbAUgmAAQgnAAgagUgAGChmQgNAYAAAwQAABkA3AAQA3AAAAhkQAAgwgNgYQgOgZgcAAQgcAAgOAZgAjCBtQgbgPgPgbQgQgbgBggQABgfAQgbQAPgbAcgPQAbgQAhAAQAgAAAcAQQAcAPAQAbQAQAbAAAfQAAAggQAbQgQAbgcAPQgcAQghAAQggAAgcgQgAiugkQgRASAAAaQAAAbARASQAQARAZAAQAZAAAQgRQARgSAAgbQAAgZgRgSQgQgSgZAAQgZAAgQARgAC/B3IAAjfIg4ATIgOg3IBvglIAUAAIAAEog");
	this.shape.setTransform(58.55,34.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtM0201, new cjs.Rectangle(0,0,115.4,60.6), null);


(lib.txtM0102 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKtBlQgbgPgQgbQgPgbAAggQAAgfAPgbQAQgbAbgPQAcgQAhAAQAhAAAbAQQAbAPAQAbQARAbgBAfQABAggRAbQgQAbgbAPQgcAQggAAQgiAAgbgQgALAgrQgQARAAAbQAAAaAQASQARARAZAAQAZAAAQgRQAQgSAAgaQAAgagQgSQgQgSgZAAQgZAAgRASgAhZBjQgVgUABgdQgBgeAXgSQAWgQAnAAIA3AAIAAgKQAAgRgLgKQgKgKgTAAQgSAAgNAHQgNAIgPAOIgfgmQAmguA6AAQArAAAaAZQAaAZAAAuIAACDIg4AAIAAgVQgMAMgRAHQgRAIgVAAQgkAAgUgSgAgpAfQgHAHAAAMQgBAMAJAHQAJAHAOAAQATAAAOgNQANgOAAgVIAAgDIgvAAQgOAAgJAGgAlyBxIAAg0IAIABQANAAAHgMQAHgMAEgbQADgYABgtIABg1ICwAAIAADeIg8AAIAAimIg8AAIAAAQQgCA4gHAiQgIAhgRAQQgQARgcAAQgMAAgKgEgAt7BjQgUgUAAgdQAAgeAWgSQAXgQAnAAIA3AAIAAgKQAAgRgKgKQgKgKgVAAQgRAAgOAHQgNAIgPAOIgfgmQAnguA6AAQArAAAaAZQAbAZgBAuIAACDIg3AAIAAgVQgNAMgRAHQgRAIgWAAQgjAAgVgSgAtKAfQgIAHAAAMQAAAMAIAHQAJAHAPAAQATAAAOgNQANgOAAgVIAAgDIgvAAQgPAAgIAGgARGBvIAAhrIg2A9IgUAAIg2g8IAABqIg8AAIAAjiIAUAAIBpB0IBoh0IAUAAIAADigAINBvIAAhZIhSAAIAABZIg8AAIAAjeIA8AAIAABPIBSAAIAAhPIA8AAIAADegACOBvIAAjeIBnAAQAiAAAWARQAXASgBAdQAAAYgSARQARAGAJANQAJANAAASQAAAUgKAPQgLAPgSAJQgSAIgXAAgADHBHIA2AAQAPgBAIgGQAIgIAAgMQAAgNgIgGQgIgHgPAAIg2AAgADHgWIArAAQAbAAAAgXQAAgNgIgFQgGgHgNAAIgrAAgAodBvIAAjeICkAAIAAA4IhnAAIAACmgAvzBvIAAhZIhTAAIAABZIg8AAIAAjeIA8AAIAABPIBTAAIAAhPIA8AAIAADeg");
	this.shape.setTransform(119.5,80.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtM0102, new cjs.Rectangle(0,0,240.7,105.1), null);


(lib.txtM0101 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADOC/IAAgzIAaABQAQAAAMgGQALgGAHgSIAHgPIhVjQIBAAAIA2CRIA6iRIBAAAIhqDxQgQAjgVAQQgVAQgfAAQgTAAgUgFgAoRB3IAAgkQgqgCgggPQgfgPgSgcQgSgaAAglQAAg4AmggQAnggBAgCIAAghIA9AAIAAAhQAqABAgAPQAgAPASAbQATAcAAAlQAAAlgTAaQgSAcggAOQggAPgqACIAAAkgAnUAcQAngBAWgSQAWgRAAggQAAgggWgRQgWgRgngBgApNhYQgWASAAAgQAAAfAWAQQAWARAmACIAAiHQgmABgWASgAICBkQgbgQgQgbQgQgbAAgfQAAghAQgaQAQgbAbgPQAcgQAhAAQAgAAAZAPQAZAPAOAZIgqAhQgKgPgNgJQgNgJgRAAQgaAAgRASQgQASAAAaQAAAaAQASQARARAaAAQARAAAMgIQANgJALgPIAqAgQgOAagZAPQgZAOggAAQghAAgcgPgAjxBkQgbgQgQgbQgQgbAAgfQAAggAQgbQAQgbAbgPQAcgQAhAAQAgAAAcAQQAbAQAQAaQAQAbAAAgQAAAfgQAbQgQAbgbAQQgcAPghAAQghAAgbgPgAjegtQgQASAAAbQAAAZAQASQAQARAaAAQAYAAARgRQAQgSAAgZQAAgbgQgSQgRgSgYAAQgaAAgQASgAB/BuIhYh1IAAB1Ig7AAIAAjeIA7AAIAABoIBUhoIBFAAIhUBmIBbB4g");
	this.shape.setTransform(71.125,35.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txtM0101, new cjs.Rectangle(0,0,152.6,60.6), null);


(lib.LOGO_visa = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMB2IAMg4QAPAIALAEQATAFAVgBQAQAAALgGQANgGAAgNQAAgIgIgGQgHgIgTgJQg7gdABgoQAAglAfgXQAfgYAxABQAfgBAfALIgMA2QgggOghADQgNACgIAHQgGAFgBAHQAAAKAPAJQAIAGAYAMQAuAaAAAlQAAAoggAYQgfAYg0gBQgtAAgbgNgAFbCAIgIgnIhVAAIgNAnIhGAAIBjjsQAEgIAHgFQAIgFAJAAIA5AAIA1D+gAFIAmIgUhfIgjBfIA3AAgAh8CAIA3j+IBCAAIg3D+gAkSCAIg0jLQgDgJgDgEQgDgFgHgEQgXgMgqgKIACgHIBwAAQALAAAIAHQAJAHACAMIAcCTIBEitIBGAAIhrD+g");
	this.shape.setTransform(-0.225,0.15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGO_visa, new cjs.Rectangle(-41,-13.1,81.8,26.4), null);


(lib.LOGO_gpb = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A2eD3QhYgFg6g2QgMgLgFgUQgagNgNgVQgHgJADgRIADgHQgTgOgDgGQgJgQALgUQgIgKgDgGQgCgHAAgMQACgRAPgPQAageBDgWQAdgJAZgGIAugKQAMgDA2gJQAqgHAYgIQhZgPhTAPQhYAQhHAwIAHgSQBIgvBIgPQBYgTBxAUQAOgJACgMQg5gUhUABQgqABg3AOQg9AOgjAUIAQgSQAbgRA4gOQA8gQAwgBQAkgBAZAEQAaADApALQgEgHgIgFIgWgKQgrgThCABQhHACg7AaQAUgNAOgGQA3gZBKABQAkABAiALQAlANAYAXQAIAJACAKQAlASAMAVQAGAMgCANQAMAGAJAMQAGAJACAKQACARgJAKQAGADAFAIQAFAGABAFQAGAagfAaQgPAMgcANQgbANgaAHQgqAKg1AJIhQANQAzAMAvAAQA/AABHgXQAigMAXgMIgEALQgsAbhGAPQg6ANgngCQg/gDg4gQQgSAFgPAGQAnARAmAIQAcAGApADQAmACA1gIQA4gJAygRQgEAHgEADQgZANguAMQguAMgcABQhFADg0gKQgngIgygWQgHAGgCAJQBSAqBTAEQBPAFBbgdIgLAKQhaAlhVgGQhGgEhEggIgIgEQAIAOAmAUQAtAYAuAEQAiADAngFQAmgFAagLIgUAKQgvAXg3AAIgTgBgA5BCDQADgGAEgFIgVgLQAAAKAOAMgA5EBZIAcAQIAWgLIgkgPQgHADgHAHgAy/gbQgaAUg/AQQgvAMhEALQhIAMgeAIQgPADgbAKQAUAKAWAIQAngLAsgIQAwgHA0gLQA+gNAlgSQAxgXgQgZgA5cBIIAJgIIgTgLQgFAKAPAJgAzqhEQgaAMgwAMIhFANQg+ALgoAJQhVARggAbQAFAFASAJQAXgOAigIQAogLBPgNQBjgPA8gVQAXgJANgJQgDgDgNgGIgPgGIgBAAgA1thcQhUAKhNAWQgsAOgVALQguAYASAZQAFgGAMgIQAbgQAqgMQArgNBTgPQBagQApgLQgcgHgQgCIgTgBQgMAAgOABgAzRhTIAXAMQADgHgBgGQgCgFgJgHIgOANgA0uhwIAeAHIAcAJQACABAJgHIAKgKQgXgKgagHQgNALgRAGgAz+iRQAPAEAWAJQgCgOgXgPQgCAHgKAJgAQ/BkIAAgOIAMABQAQAAAIgRIAFgMIgrhkIASAAIAiBSIAihSIARAAIgzB2QgLAagXAAQgIAAgIgCgAYbBkIAAiPIAbAAIAAANQAKgQAXAAQAXAAAOAQQAOAQAAAWQAAAYgOAQQgOAQgXAAQgUAAgLgNIAAAxgAZAgNQgJAIAAANQAAAOAJAJQAHAHALAAQAMAAAHgIQAIgIAAgNQAAgMgIgJQgHgIgMAAQgLAAgHAHgAI9BkIAAiOIAPAAIAAARQAOgTAaAAQAWAAAPAQQAOAPAAAWQAAAXgOAQQgQAQgVAAQgZAAgOgSIAAA2gAJZgUQgMALAAASQAAAUAMAKQAJAJAPAAQAQAAAKgLQALgLAAgRQAAgQgLgLQgKgLgQAAQgPAAgJAJgApBBkIAAiPIAaAAIAAANQALgQAXAAQAXAAAOAQQAOAQAAAWQAAAYgOAQQgOAQgXAAQgUAAgLgNIAAAxgAocgNQgJAIAAANQAAAOAJAJQAHAHALAAQALAAAIgIQAIgIAAgNQAAgMgIgJQgIgIgLAAQgLAAgHAHgAWYAwQgRgRAAgcIAAhRIAdAAIAABTQAAAQAJAIQAJAIANAAQANAAAJgIQAJgIAAgQIAAhTIAdAAIAABRQAAAcgRARQgRAQgaAAQgbAAgQgQgAPPBAIAAhqIARAAIAABJIA/hLIAHAAIAABpIgRAAIAAhIIhABLgALMAwQgQgQAAgXQAAgVAQgQQAPgQAWAAQAVAAANANQAOANAAAUIgBAMIhTAAQACAQAKAJQALAJAQAAQARAAAOgOIAKAMQgRASgZAAQgXAAgQgQgALagVQgJAIgDANIBBAAQABgNgKgIQgJgIgMAAQgNAAgKAIgAFKA6QgGgFAAgJQAAgIAGgGQAFgGAJAAQAIAAAHAGQAFAGAAAIQAAAJgFAFQgHAGgIAAQgJAAgFgGgAgfA3QgKgJAAgOQAAgOAMgIQAKgIATAAIAZAAIAAgEQAAgTgUAAQgNAAgOAPIgPgSQATgWAbAAQAUAAAMAMQANAMAAAWIAAA9IgbAAIAAgKQgNANgSAAQgRAAgKgJgAgLAfQAAAMANAAQAJAAAHgGQAGgGABgJIAAgBIgXAAQgNAAAAAKgAiZAvQgQgSAAgcIAAgPQAAglAOgRQAQgVApgFQAbgDAFgDIAAAaQgIADgYADQgaADgLAKQgIAKAAAVQAOgSAXAAQAVAAAOAQQAPAPAAAVQAAAYgQAPQgQAPgZAAQgZAAgPgRgAiEgIQgIAIAAAKQAAAMAIAHQAIAIALAAQAMAAAIgIQAHgHAAgMQAAgKgHgIQgIgIgMAAQgLAAgIAIgAmwAwQgRgQAAgYQAAgWARgQQAQgQAXAAQAYAAARAQQAQAQAAAWQAAAYgQAQQgRAQgYAAQgXAAgQgQgAmcgLQgIAIAAAMQAAAMAIAIQAHAIAMAAQAMAAAIgIQAIgIAAgMQAAgMgIgIQgIgIgMAAQgMAAgHAIgAsuAsIAQgRQALAMARAAQARAAAAgLQAAgKgPAAIgOAAIAAgVIAMAAQAMAAABgJQgBgJgNAAQgPAAgJALIgRgRQAPgTAcAAQATAAAKAIQALAIAAAPQAAANgLAIQAPAJAAAPQAAAigrAAQgeAAgQgUgAuYA3QgJgJAAgOQAAgOALgIQAKgIASAAIAbAAIAAgEQAAgTgUAAQgOAAgOAPIgPgSQASgWAcAAQAVAAAMAMQAMAMAAAWIAAA9IgaAAIAAgKQgMANgUAAQgRAAgKgJgAuEAfQgBAMAQAAQAJAAAGgGQAHgGAAgJIAAgBIgXAAQgOAAAAAKgAUaA9IAAhFIgkApIgFAAIgkgpIAABFIgQAAIAAhpIAFAAIAyA6IAwg6IAGAAIAABpgAObA9IAAhFIgjApIgHAAIgjgpIAABFIgRAAIAAhpIAHAAIAwA6IAyg6IAFAAIAABpgAIHA9IAAh9IhNAAIAAB9IgRAAIAAiLIBvAAIAACLgAEXA9Igrg4IAAA4IgcAAIAAhoIAcAAIAAAwIApgwIAgAAIgoAvIAsA5gACWA9IAAgqIgoAAIAAAqIgcAAIAAhoIAcAAIAAAmIAoAAIAAgmIAcAAIAABogAjgA9IAAgyIgZAcIgKAAIgZgcIAAAyIgdAAIAAhrIAJAAIAyA3IAyg3IAJAAIAABrgAp7A9IAAhQIgmAAIAABQIgdAAIAAhoIBgAAIAABogAwJA9IAAiLIBaAAIAAAaIg9AAIAABxg");
	this.shape.setTransform(167.45,24.8072);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGO_gpb, new cjs.Rectangle(0,0,334.9,49.6), null);


(lib.LOGO_aeroflit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIyCyIAngqQBBhLAyglQBchFBpgQIACAAQAigsAVgNQAQgMAkgDIATgCQAngFATgGQAhgLAYgYIACABIgoA2IABABIgGAHIgrBAIgCABIgXAhIgZAVIgRANIgBACQglAVgqACIgYACIgDAAIgcAlQgFAMgOAAIgLAAQhQgBgrAMQhEAThSA+gALzBVQhKANhDAtQA5gkA2gMQAsgLBIABQAOABAEgFIgngBQgkAAgdAFgAJ8B7IgLAJQBBgoBHgMQAqgGA6AEIABgCIgCgEIgegBQhpAAhZA0gALqAmQhAAig9A4QBDgtAogSQAwgVA/gGIAMgPIABgCIATgXQg7AGhCAigAL/BFQgxAIgyAYIgHAGQBbgtBoAHIgIgGIgIAAQgqAAgfAGgAMLA9QgvAHgdANIgLAGQBCgbBSABIgBgBQgHgCAAgEQgUAAghAHgANEAyQgBADAAACIAFACIAOAGQAJAFACAEIAAACIABABQAHgMAPgRIAEgFIgEAAQgrACgJAHgAM2AsQgxAGgqASQAdgJAggEQAcgFANABIABgFIAAAAIACgCIAAgBIAAAAgAOHAhIguADIgIACIgJAGIAHgCIABAAIAMgDIAigCIAdgBQAaAAAYgKQgWAGgwABgAOZAXQg6ABgQAMIgCABIADgCQANgEAqgCQBEgBAdgQQgbAJg0ACgAOeAMQghADgMACQgVAEgKAIQARgIA1gCQAigBATgCQAcgFARgLIAFgDQgbANhGACgAPcgBQgSACgkACQg/ADgNAOQAQgIA0gCQAqgCAUgFQAhgFAQgQQgSALgfAGgAPkgMQgRADgkACQgiACgNACQgWADgIAKQAQgHA0gDQAogBAUgFQAggGARgPQgRALgeAEgAODgMQgHABgJAEIgIAGIAAABQARgHAzgDQAogCARgEQAfgGARgOIACgCIgMAGQgSAIgXADIAAABIgMACQgPABgmABIgBAAgAQRhMIhQAFQgeAEgNAKIgHAGIgeApQANgGAUgCIARAAQAogCAOgCQAzgHAXgTIAGgGIADgEIAdgrQgVAUgjAFgAD1BHQgfgWAAgeQAAgeAfgTQAjgYA6AAQA4AAAkAYQAeATAAAeQAAAegeAWQgjAXg5AAQg6AAgjgXgAElgSQgNAOAAAXQAAAYANAQQAPASAeAAQAdAAAPgSQAMgQAAgYQAAgXgMgOQgQgUgcABQgegBgPAUgAiJBeIAAgVIgYAAQgmgBgWgOQgZgNAAgbQAAgXAZgQQAUgMAogDIAYAAIAAgTIA8AAIAAATIAXAAQApADASAMQAZAPABAYQgBAbgZANQgUAOgnABIgXAAIAAAVgAhPA3IAGAAQAHAAAMgCQAMgFACgCQAMgJAAgTQAAgSgMgJQgFgEgJgCQgHgDgMAAIgGAAgAihgPQgJACgEAEQgMAJAAASQAAATAMAJQACACALAFQALACAJAAIAGAAIAAhJIgGAAQgMAAgIADgAnaBHQgfgWAAgeQAAgeAfgTQAjgYA5AAQA6AAAiAYQAeATABAeQgBAfgeAVQghAXg7AAQg5AAgjgXgAmrgSQgMAOAAAXQAAAYAMAQQAQASAdAAQAeAAAPgSQAMgPAAgZQAAgYgMgNQgQgUgdABQgdgBgQAUgAuOBRQgWgLgOgOIAegPIAEAFQAJAMAPAIQAQAJAYAAQAgAAAPgMQATgOABgWIhcABIAAgVIBcABQgDgQgMgLQgRgQgigBQgWAAgPAIQgRAGgIAJIgHAGIgegOQATgRAYgHQAbgKAiABQA9AAAjAYQAeATABAeQgBAegeAWQgjAXg9AAQgpAAgbgNgAICBaIAAh3Ig/AAIAAgWIC6AAIAAAWIhAAAIAAB3gACmBaIhAhsIgCAAIg6BsIgdAAIBOiNIA4AAIBVCNgAq6BaIAAiNIBlAAQAuAAATALQAWAMAAAVQAAAXgWALQgTALgrAAIgtAAIAAA0gAp/ARIAiAAQAOgBAJgGQAKgFABgMQgBgKgKgHQgJgEgOAAIgigBgAvlBaIgZgoIhSAAIgYAoIgdAAIBSiNIA2AAIBaCNgAwLAeIgdgwIgBAAIgBAAIgbAwIA6AAg");
	this.shape.setTransform(0.8,0.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGO_aeroflit, new cjs.Rectangle(-115.8,-18.2,232.39999999999998,36.7), null);


(lib.legal_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal_1, new cjs.Rectangle(0,0,260,377), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Ag1A2IAAhrIBrAAIAABrg");
	mask.setTransform(5.4,5.425);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,0,0,4).p("AAzgyIhlBl");
	this.shape.setTransform(5.4,5.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFFFFF").ss(1,0,0,4).p("AgygyIBlBl");
	this.shape_1.setTransform(5.4,5.4);

	var maskedShapeInstanceList = [this.shape,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,10.8,10.9), null);


(lib.elipse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#562737").ss(2,1,1).p("EAhzAAAQAAOAp5J6Qp6J5uAAAQt/AAp6p5Qp5p6AAuAQAAt/J5p6QJ6p5N/AAQOAAAJ6J5QJ5J6AAN/g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.elipse, new cjs.Rectangle(-217.3,-217.3,434.6,434.6), null);


(lib.BUTT = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxBdIAAiFIAOAAIAAAQQAGgIAKgFQAKgEAKgBQAOABALAGQALAHAGAMQAGALAAANQAAAOgGAMQgGAMgLAHQgLAGgOAAQgKAAgJgEQgKgEgGgIIAAAygAgRgYQgHAEgFAIQgFAJAAALQAAAMAFAJQAEAIAIAEQAIAFAJAAQAJAAAHgGQAIgEAFgIQAEgJAAgKQAAgKgEgIQgFgJgIgFQgHgFgJABQgJAAgIADgAj5BdIAAgiQgQgBgMgFQgNgHgHgLQgHgMAAgPQAAgOAHgLQAHgMANgFQAMgHAQgBIAAgyIAQAAIAAAyQAQABAMAHQANAFAHAMQAHAMAAAOQAAAOgHAMQgIALgMAHQgNAFgPABIAAAigAjqAuQATAAAKgKQALgKAAgSQAAgQgLgKQgKgKgTgBgAkVgSQgLAKAAARQAAARALAKQAKAKASAAIAAhLQgSABgKAKgADBA7IAAhjIAQAAIAABEIA7hGIAGAAIAABjIgQAAIAAhEIg7BGgAiPA1QgMgIgGgLQgHgMAAgNQAAgNAHgMQAGgMAMgHQAMgGAOgBQAOABALAGQAMAHAHAMQAHAMAAANQAAANgHAMQgHALgMAIQgLAGgOAAQgOAAgMgGgAiHgXQgIAFgFAJQgEAIAAAKQAAAKAEAIQAFAJAIAEQAIAGAKAAQAJAAAIgGQAJgEAEgJQAFgIAAgKQAAgKgFgIQgEgJgIgFQgIgFgKABQgKgBgIAFgAmgAyQgQgIgJgQQgJgQAAgSQAAgTAJgQQAJgPAQgKQAPgIATgBQATABAQAIQAPAKAKAPQAJAQAAATQAAASgJAQQgKAQgPAIQgQAJgTAAQgTAAgPgJgAmYg3QgMAHgHAMQgHAMAAAQQAAAOAHANQAHAMAMAHQAMAHAOABQAPgBAMgHQAMgHAHgMQAHgNAAgOQAAgPgHgMQgHgNgMgHQgMgIgPABQgOgBgMAIgAF4A5IAAhhIAQAAIAAAiIAXAAQAQAAAKAIQAKAIAAAPQAAAOgKAJQgKAJgQAAgAGIAtIAWAAQAKgBAGgFQAFgFAAgIQAAgKgFgFQgGgFgKAAIgWAAgAE9A5IAAhSIghAAIAAgPIBRAAIAAAPIghAAIAABSgACaA5IAAhBIghAnIgGAAIghgnIAABBIgQAAIAAhjIAGAAIAuA2IAug2IAFAAIAABjg");
	this.shape.setTransform(0.125,0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#562737").s().p("AziDfQgyAAAAgyIAAlZQAAgyAyAAMAnFAAAQAyAAAAAyIAAFZQAAAygyAAg");
	this.shape_1.setTransform(0.075,0.275);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-130,-22,260.2,44.6);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.bndrchk_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#000000","rgba(0,0,0,0)"],[0,1],-17.5,-12.2,-17.5,-92.1).s().p("EgmpAZYMAAAgyvMBNTAAAMAAAAyvg");
	this.shape.setTransform(2.375,229.375);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.instance = new lib.bndrchk();
	this.instance.parent = this;
	this.instance.setTransform(-241,-241);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bndrchk_1, new cjs.Rectangle(-245,-241,494.8,632.8), null);


(lib.BG_BLCK = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#090C0E").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.BG_BLCK, new cjs.Rectangle(0,0,300,600), null);


(lib.TXT01 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txtS02 copy
	this.instance = new lib.txtS0301();
	this.instance.parent = this;
	this.instance.setTransform(0.25,130.7,1,1,0,0,0,130.7,25.7);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(215).to({_off:false},0).wait(1).to({regX:124.6,regY:27.1,x:-5.7,y:132.1,alpha:0.001},0).wait(1).to({x:-5.3,alpha:0.0043},0).wait(1).to({x:-4.55,alpha:0.01},0).wait(1).to({x:-3.45,alpha:0.0184},0).wait(1).to({x:-1.95,alpha:0.03},0).wait(1).to({x:0,alpha:0.0452},0).wait(1).to({x:2.45,alpha:0.0644},0).wait(1).to({x:5.5,alpha:0.0883},0).wait(1).to({x:9.3,alpha:0.1176},0).wait(1).to({x:13.85,alpha:0.1532},0).wait(1).to({x:19.35,alpha:0.1959},0).wait(1).to({x:25.9,alpha:0.2468},0).wait(1).to({x:33.55,alpha:0.3064},0).wait(1).to({x:42.3,alpha:0.3748},0).wait(1).to({x:52.05,alpha:0.4505},0).wait(1).to({x:62.25,alpha:0.5301},0).wait(1).to({x:72.4,alpha:0.6089},0).wait(1).to({x:81.85,alpha:0.6824},0).wait(1).to({x:90.2,alpha:0.7476},0).wait(1).to({x:97.35,alpha:0.8033},0).wait(1).to({x:103.35,alpha:0.8498},0).wait(1).to({x:108.25,alpha:0.888},0).wait(1).to({x:112.2,alpha:0.9189},0).wait(1).to({x:115.35,alpha:0.9435},0).wait(1).to({x:117.85,alpha:0.9627},0).wait(1).to({x:119.7,alpha:0.9772},0).wait(1).to({x:121.05,alpha:0.9878},0).wait(1).to({x:121.95,alpha:0.9948},0).wait(1).to({x:122.45,alpha:0.9988},0).wait(1).to({regX:130.7,regY:25.7,x:128.7,y:130.7,alpha:1},0).wait(77).to({regX:124.6,regY:27.1,x:122.8,y:132.1,alpha:0.999},0).wait(1).to({x:123.25,alpha:0.9957},0).wait(1).to({x:124.15,alpha:0.99},0).wait(1).to({x:125.35,alpha:0.9816},0).wait(1).to({x:127.1,alpha:0.97},0).wait(1).to({x:129.4,alpha:0.9548},0).wait(1).to({x:132.3,alpha:0.9356},0).wait(1).to({x:135.95,alpha:0.9117},0).wait(1).to({x:140.35,alpha:0.8824},0).wait(1).to({x:145.75,alpha:0.8468},0).wait(1).to({x:152.2,alpha:0.8041},0).wait(1).to({x:159.9,alpha:0.7532},0).wait(1).to({x:168.9,alpha:0.6936},0).wait(1).to({x:179.25,alpha:0.6252},0).wait(1).to({x:190.7,alpha:0.5495},0).wait(1).to({x:202.7,alpha:0.4699},0).wait(1).to({x:214.65,alpha:0.3911},0).wait(1).to({x:225.75,alpha:0.3176},0).wait(1).to({x:235.6,alpha:0.2524},0).wait(1).to({x:244.05,alpha:0.1967},0).wait(1).to({x:251.05,alpha:0.1502},0).wait(1).to({x:256.85,alpha:0.112},0).wait(1).to({x:261.5,alpha:0.0811},0).wait(1).to({x:265.25,alpha:0.0565},0).wait(1).to({x:268.15,alpha:0.0373},0).wait(1).to({x:270.35,alpha:0.0228},0).wait(1).to({x:271.95,alpha:0.0122},0).wait(1).to({x:273,alpha:0.0052},0).wait(1).to({x:273.6,alpha:0.0012},0).wait(1).to({regX:130.7,regY:25.7,x:279.9,y:130.7,alpha:0},0).to({_off:true},1).wait(1));

	// txtS02
	this.instance_1 = new lib.txtS0201();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0.25,130.7,1,1,0,0,0,130.7,25.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(111).to({_off:false},0).wait(1).to({regX:76,regY:16,x:-54.3,y:121,alpha:0.001},0).wait(1).to({x:-53.9,alpha:0.0043},0).wait(1).to({x:-53.15,alpha:0.01},0).wait(1).to({x:-52.05,alpha:0.0184},0).wait(1).to({x:-50.55,alpha:0.03},0).wait(1).to({x:-48.6,alpha:0.0452},0).wait(1).to({x:-46.15,alpha:0.0644},0).wait(1).to({x:-43.1,alpha:0.0883},0).wait(1).to({x:-39.3,alpha:0.1176},0).wait(1).to({x:-34.75,alpha:0.1532},0).wait(1).to({x:-29.25,alpha:0.1959},0).wait(1).to({x:-22.7,alpha:0.2468},0).wait(1).to({x:-15.05,alpha:0.3064},0).wait(1).to({x:-6.3,alpha:0.3748},0).wait(1).to({x:3.45,alpha:0.4505},0).wait(1).to({x:13.65,alpha:0.5301},0).wait(1).to({x:23.8,alpha:0.6089},0).wait(1).to({x:33.25,alpha:0.6824},0).wait(1).to({x:41.6,alpha:0.7476},0).wait(1).to({x:48.75,alpha:0.8033},0).wait(1).to({x:54.75,alpha:0.8498},0).wait(1).to({x:59.65,alpha:0.888},0).wait(1).to({x:63.6,alpha:0.9189},0).wait(1).to({x:66.75,alpha:0.9435},0).wait(1).to({x:69.25,alpha:0.9627},0).wait(1).to({x:71.1,alpha:0.9772},0).wait(1).to({x:72.45,alpha:0.9878},0).wait(1).to({x:73.35,alpha:0.9948},0).wait(1).to({x:73.85,alpha:0.9988},0).wait(1).to({regX:130.7,regY:25.7,x:128.7,y:130.7,alpha:1},0).wait(75).to({regX:76,regY:16,x:74.2,y:121,alpha:0.999},0).wait(1).to({x:74.65,alpha:0.9957},0).wait(1).to({x:75.55,alpha:0.99},0).wait(1).to({x:76.75,alpha:0.9816},0).wait(1).to({x:78.5,alpha:0.97},0).wait(1).to({x:80.8,alpha:0.9548},0).wait(1).to({x:83.7,alpha:0.9356},0).wait(1).to({x:87.35,alpha:0.9117},0).wait(1).to({x:91.75,alpha:0.8824},0).wait(1).to({x:97.15,alpha:0.8468},0).wait(1).to({x:103.6,alpha:0.8041},0).wait(1).to({x:111.3,alpha:0.7532},0).wait(1).to({x:120.3,alpha:0.6936},0).wait(1).to({x:130.65,alpha:0.6252},0).wait(1).to({x:142.1,alpha:0.5495},0).wait(1).to({x:154.1,alpha:0.4699},0).wait(1).to({x:166.05,alpha:0.3911},0).wait(1).to({x:177.15,alpha:0.3176},0).wait(1).to({x:187,alpha:0.2524},0).wait(1).to({x:195.45,alpha:0.1967},0).wait(1).to({x:202.45,alpha:0.1502},0).wait(1).to({x:208.25,alpha:0.112},0).wait(1).to({x:212.9,alpha:0.0811},0).wait(1).to({x:216.65,alpha:0.0565},0).wait(1).to({x:219.55,alpha:0.0373},0).wait(1).to({x:221.75,alpha:0.0228},0).wait(1).to({x:223.35,alpha:0.0122},0).wait(1).to({x:224.4,alpha:0.0052},0).wait(1).to({x:225,alpha:0.0012},0).wait(1).to({regX:130.7,regY:25.7,x:279.9,y:130.7,alpha:0},0).to({_off:true},1).wait(107));

	// txtS01
	this.instance_2 = new lib.txtS0101();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.25,130.7,1,1,0,0,0,130.7,25.7);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({regX:130.5,regY:27.5,x:32.3,y:132.5,alpha:0.2507},0).wait(1).to({x:49.2,alpha:0.3825},0).wait(1).to({x:61.35,alpha:0.477},0).wait(1).to({x:70.85,alpha:0.5512},0).wait(1).to({x:78.7,alpha:0.612},0).wait(1).to({x:85.25,alpha:0.6632},0).wait(1).to({x:90.9,alpha:0.7071},0).wait(1).to({x:95.8,alpha:0.7453},0).wait(1).to({x:100.1,alpha:0.7786},0).wait(1).to({x:103.85,alpha:0.808},0).wait(1).to({x:107.2,alpha:0.834},0).wait(1).to({x:110.15,alpha:0.857},0).wait(1).to({x:112.8,alpha:0.8775},0).wait(1).to({x:115.1,alpha:0.8957},0).wait(1).to({x:117.2,alpha:0.9118},0).wait(1).to({x:119.05,alpha:0.9261},0).wait(1).to({x:120.65,alpha:0.9387},0).wait(1).to({x:122.1,alpha:0.9499},0).wait(1).to({x:123.35,alpha:0.9596},0).wait(1).to({x:124.4,alpha:0.9681},0).wait(1).to({x:125.35,alpha:0.9754},0).wait(1).to({x:126.15,alpha:0.9816},0).wait(1).to({x:126.8,alpha:0.9867},0).wait(1).to({x:127.35,alpha:0.991},0).wait(1).to({x:127.8,alpha:0.9944},0).wait(1).to({x:128.15,alpha:0.9969},0).wait(1).to({x:128.35,alpha:0.9986},0).wait(1).to({x:128.5,alpha:0.9997},0).wait(1).to({regX:130.7,regY:25.7,x:128.7,y:130.7,alpha:1},0).wait(83).to({regX:130.5,regY:27.5,y:132.5,alpha:0.999},0).wait(1).to({x:129.15,alpha:0.9957},0).wait(1).to({x:130.05,alpha:0.99},0).wait(1).to({x:131.25,alpha:0.9816},0).wait(1).to({x:133,alpha:0.97},0).wait(1).to({x:135.3,alpha:0.9548},0).wait(1).to({x:138.2,alpha:0.9356},0).wait(1).to({x:141.85,alpha:0.9117},0).wait(1).to({x:146.25,alpha:0.8824},0).wait(1).to({x:151.65,alpha:0.8468},0).wait(1).to({x:158.1,alpha:0.8041},0).wait(1).to({x:165.8,alpha:0.7532},0).wait(1).to({x:174.8,alpha:0.6936},0).wait(1).to({x:185.15,alpha:0.6252},0).wait(1).to({x:196.6,alpha:0.5495},0).wait(1).to({x:208.6,alpha:0.4699},0).wait(1).to({x:220.55,alpha:0.3911},0).wait(1).to({x:231.65,alpha:0.3176},0).wait(1).to({x:241.5,alpha:0.2524},0).wait(1).to({x:249.95,alpha:0.1967},0).wait(1).to({x:256.95,alpha:0.1502},0).wait(1).to({x:262.75,alpha:0.112},0).wait(1).to({x:267.4,alpha:0.0811},0).wait(1).to({x:271.15,alpha:0.0565},0).wait(1).to({x:274.05,alpha:0.0373},0).wait(1).to({x:276.25,alpha:0.0228},0).wait(1).to({x:277.85,alpha:0.0122},0).wait(1).to({x:278.9,alpha:0.0052},0).wait(1).to({x:279.5,alpha:0.0012},0).wait(1).to({regX:130.7,regY:25.7,x:279.9,y:130.7,alpha:0},0).to({_off:true},1).wait(211));

	// msk (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_123 = new cjs.Graphics().p("A5GEkIAAnIMAyNAAAIAAHIg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(123).to({graphics:mask_graphics_123,x:129.975,y:29.225}).wait(230));

	// txtM0101
	this.instance_3 = new lib.txtM0201();
	this.instance_3.parent = this;
	this.instance_3.setTransform(72.3,75.3,1,1,0,0,0,76.3,30.3);
	this.instance_3._off = true;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(123).to({_off:false},0).wait(1).to({regX:58.6,regY:34.3,x:54.6,y:64.6},0).wait(1).to({y:57.6},0).wait(1).to({y:52.85},0).wait(1).to({y:49.2},0).wait(1).to({y:46.35},0).wait(1).to({y:44},0).wait(1).to({y:42.1},0).wait(1).to({y:40.5},0).wait(1).to({y:39.2},0).wait(1).to({y:38.05},0).wait(1).to({y:37.15},0).wait(1).to({y:36.4},0).wait(1).to({y:35.75},0).wait(1).to({y:35.3},0).wait(1).to({y:34.9},0).wait(1).to({y:34.6},0).wait(1).to({y:34.4},0).wait(1).to({y:34.3},0).wait(1).to({regX:76.3,regY:30.3,x:72.3,y:30.3},0).wait(180).to({regX:58.6,regY:34.3,x:54.6,y:34.3},0).wait(1).to({y:34.2},0).wait(1).to({y:34.05},0).wait(1).to({y:33.85},0).wait(1).to({y:33.55},0).wait(1).to({y:33.2},0).wait(1).to({y:32.7},0).wait(1).to({y:32.1},0).wait(1).to({y:31.35},0).wait(1).to({y:30.5},0).wait(1).to({y:29.45},0).wait(1).to({y:28.15},0).wait(1).to({y:26.65},0).wait(1).to({y:24.8},0).wait(1).to({y:22.55},0).wait(1).to({y:19.7},0).wait(1).to({y:16.1},0).wait(1).to({y:11.25},0).wait(1).to({y:4.05},0).wait(1).to({regX:76.3,regY:30.3,x:72.3,y:-14.7},0).to({_off:true},1).wait(11));

	// msk copy (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_123 = new cjs.Graphics().p("A5GIKIAAnKMAyNAAAIAAHKg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(123).to({graphics:mask_1_graphics_123,x:129.975,y:52.15}).wait(230));

	// txtM0102 copy
	this.instance_4 = new lib.txtM0203();
	this.instance_4.parent = this;
	this.instance_4.setTransform(116.4,97.6,1,1,0,0,0,120.4,52.6);
	this.instance_4._off = true;

	this.instance_5 = new lib.txtM0202();
	this.instance_5.parent = this;
	this.instance_5.setTransform(116.4,7.6,1,1,0,0,0,120.4,52.6);

	var maskedShapeInstanceList = [this.instance_4,this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_4}]},225).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},79).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_5}]},1).to({state:[]},1).wait(8));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(225).to({_off:false},0).wait(1).to({regX:86,regY:80.7,x:82,y:125.55},0).wait(1).to({y:125.25},0).wait(1).to({y:124.6},0).wait(1).to({y:123.65},0).wait(1).to({y:122.25},0).wait(1).to({y:120.4},0).wait(1).to({y:117.85},0).wait(1).to({y:114.55},0).wait(1).to({y:110.4},0).wait(1).to({y:105.4},0).wait(1).to({y:100.05},0).wait(1).to({y:94.95},0).wait(1).to({y:90.75},0).wait(1).to({y:87.45},0).wait(1).to({y:85},0).wait(1).to({y:83.2},0).wait(1).to({y:82},0).wait(1).to({y:81.25},0).wait(1).to({y:80.8},0).wait(1).to({regX:120.4,regY:52.6,x:116.4,y:52.6},0).wait(80).to({regX:86,regY:80.7,x:82,y:80.7},0).wait(1).to({y:80.6},0).wait(1).to({y:80.45},0).wait(1).to({y:80.25},0).wait(1).to({y:79.95},0).wait(1).to({y:79.6},0).wait(1).to({y:79.1},0).wait(1).to({y:78.5},0).wait(1).to({y:77.75},0).wait(1).to({y:76.9},0).wait(1).to({y:75.85},0).wait(1).to({y:74.55},0).wait(1).to({y:73.05},0).wait(1).to({y:71.2},0).wait(1).to({y:68.95},0).wait(1).to({y:66.1},0).wait(1).to({y:62.5},0).wait(1).to({y:57.65},0).wait(1).to({y:50.45},0).to({_off:true},1).wait(9));

	// txtM0102
	this.instance_6 = new lib.txtM0202();
	this.instance_6.parent = this;
	this.instance_6.setTransform(116.4,97.6,1,1,0,0,0,120.4,52.6);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(126).to({_off:false},0).wait(1).to({regX:132.3,regY:78.9,x:128.3,y:109.2},0).wait(1).to({y:102.2},0).wait(1).to({y:97.45},0).wait(1).to({y:93.8},0).wait(1).to({y:90.95},0).wait(1).to({y:88.6},0).wait(1).to({y:86.7},0).wait(1).to({y:85.1},0).wait(1).to({y:83.8},0).wait(1).to({y:82.65},0).wait(1).to({y:81.75},0).wait(1).to({y:81},0).wait(1).to({y:80.35},0).wait(1).to({y:79.9},0).wait(1).to({y:79.5},0).wait(1).to({y:79.2},0).wait(1).to({y:79},0).wait(1).to({y:78.9},0).wait(1).to({regX:120.4,regY:52.6,x:116.4,y:52.6},0).wait(81).to({regX:132.3,regY:78.9,x:128.3,y:78.8},0).wait(1).to({y:78.5},0).wait(1).to({y:77.85},0).wait(1).to({y:76.9},0).wait(1).to({y:75.5},0).wait(1).to({y:73.65},0).wait(1).to({y:71.1},0).wait(1).to({y:67.8},0).wait(1).to({y:63.65},0).wait(1).to({y:58.65},0).wait(1).to({y:53.3},0).wait(1).to({y:48.2},0).wait(1).to({y:44},0).wait(1).to({y:40.7},0).wait(1).to({y:38.25},0).wait(1).to({y:36.45},0).wait(1).to({y:35.25},0).wait(1).to({y:34.5},0).wait(1).to({y:34.05},0).wait(1).to({regX:120.4,regY:52.6,x:116.4,y:7.6},0).to({_off:true},1).wait(107));

	// msk (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_0 = new cjs.Graphics().p("A5GEkIAAnIMAyNAAAIAAHIg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:mask_2_graphics_0,x:129.975,y:29.225}).wait(120).to({graphics:null,x:0,y:0}).wait(233));

	// txtM0101
	this.instance_7 = new lib.txtM0101();
	this.instance_7.parent = this;
	this.instance_7.setTransform(72.3,75.3,1,1,0,0,0,76.3,30.3);

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({regX:71.1,regY:35.6,x:67.1,y:65.9},0).wait(1).to({y:58.9},0).wait(1).to({y:54.15},0).wait(1).to({y:50.5},0).wait(1).to({y:47.65},0).wait(1).to({y:45.3},0).wait(1).to({y:43.4},0).wait(1).to({y:41.8},0).wait(1).to({y:40.5},0).wait(1).to({y:39.35},0).wait(1).to({y:38.45},0).wait(1).to({y:37.7},0).wait(1).to({y:37.05},0).wait(1).to({y:36.6},0).wait(1).to({y:36.2},0).wait(1).to({y:35.9},0).wait(1).to({y:35.7},0).wait(1).to({y:35.6},0).wait(1).to({regX:76.3,regY:30.3,x:72.3,y:30.3},0).wait(81).to({regX:71.1,regY:35.6,x:67.1,y:35.6},0).wait(1).to({y:35.5},0).wait(1).to({y:35.35},0).wait(1).to({y:35.15},0).wait(1).to({y:34.85},0).wait(1).to({y:34.5},0).wait(1).to({y:34},0).wait(1).to({y:33.4},0).wait(1).to({y:32.65},0).wait(1).to({y:31.8},0).wait(1).to({y:30.75},0).wait(1).to({y:29.45},0).wait(1).to({y:27.95},0).wait(1).to({y:26.1},0).wait(1).to({y:23.85},0).wait(1).to({y:21},0).wait(1).to({y:17.4},0).wait(1).to({y:12.55},0).wait(1).to({y:5.35},0).wait(1).to({regX:76.3,regY:30.3,x:72.3,y:-14.7},0).to({_off:true},1).wait(233));

	// msk copy (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	var mask_3_graphics_0 = new cjs.Graphics().p("A5GIKIAAnKMAyNAAAIAAHKg");

	this.timeline.addTween(cjs.Tween.get(mask_3).to({graphics:mask_3_graphics_0,x:129.975,y:52.15}).wait(123).to({graphics:null,x:0,y:0}).wait(230));

	// txtM0102
	this.instance_8 = new lib.txtM0102();
	this.instance_8.parent = this;
	this.instance_8.setTransform(116.4,97.6,1,1,0,0,0,120.4,52.6);
	this.instance_8._off = true;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(3).to({_off:false},0).wait(1).to({regX:119.5,regY:80.7,x:115.5,y:111},0).wait(1).to({y:104},0).wait(1).to({y:99.25},0).wait(1).to({y:95.6},0).wait(1).to({y:92.75},0).wait(1).to({y:90.4},0).wait(1).to({y:88.5},0).wait(1).to({y:86.9},0).wait(1).to({y:85.6},0).wait(1).to({y:84.45},0).wait(1).to({y:83.55},0).wait(1).to({y:82.8},0).wait(1).to({y:82.15},0).wait(1).to({y:81.7},0).wait(1).to({y:81.3},0).wait(1).to({y:81},0).wait(1).to({y:80.8},0).wait(1).to({y:80.7},0).wait(1).to({regX:120.4,regY:52.6,x:116.4,y:52.6},0).wait(81).to({regX:119.5,regY:80.7,x:115.5,y:80.7},0).wait(1).to({y:80.6},0).wait(1).to({y:80.45},0).wait(1).to({y:80.25},0).wait(1).to({y:79.95},0).wait(1).to({y:79.6},0).wait(1).to({y:79.1},0).wait(1).to({y:78.5},0).wait(1).to({y:77.75},0).wait(1).to({y:76.9},0).wait(1).to({y:75.85},0).wait(1).to({y:74.55},0).wait(1).to({y:73.05},0).wait(1).to({y:71.2},0).wait(1).to({y:68.95},0).wait(1).to({y:66.1},0).wait(1).to({y:62.5},0).wait(1).to({y:57.65},0).wait(1).to({y:50.45},0).wait(1).to({regX:120.4,regY:52.6,x:116.4,y:7.6},0).to({_off:true},1).wait(230));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.4,0,536.7,153);


(lib.LEGALMOV = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal_1();
	this.instance.parent = this;
	this.instance.setTransform(130,188.5,1,1,0,0,0,130,188.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},19).wait(80).to({alpha:0},20).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,260,377);


(lib.cross = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(0.4,0.4,1,1,0,0,0,5.4,5.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.cross, new cjs.Rectangle(-5.1,-5.1,11.1,11.1), null);


(lib.LOGOGROUP = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// LOGO_gpb
	this.instance = new lib.LOGO_gpb();
	this.instance.parent = this;
	this.instance.setTransform(-0.45,-81.8,0.69,0.69,0,0,0,167.5,24.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// cross
	this.instance_1 = new lib.cross();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-1,-40);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// LOGO_visa
	this.instance_2 = new lib.LOGO_visa();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,3);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// cross copy
	this.instance_3 = new lib.cross();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-1,46);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// LOGO_aeroflit
	this.instance_4 = new lib.LOGO_aeroflit();
	this.instance_4.parent = this;
	this.instance_4.setTransform(0,85);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116,-99,232.6,202.5);


(lib.movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FADE
	this.instance = new lib.BG_BLCK();
	this.instance.parent = this;
	this.instance.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},19).to({_off:true},1).wait(56).to({_off:false},0).to({alpha:1},21).to({alpha:0},19).to({_off:true},1).wait(442).to({_off:false},0).to({alpha:1},20).wait(1));

	// LEGAL
	this.instance_1 = new lib.LEGALMOV("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,319.5,1,1,0,0,0,130,188.5);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(459).to({_off:false},0).to({_off:true},120).wait(1));

	// LOGO_GPB
	this.instance_2 = new lib.LOGO_gpb();
	this.instance_2.parent = this;
	this.instance_2.setTransform(135.5,47.2,0.69,0.69,0,0,0,167.4,24.9);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(97).to({_off:false},0).wait(483));

	// BTN
	this.instance_3 = new lib.BUTT("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,559);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(97).to({_off:false},0).wait(483));

	// TXT
	this.instance_4 = new lib.TXT01("synched",0,false);
	this.instance_4.parent = this;
	this.instance_4.setTransform(150.7,430.2,1,1,0,0,0,130.7,78.2);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(106).to({_off:false},0).to({_off:true},353).wait(121));

	// ELIPSE
	this.instance_5 = new lib.elipse();
	this.instance_5.parent = this;
	this.instance_5.setTransform(417.5,157);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(97).to({_off:false},0).wait(1).to({x:377.7108,alpha:0.2094},0).wait(1).to({x:355.4434,alpha:0.3266},0).wait(1).to({x:339.0975,alpha:0.4126},0).wait(1).to({x:326.0414,alpha:0.4814},0).wait(1).to({x:315.154,alpha:0.5387},0).wait(1).to({x:305.8338,alpha:0.5877},0).wait(1).to({x:297.7137,alpha:0.6305},0).wait(1).to({x:290.5502,alpha:0.6682},0).wait(1).to({x:284.172,alpha:0.7017},0).wait(1).to({x:278.4532,alpha:0.7318},0).wait(1).to({x:273.2979,alpha:0.759},0).wait(1).to({x:268.6313,alpha:0.7835},0).wait(1).to({x:264.3937,alpha:0.8058},0).wait(1).to({x:260.5364,alpha:0.8261},0).wait(1).to({x:257.019,alpha:0.8446},0).wait(1).to({x:253.808,alpha:0.8615},0).wait(1).to({x:250.8747,alpha:0.877},0).wait(1).to({x:248.1947,alpha:0.8911},0).wait(1).to({x:245.7468,alpha:0.904},0).wait(1).to({x:243.5127,alpha:0.9157},0).wait(1).to({x:241.476,alpha:0.9264},0).wait(1).to({x:239.6226,alpha:0.9362},0).wait(1).to({x:237.9398,alpha:0.9451},0).wait(1).to({x:236.4162,alpha:0.9531},0).wait(1).to({x:235.0417,alpha:0.9603},0).wait(1).to({x:233.8072,alpha:0.9668},0).wait(1).to({x:232.7043,alpha:0.9726},0).wait(1).to({x:231.7256,alpha:0.9778},0).wait(1).to({x:230.8641,alpha:0.9823},0).wait(1).to({x:230.1136,alpha:0.9862},0).wait(1).to({x:229.4684,alpha:0.9896},0).wait(1).to({x:228.9231,alpha:0.9925},0).wait(1).to({x:228.4728,alpha:0.9949},0).wait(1).to({x:228.1131,alpha:0.9968},0).wait(1).to({x:227.8397,alpha:0.9982},0).wait(1).to({x:227.6488,alpha:0.9992},0).wait(1).to({x:227.5367,alpha:0.9998},0).wait(1).to({x:227.5,alpha:1},0).wait(294).to({x:227.4577,alpha:0.9997},0).wait(1).to({x:227.3272,alpha:0.9989},0).wait(1).to({x:227.1024,alpha:0.9976},0).wait(1).to({x:226.7767,alpha:0.9955},0).wait(1).to({x:226.3429,alpha:0.9929},0).wait(1).to({x:225.7927,alpha:0.9895},0).wait(1).to({x:225.1174,alpha:0.9853},0).wait(1).to({x:224.3067,alpha:0.9803},0).wait(1).to({x:223.3495,alpha:0.9745},0).wait(1).to({x:222.233,alpha:0.9676},0).wait(1).to({x:220.943,alpha:0.9596},0).wait(1).to({x:219.4629,alpha:0.9505},0).wait(1).to({x:217.774,alpha:0.9401},0).wait(1).to({x:215.8545,alpha:0.9283},0).wait(1).to({x:213.6791,alpha:0.9149},0).wait(1).to({x:211.2182,alpha:0.8998},0).wait(1).to({x:208.4362,alpha:0.8827},0).wait(1).to({x:205.2908,alpha:0.8633},0).wait(1).to({x:201.7303,alpha:0.8414},0).wait(1).to({x:197.6907,alpha:0.8166},0).wait(1).to({x:193.0915,alpha:0.7883},0).wait(1).to({x:187.829,alpha:0.7559},0).wait(1).to({x:181.7658,alpha:0.7186},0).wait(1).to({x:174.7144,alpha:0.6752},0).wait(1).to({x:166.4061,alpha:0.624},0).wait(1).to({x:156.4346,alpha:0.5627},0).wait(1).to({x:144.1319,alpha:0.487},0).wait(1).to({x:128.253,alpha:0.3892},0).wait(1).to({x:105.8981,alpha:0.2517},0).wait(1).to({x:65,alpha:0},0).to({_off:true},1).wait(121));

	// BOND
	this.instance_6 = new lib.bndrchk_1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(170,242);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(97).to({_off:false},0).wait(342).to({regX:2.4,regY:75.4,x:172.4,y:317.4,alpha:0.9994},0).wait(1).to({alpha:0.9976},0).wait(1).to({alpha:0.9943},0).wait(1).to({alpha:0.9895},0).wait(1).to({alpha:0.983},0).wait(1).to({alpha:0.9745},0).wait(1).to({alpha:0.9638},0).wait(1).to({alpha:0.9505},0).wait(1).to({alpha:0.9344},0).wait(1).to({alpha:0.9149},0).wait(1).to({alpha:0.8915},0).wait(1).to({alpha:0.8633},0).wait(1).to({alpha:0.8294},0).wait(1).to({alpha:0.7883},0).wait(1).to({alpha:0.7379},0).wait(1).to({alpha:0.6752},0).wait(1).to({alpha:0.5948},0).wait(1).to({alpha:0.487},0).wait(1).to({alpha:0.3274},0).wait(1).to({regX:0,regY:0,x:170,y:242,alpha:0},0).to({_off:true},1).wait(121));

	// LOGOGROUP
	this.instance_7 = new lib.LOGOGROUP("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(150.8,301.65);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({_off:true},97).wait(483));

	// BG
	this.instance_8 = new lib.BG_BLCK();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(580));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1622,-60.3,2256.8,694.0999999999999);


// stage content:
(lib.gpb_arflvisa_plane_300x600_review = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// movie
	this.instance = new lib.movie();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// button
	this.instance_1 = new lib.btn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,300,1.25,1.5);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(149,299,152,302);
// library properties:
lib.properties = {
	id: 'F66FE7A2AC3D5941AE55BF9D2D3ACE18',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"gpb_arflvisa_plane_300x600_review_atlas_P_.png", id:"gpb_arflvisa_plane_300x600_review_atlas_P_"},
		{src:"gpb_arflvisa_plane_300x600_review_atlas_NP_.jpg", id:"gpb_arflvisa_plane_300x600_review_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F66FE7A2AC3D5941AE55BF9D2D3ACE18'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;