(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,0,1456,180],[0,182,1456,180],[1720,0,203,198],[1458,0,260,180],[0,364,882,142]]}
];


// symbols:



(lib.BG = function() {
	this.initialize(ss["index_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.BGgirlRED = function() {
	this.initialize(ss["index_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.girl = function() {
	this.initialize(ss["index_atlas_"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.KARD = function() {
	this.initialize(ss["index_atlas_"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.legal = function() {
	this.initialize(ss["index_atlas_"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt03 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A05DkIAAiaIAQAAIAAASQAIgKALgFQALgGANAAQAQABANAHQAMAIAHANQAHANABARQgBARgHANQgHANgMAHQgNAIgQAAQgNAAgLgEQgKgFgHgJIAAA6gA0TBcQgJAEgFAKQgHAJAAAPQAAAOAHAKQAFAJAIAFQAKAFAJAAQAMgBAJgFQAIgGAGgJQAFgKAAgMQAAgMgFgKQgFgJgJgGQgJgFgMgBQgJABgJAEgAtIC0QgNgHgIgOQgHgMgBgRQABgRAHgNQAIgNANgIQANgHARgBQAQABAOAHQANAIAIANQAHANABARQgBARgHAMQgIAOgNAHQgOAIgQAAQgQAAgOgIgAs/BeQgJAFgFAJQgFAKgBAMQABAMAFAJQAFAKAJAGQAKAFALAAQALAAAKgFQAJgGAFgKQAGgJgBgMQABgMgGgKQgFgJgJgFQgJgGgMgBQgMABgJAGgAu5C0QgNgHgIgOQgIgMAAgRQAAgRAIgNQAIgNANgIQANgHAQgBQAQAAALAHQAMAGAIAMIgNAKQgGgJgIgEQgJgFgKgBQgMABgJAGQgJAFgGAJQgEAKgBAMQABAMAEAJQAGAKAJAGQAJAFAMABQAKgBAIgFQAJgEAGgIIAMAJQgHAMgMAGQgMAHgPgBQgQAAgNgIgAxFC8IAAhyIASAAIAABPIBFhSIAGAAIAABzIgRAAIAAhPIhFBRgA2bC0QgNgHgHgNQgJgNAAgRQABgQAHgNQAHgOANgIQANgHAQgBQAPAAAMAHQALAGAHALQAGAMABAPIgBAIIgBAFIhYAAQABALAGAJQAFAIAJAEQAJAFALABQALgBAIgEQAIgEAIgHIAKAMQgJAJgLAGQgMAEgNAAQgRAAgOgIgA1eB4QAAgKgEgIQgFgHgHgEQgIgDgJgBQgOAAgKAJQgLAJgDAPIBHAAIAAAAgA4MC0QgOgHgHgOQgIgMAAgRQAAgRAIgNQAHgNAOgIQANgHAQgBQAQAAALAHQAMAGAIAMIgNAKQgGgJgIgEQgJgFgKgBQgMABgJAGQgJAFgGAJQgEAKgBAMQABAMAEAJQAGAKAJAGQAJAFAMABQALgBAHgFQAJgEAGgIIAMAJQgHAMgMAGQgMAHgPgBQgQAAgNgIgAp4C6IAAhLIgmAtIgHAAIgmgtIAABLIgSAAIAAhzIAGAAIA2A/IA1g/IAFAAIAABzgAy0C6IAAhwIAtAAQASAAAJAIQAKAIAAAOQAAAGgDAGQgDAGgGADQAKAEAFAGQAGAHAAAKQAAAPgKAKQgLAJgSAAgAyiCqIAhAAQALABAFgGQAHgFgBgIQABgHgHgFQgGgFgKAAIghAAgAyiB4IAcAAQAJAAAFgFQAEgDAAgHQAAgIgEgDQgFgEgJAAIgcAAgAzigeIAAiaIARAAIAAASQAGgKAMgFQAKgGAOABQAQAAANAHQAMAIAHANQAIANAAARQAAARgIANQgHANgMAIQgNAHgQABQgMgBgLgEQgLgFgHgJIAAA6gAy8imQgJAFgGAJQgFAJAAAPQAAAPAFAJQAGAJAIAFQAJAEAKABQAMgBAJgFQAJgGAFgJQAFgKAAgMQAAgMgFgJQgFgKgJgGQgJgFgMgBQgKAAgIAFgAMignIAAghIhaAAIAAhwIATAAIAABhIA1AAIAAhhIASAAIAABhIASAAIAAAwgACGgnIAAghIhYAAIAAAhIgSAAIAAgwIAMAAQAIgKAEgQQACgQABgYIABgfIBNAAIAABhIASAAIAAAwgABIiZQgBAZgDARQgDAQgGAIIA4AAIAAhRIgqAAgAPNhNQgMgJgIgNQgIgNAAgQQAAgRAIgNQAIgNANgIQANgHAQAAQARAAAOAHQAMAIAIANQAIANABARQgBAQgIANQgIANgMAJQgOAHgRABQgQgBgOgHgAPXikQgJAFgGAKQgFAJAAAMQAAAMAFAJQAFAKAJAFQAKAGALAAQAMAAAJgGQAKgFAEgKQAGgJAAgMQAAgMgGgJQgFgKgIgFQgKgGgMgBQgLABgJAGgANDhFIAAhzIASAAIAABQIBDhSIAHAAIAAByIgRAAIAAhPIhFBSgAHxhJQgJgEgEgHQgGgHAAgKQAAgPALgIQALgIASAAIAkAAIAAgKQgBgOgGgHQgIgIgNAAQgKABgIAFQgHAEgHAIIgMgJQAJgMAMgHQALgFAOAAQAMAAALAEQAKAGAFAKQAGAKgBAPIAABFIgQAAIAAgOQgGAHgJAFQgKAFgNAAQgLAAgJgEgAH3hyQgHAEAAAIQAAAGADAEQAEAEAFACQAFACAHAAQAJAAAHgFQAJgDAEgIQAFgGAAgJIAAgDIghAAQgNAAgFAEgAEyhNQgOgIgIgOQgHgNAAgQQAAgRAHgNQAIgNAOgIQAMgHARAAQAQgBALAHQAMAGAHAMIgMAKQgHgJgIgEQgIgFgLgBQgMABgIAGQgKAFgFAKQgFAJAAAMQAAAMAFAJQAFAKAKAFQAIAGAMABQALgBAIgFQAIgEAHgIIAMAJQgIAMgLAGQgMAHgPAAQgRgBgMgHgACmhFIAAhzIASAAIAABQIBEhSIAHAAIAAByIgSAAIAAhPIhFBSgArWhJQgJgEgEgHQgGgHAAgKQAAgPALgIQALgIASAAIAkAAIAAgKQgBgOgGgHQgIgIgNAAQgKABgIAFQgHAEgHAIIgMgJQAJgMAMgHQALgFAOAAQAMAAAKAEQALAGAFAKQAGAKgBAPIAABFIgQAAIAAgOQgGAHgJAFQgKAFgNAAQgLAAgJgEgArQhyQgHAEAAAIQAAAGADAEQAEAEAFACQAFACAHAAQAJAAAHgFQAJgDAEgIQAFgGAAgJIAAgDIghAAQgNAAgFAEgAtWhFIAAhzIASAAIAABQIBEhSIAGAAIAAByIgRAAIAAhPIhEBSgAxIhNQgOgIgHgNQgIgNAAgRQgBgRAIgMQAIgOANgIQANgHAPAAQAPgBAMAHQALAGAHALQAHAMAAAPIAAAIIgBAGIhZAAQABAKAFAJQAGAIAJAEQAJAGALAAQALgBAIgEQAJgEAGgHIAKAMQgIAJgLAGQgLAEgOABQgRgBgNgHgAwLiKQAAgLgFgHQgFgHgHgEQgHgEgKAAQgOABgKAIQgLAJgCAPIBHAAIAAAAgA4fhFIAAibIASAAIAAB2IBjh5IAFAAIAACbIgSAAIAAh2IhiB5gAqChIIgCAAIAAgPIACABIADAAQAKAAAFgSQAEgTABggIABgdIBLAAIAABwIgRAAIAAhgIgpAAIgBANQgBAdgEASQgDATgIAJQgHAJgNAAIgEgBgAYYhIIAAhLIgmAtIgHAAIgmgtIAABLIgSAAIAAhyIAHAAIA1A/IA1g/IAGAAIAABygAWIhIIAAhwIASAAIAABwgAUihIIAAhwIASAAIAAAmIAaAAQATABALAJQAMAKAAARQAAARgMAKQgLAKgTAAgAU0hXIAZAAQAMAAAHgGQAFgFAAgLQABgKgHgFQgGgFgMAAIgZAAgAT2hIIAAg0Ig3AAIAAA0IgSAAIAAhwIASAAIAAAtIA3AAIAAgtIASAAIAABwgASBhIIAAg0Ig2AAIAAA0IgSAAIAAhwIASAAIAAAtIA2AAIAAgtIASAAIAABwgAKchIIAAg0Ig2AAIAAA0IgSAAIAAhwIASAAIAAAtIA2AAIAAgtIASAAIAABwgAGlhIIAAhgIgmAAIAAgQIBdAAIAAAQIglAAIAABggAgxhIIAAhLIgmAtIgHAAIgmgtIAABLIgSAAIAAhyIAHAAIA1A/IA1g/IAGAAIAABygAjBhIIAAhwIASAAIAABwgAknhIIAAhwIASAAIAAAmIAaAAQATABALAJQAMAKAAARQAAARgMAKQgLAKgTAAgAkVhXIAZAAQAMAAAHgGQAFgFAAgLQABgKgHgFQgGgFgMAAIgZAAgAlThIIAAg0Ig3AAIAAA0IgSAAIAAhwIASAAIAAAtIA3AAIAAgtIARAAIAABwgAoFhIIAAhwIASAAIAAAmIAbAAQATABAMAKQAKAJABARQgBARgKAKQgMAKgTAAgAnzhXIAaAAQAMgBAGgFQAHgGAAgKQgBgJgGgGQgGgFgMAAIgaAAgAuChIIAAhLIgmAtIgHAAIgmgtIAABLIgSAAIAAhyIAGAAIA1A/IA1g/IAHAAIAABygA0OhIIAAhgIg1AAIAABgIgTAAIAAhwIBaAAIAABwg");
	this.shape.setTransform(160.8,31.75);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt03, new cjs.Rectangle(0,0,386.1,58.8), null);


(lib.txt02 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Au1DuIAAiaIARAAIAAASQAHgKALgFQALgFANAAQAQAAANAIQAMAHAHANQAIAOAAAQQAAARgIANQgHANgMAIQgNAIgQAAQgMAAgLgFQgLgFgHgJIAAA6gAuPBmQgJAFgFAJQgGAJAAAPQAAAPAGAJQAFAKAJAEQAJAFAKAAQALgBAJgFQAJgFAFgKQAFgJAAgNQAAgMgFgJQgFgKgJgGQgJgFgLAAQgKAAgJAEgATDC8QgNgLgFgSQgGgSAAgWQAAgWAGgSQAGgRAMgKQAMgKAUAAQATAAAMAKQAMAKAGARQAGASAAAWQAAAWgGASQgFASgNALQgMAKgTABQgUgBgMgKgATNBCQgIAIgEANQgEAOABASQgBASAEAPQAEAOAIAIQAIAIAOAAQANAAAIgIQAIgIAEgOQADgPAAgSQAAgSgDgOQgEgNgIgIQgIgIgNAAQgOAAgIAIgAMyC/QgNgIgIgNQgIgNAAgRQAAgQAIgOQAIgNANgHQANgIARAAQAPAAAMAGQAMAHAHALIgNAKQgGgIgIgFQgIgFgLAAQgMAAgJAGQgJAFgFAKQgFAJgBAMQABAMAFAKQAFAJAJAGQAJAFAMABQALgBAIgEQAIgFAGgIIANAJQgIAMgLAGQgMAHgPAAQgRAAgNgIgAJyDDQgJgEgFgHQgFgHAAgKQAAgOALgJQALgIASAAIAkAAIAAgKQgBgOgHgHQgHgHgNAAQgKAAgIAFQgIAEgGAJIgMgKQAIgMAMgGQAMgGAOAAQAMAAAKAFQAKAFAGAKQAFAKAAAPIAABFIgQAAIAAgOQgGAIgKAEQgKAFgMAAQgLAAgJgEgAJ3CaQgGAEAAAIQAAAGADAEQADAEAGACQAFACAGAAQAKAAAHgEQAIgEAFgHQAEgHABgJIAAgDIgiAAQgMAAgGAEgAIGC/QgOgIgHgNQgIgNAAgRQAAgQAHgNQAIgOANgHQANgIAQAAQAOAAAMAGQALAHAHALQAHALAAAPIAAAIIgBAGIhZAAQABALAGAIQAFAIAJAFQAJAFALAAQALgBAIgEQAJgEAHgHIAKAMQgIAJgMAGQgLAFgOAAQgRAAgNgIgAJDCCQAAgKgFgIQgFgHgHgEQgHgDgJAAQgPAAgKAJQgKAIgDAPIBHAAIAAAAgAGbDAQgLgGgGgJIALgMQAHAIAHAEQAIAFAKABQAJAAAGgFQAGgEABgHQgBgHgFgEQgFgEgJgDIgLgFQgNgFgHgHQgIgHAAgMQAAgKAGgHQAFgHAIgEQAJgDAKAAQAMAAAKAFQAJAEAHAIIgLALQgGgFgHgEQgHgDgIAAQgIAAgFAEQgFADAAAHQAAAGAEADQAEAEAKADIAKAFQAPAGAHAIQAIAHAAAMQAAALgGAHQgFAIgJADQgJAEgLAAQgPAAgLgHgAEyC/QgOgIgHgNQgIgNAAgRQAAgQAHgNQAIgOANgHQANgIAQAAQAOAAAMAGQALAHAHALQAHALAAAPIAAAIIgBAGIhZAAQABALAGAIQAFAIAJAFQAJAFALAAQALgBAIgEQAJgEAHgHIAKAMQgIAJgMAGQgLAFgOAAQgRAAgNgIgAFvCCQAAgKgFgIQgFgHgHgEQgHgDgJAAQgPAAgKAJQgKAIgDAPIBHAAIAAAAgAjcDDQgJgEgFgHQgFgHAAgKQAAgOALgJQALgIASAAIAkAAIAAgKQgBgOgHgHQgHgHgNAAQgKAAgIAFQgIAEgGAJIgMgKQAIgMAMgGQAMgGAOAAQAMAAAKAFQAKAFAGAKQAFAKAAAPIAABFIgQAAIAAgOQgGAIgKAEQgKAFgMAAQgLAAgJgEgAjXCaQgGAEAAAIQAAAGADAEQADAEAGACQAFACAGAAQAKAAAHgEQAIgEAFgHQAEgHABgJIAAgDIgiAAQgMAAgGAEgApFDHIAAhzIASAAIAABQIBEhSIAGAAIAAByIgRAAIAAhPIhFBSgAq9DHIAAhzIASAAIAABQIBEhSIAHAAIAAByIgSAAIAAhPIhEBSgAsaC/QgOgIgHgNQgIgNAAgRQAAgQAIgOQAHgNAOgHQANgIAQAAQAQAAALAGQAMAHAIALIgNAKQgGgIgIgFQgJgFgKAAQgMAAgJAGQgKAFgFAKQgFAJAAAMQAAAMAFAKQAFAJAKAGQAJAFAMABQAKgBAIgEQAJgFAGgIIAMAJQgHAMgMAGQgMAHgPAAQgQAAgNgIgAwXC/QgOgIgHgNQgIgNAAgRQAAgQAHgNQAIgOANgHQANgIAQAAQAOAAAMAGQALAHAHALQAHALAAAPIAAAIIgBAGIhZAAQABALAGAIQAFAIAJAFQAJAFALAAQALgBAIgEQAJgEAHgHIAKAMQgIAJgMAGQgLAFgOAAQgRAAgNgIgAvaCCQAAgKgFgIQgFgHgHgEQgHgDgJAAQgPAAgKAJQgKAIgDAPIBHAAIAAAAgA0+C/QgNgIgHgNQgIgNAAgRQAAgRAIgNQAHgNAOgHQANgIAQAAQARAAANAIQANAHAIANQAIAOAAAQQAAARgIANQgIANgNAIQgNAHgRABQgQgBgOgHgA00BoQgKAFgFAKQgFAJAAAMQAAAMAFAKQAFAJAJAGQAKAFALAAQAMAAAJgFQAJgGAFgJQAGgKAAgMQAAgMgGgJQgFgKgJgFQgJgGgMAAQgLAAgJAGgAWLDEIAng3IgGABIgHABQgNAAgLgHQgMgGgGgMQgHgLAAgOQAAgPAHgLQAHgMALgGQAMgHAPAAQAOAAAMAHQALAGAHAMQAHALAAAPQAAAKgDAIQgCAHgFAIIgLAQIglA2gAWWA/QgHAEgFAIQgEAIgBAKQABAKAEAHQAFAIAHAFQAIAEAKABQAJgBAIgEQAIgFAEgIQAEgHABgKQgBgKgEgIQgEgIgIgEQgIgFgJAAQgKAAgIAFgAVKDEIAAiCIgiAKIgEgQIAxgQIAHAAIAACYgAQyDEIAAgEIA2g6QAMgMAHgLQAHgLAAgLQAAgIgDgHQgEgHgGgEQgHgFgJAAQgJAAgHAFQgHAEgEAHQgDAHAAAJIAAAGIABAGIgSAAIgCgGIAAgHQAAgMAGgLQAGgKALgHQALgHAPAAQAOAAALAGQALAGAGAKQAGALAAANQAAALgFAKQgEAKgIAJIgPARIghAjIBHAAIAAAQgAPbDEIAAhEQAAgNgIgJQgHgIgNAAQgNAAgIAJQgIAIAAANIAABEIgSAAIAAisIASAAIAABJQAFgHAJgEQAIgEALAAQANAAAKAFQAJAGAFAKQAFAKAAANIAABGgALWDEIAAhwIAQAAIAAAQQAHgIAJgEQAJgFAKAAIAFABIADAAIAAAQIgGAAQgKAAgHAEQgIADgFAIQgFAHAAALIAAA/gAD9DEIgvg/IghAAIAAA/IgSAAIAAiYIA2AAQAPABAKAFQALAGAGAKQAGAKAAAMQAAAQgIALQgJALgPAFIAxBBgACtB1IAjAAQAPgBAIgHQAHgIAAgMQAAgNgHgIQgIgHgPgBIgjAAgABEDEIg0g/IAvgxIAXAAIgwAxIA1A/gAgCDEIAAisIARAAIAACsgAgtDEIAAhEQAAgOgIgIQgHgIgNAAQgNAAgIAIQgIAJAAANIAABEIgSAAIAAhwIAQAAIAAAMQAGgHAJgDQAJgEALAAQANAAAJAFQAKAGAFAKQAFAKAAANIAABGgAktDEIAAhwIAQAAIAAAQQAHgIAJgEQAJgFAKAAIAFABIADAAIAAAQIgGAAQgKAAgHAEQgIADgFAIQgFAHAAALIAAA/gAmYDEIAAiYIBfAAIAAAQIhNAAIAAA1IBAAAIAAAQIhAAAIAABDgAydDEIAAhwIAuAAQARABAJAHQAKAIAAAOQAAAHgDAFQgDAGgGADQAKAEAGAHQAFAGABAKQgBAPgKAKQgLAJgSAAgAyLC1IAhAAQALAAAGgGQAGgFAAgIQAAgHgGgFQgGgEgLAAIghAAgAyLCCIAcAAQAJAAAFgEQAFgEAAgHQAAgHgFgEQgFgEgJAAIgcAAgA1/DEIAAhgIg2AAIAABgIgSAAIAAhwIBaAAIAABwgA08gSIgJgCIAAgPIAIABIAGAAQAIAAAGgDQAHgEAEgLIAGgNIguhtIATAAIAlBaIAlhaIATAAIg3CAQgHAPgJAHQgKAGgMAAIgJAAgAOwgUIAAiaIARAAIAAASQAHgKALgFQALgFANAAQAQAAANAIQAMAHAHANQAIAOAAAQQAAARgIANQgHANgMAIQgNAIgQAAQgMAAgLgFQgLgFgHgJIAAA6gAPWicQgJAFgFAJQgGAJAAAPQAAAPAGAJQAFAKAJAEQAJAFAKAAQALgBAJgFQAJgFAFgKQAFgJAAgNQAAgMgFgJQgFgKgJgGQgJgFgLAAQgKAAgJAEgAoVgUIAAiaIAQAAIAAASQAHgKALgFQALgFAOAAQAQAAAMAIQANAHAHANQAHAOAAAQQAAARgHANQgHANgNAIQgMAIgQAAQgNAAgLgFQgKgFgHgJIAAA6gAnvicQgJAFgGAJQgGAJAAAPQAAAPAGAJQAGAKAIAEQAJAFAKAAQAMgBAJgFQAIgFAGgKQAFgJAAgNQAAgMgFgJQgFgKgJgGQgJgFgMAAQgKAAgIAEgAURg7IAAhzIASAAIAABQIBEhSIAGAAIAAByIgRAAIAAhPIhFBSgASlhDQgNgIgIgNQgIgNAAgRQAAgRAIgNQAIgNANgHQANgIARAAQAQAAAOAIQANAHAIANQAHAOABAQQgBARgHANQgIANgNAIQgOAHgQABQgRgBgNgHgASuiaQgJAFgFAKQgFAJgBAMQABAMAFAKQAFAJAJAGQAJAFAMAAQALAAAJgFQAKgGAFgJQAFgKAAgMQAAgMgFgJQgFgKgJgFQgJgGgMAAQgMAAgJAGgANMg/QgIgEgFgHQgGgHAAgKQABgOAKgJQALgIATAAIAjAAIAAgKQAAgOgHgHQgIgHgMAAQgLAAgHAFQgIAEgHAJIgLgKQAIgMAMgGQALgGAOAAQANAAAKAFQAKAFAFAKQAGAKAAAPIAABFIgRAAIAAgOQgGAIgJAEQgKAFgNAAQgLAAgJgEgANShoQgGAEAAAIQAAAGADAEQADAEAFACQAGACAGAAQAJAAAIgEQAIgEAEgHQAFgHAAgJIAAgDIghAAQgMAAgGAEgAItg7IAAhzIASAAIAABQIBEhSIAGAAIAAByIgRAAIAAhPIhFBSgAHBhDQgNgIgIgNQgIgNAAgRQAAgRAIgNQAIgNANgHQANgIARAAQAQAAAOAIQANAHAIANQAHAOABAQQgBARgHANQgIANgNAIQgOAHgQABQgRgBgNgHgAHKiaQgJAFgFAKQgFAJgBAMQABAMAFAKQAFAJAJAGQAJAFAMAAQALAAAJgFQAKgGAFgJQAFgKAAgMQAAgMgFgJQgFgKgJgFQgJgGgMAAQgMAAgJAGgAgFg/QgJgEgFgHQgFgHAAgKQAAgOALgJQALgIARAAIAkAAIAAgKQgBgOgHgHQgHgHgNAAQgKAAgIAFQgHAEgGAJIgMgKQAIgMAMgGQALgGAOAAQAMAAAKAFQAKAFAGAKQAFAKAAAPIAABFIgQAAIAAgOQgGAIgKAEQgKAFgMAAQgLAAgIgEgAAAhoQgGAEAAAIQAAAGADAEQADAEAFACQAFACAGAAQAKAAAHgEQAIgEAFgHQAEgHABgJIAAgDIgiAAQgMAAgFAEgAiGg7IAAhzIASAAIAABQIBEhSIAGAAIAAByIgRAAIAAhPIhFBSgAl7hDQgNgIgIgNQgIgNAAgRQAAgQAIgNQAHgOANgHQANgIAQAAQAPAAAMAGQALAHAHALQAGALABAPIgBAIIgBAGIhYAAQABALAFAIQAGAIAJAFQAJAFALAAQAKgBAJgEQAIgEAHgHIAKAMQgIAJgLAGQgMAFgNAAQgRAAgOgIgAk+iAQAAgKgEgIQgFgHgHgEQgIgDgJAAQgOAAgKAJQgLAIgDAPIBHAAIAAAAgAs2g7IAAhzIASAAIAABQIBEhSIAHAAIAAByIgSAAIAAhPIhEBSgAuYhDQgOgIgHgNQgIgNAAgRQAAgQAHgNQAIgOANgHQANgIAQAAQAOAAAMAGQALAHAHALQAHALAAAPIAAAIIgBAGIhZAAQABALAGAIQAFAIAJAFQAJAFALAAQALgBAIgEQAJgEAHgHIAKAMQgIAJgMAGQgLAFgOAAQgRAAgNgIgAtbiAQAAgKgFgIQgFgHgHgEQgHgDgJAAQgPAAgKAJQgKAIgDAPIBHAAIAAAAgA3Rg8IgGgBIgDgBIAAgPIACAAIAEAAQAMAAAHgNQAHgOADgaQADgZAAgkIABgXIBeAAIAACYIgSAAIAAiIIg7AAQgCAngDAaQgDAbgFAQQgGAQgIAHQgIAHgLAAIgBAAgABPg9IgCgBIAAgPIACABIACAAQALAAAFgSQAEgSABghIABgdIBLAAIAABwIgRAAIAAhgIgqAAIAAAOQgBAcgEATQgDASgIAJQgHAJgNAAIgEAAgARNg+IAAhgIgmAAIAAgQIBdAAIAAAQIgmAAIAABggAMhg+Ig0g8IAvg0IAWAAIgwAzIA1A9gALZg+IAAhwIASAAIAABwgAF/g+IAAg0Ig2AAIAAA0IgSAAIAAhwIASAAIAAAtIA2AAIAAgtIASAAIAABwgADNg+IAAhwIASAAIAAAnIAbAAQATAAALAKQALAKABAQQgBARgLAKQgLAKgTAAgADfhNIAaAAQAMAAAGgGQAGgGAAgJQAAgKgGgGQgGgFgMAAIgaAAgAizg+IAAhLIgmAtIgHAAIgmgtIAABLIgSAAIAAhyIAGAAIA1A/IA1g/IAGAAIAABygApCg+IAAhgIg2AAIAABgIgSAAIAAhwIBaAAIAABwgAxbg+IAAhwIASAAIAABhIAuAAIAAhhIASAAIAABhIAvAAIAAhhIASAAIAABwgAyIg+IAAgsQgGADgHABQgHABgIAAQgNAAgKgFQgKgFgGgJQgGgKAAgPIAAgdIASAAIAAAdQAAAPAIAHQAIAGAOAAIAMgBQAHgBAGgCIAAg1IASAAIAABwgAUojLQgJgKAAgRIAAgHIAPAAIAAAHQAAALAFAGQAFAGAKAAQAJAAAFgGQAGgGAAgLIAAgHIAOAAIAAAHQAAARgJAKQgJAJgQABQgQgBgKgJgAJEjLQgJgKAAgRIAAgHIAPAAIAAAHQAAALAFAGQAFAGAKAAQAJAAAFgGQAGgGAAgLIAAgHIAOAAIAAAHQAAARgJAKQgJAJgQABQgQgBgKgJgAsejLQgJgKgBgRIAAgHIAPAAIAAAHQAAALAGAGQAFAGAJAAQAKAAAFgGQAFgGAAgLIAAgHIAPAAIAAAHQAAARgKAKQgJAJgQABQgQgBgJgJg");
	this.shape.setTransform(151.925,30.775);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt02, new cjs.Rectangle(0,0,386.1,58.8), null);


(lib.txt01 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AUaDuIgJgCIAAgOIAIABIAGAAQAIAAAGgEQAHgDAFgLIAFgOIguhsIATAAIAlBZIAlhZIATAAIg3B/QgGAPgKAIQgJAGgNAAIgJgBgAPIDuIgIgCIAAgOIAHABIAGAAQAIAAAHgEQAGgDAEgLIAHgOIgvhsIATAAIAlBZIAlhZIATAAIg3B/QgHAPgJAIQgKAGgMAAIgJgBgAy1DsIAAiZIARAAIAAASQAHgKALgFQALgGAOABQAQgBAMAJQANAHAGANQAIAOAAAQQAAAQgIAOQgGANgNAIQgMAHgQABQgNAAgLgGQgKgEgIgJIAAA5gAyPBlQgIAEgGAKQgGAJAAAPQAAAPAGAJQAGAKAIAEQAJAEAKAAQALAAAKgFQAIgGAFgJQAGgJAAgNQAAgMgGgJQgFgLgIgFQgKgFgLAAQgKgBgJAFgARRC+QgOgIgHgNQgIgNAAgRQAAgQAIgOQAHgNAOgHQAMgJARABQAQAAALAGQAMAGAHAMIgMAKQgHgJgIgFQgIgEgLAAQgLAAgJAFQgKAGgFAKQgFAJAAAMQAAAMAFAKQAFAJAKAFQAJAGALAAQALAAAIgFQAIgEAHgIIAMAJQgIALgLAHQgMAGgPABQgRgBgMgHgAKZC+QgNgJgHgMQgJgNABgRQgBgRAJgNQAHgNANgHQAOgJAQABQAQgBAOAJQANAHAIANQAHAOABAQQgBARgHANQgIAMgNAJQgOAHgQABQgQgBgOgHgAKiBmQgJAGgFAKQgFAJAAAMQAAAMAFAKQAFAJAJAFQAJAGAMAAQAMAAAJgGQAJgFAFgJQAFgKABgMQgBgMgFgJQgFgKgJgGQgJgFgMAAQgLAAgKAFgAHIC+QgOgIgIgNQgHgOAAgQQgBgQAIgOQAHgNAOgHQANgJAQABQAOAAAMAGQALAHAHAKQAHAMAAAPIAAAIIgCAGIhYAAQABALAFAIQAGAIAJAEQAJAGALgBQAKAAAJgEQAIgEAIgHIAJAMQgHAJgMAFQgLAGgOAAQgRgBgNgHgAIFCAQAAgKgFgHQgFgHgHgEQgHgDgJAAQgPAAgKAJQgKAIgDAOIBHAAIAAAAgADlDCQgJgEgFgHQgGgHAAgKQABgOALgJQAKgIATAAIAkAAIAAgKQgBgOgHgHQgIgIgMABQgKAAgIAEQgIAFgHAJIgLgKQAIgMAMgHQAMgFANAAQANAAAKAEQAKAGAFAKQAGAKAAAPIAABFIgRAAIAAgOQgGAHgJAFQgKAEgMABQgMgBgIgDgADqCZQgGAEAAAIQAAAGADAEQADAEAGACQAFACAGAAQAJAAAIgEQAIgFAEgHQAFgGABgJIAAgDIgiAAQgMAAgGAEgAqkDCQgJgEgFgHQgGgHABgKQAAgOALgJQAKgIATAAIAjAAIAAgKQAAgOgHgHQgIgIgMABQgLAAgHAEQgIAFgGAJIgMgKQAIgMAMgHQALgFAOAAQANAAAKAEQAKAGAGAKQAFAKAAAPIAABFIgRAAIAAgOQgFAHgKAFQgKAEgNABQgKgBgJgDgAqfCZQgGAEAAAIQAAAGADAEQADAEAFACQAGACAGAAQAKAAAHgEQAIgFAFgHQAEgGAAgJIAAgDIghAAQgMAAgGAEgAslDGIAAhzIASAAIAABQIBDhSIAHAAIAAByIgRAAIAAhPIhFBSgAwaC+QgOgIgHgNQgIgOAAgQQAAgQAIgOQAHgNANgHQANgJAQABQAPAAALAGQAMAHAGAKQAHAMAAAPIAAAIIgBAGIhZAAQABALAGAIQAGAIAJAEQAIAGAMgBQAKAAAJgEQAIgEAHgHIAKAMQgIAJgLAFQgMAGgNAAQgRgBgOgHgAvdCAQAAgKgEgHQgGgHgHgEQgHgDgJAAQgOAAgKAJQgLAIgDAOIBHAAIAAAAgA27C+QgNgIgIgNQgIgNAAgRQAAgQAIgOQAIgNANgHQANgJAQABQAQAAALAGQAMAGAIAMIgNAKQgGgJgIgFQgJgEgKAAQgMAAgJAFQgJAGgGAKQgFAJAAAMQAAAMAFAKQAGAJAJAFQAJAGAMAAQALAAAHgFQAJgEAGgIIAMAJQgHALgMAHQgMAGgPABQgQgBgNgHgASgDEIgDgBIAAgPIACABIADAAQALgBAEgRQAEgSABghIABgdIBMAAIAABwIgSAAIAAhgIgqAAIAAANQgBAdgDATQgEARgIAKQgHAJgNAAIgDAAgApPDEIgDgBIAAgPIACABIADAAQALgBAEgRQAFgSABghIAAgdIBMAAIAABwIgSAAIAAhgIgpAAIAAANQgBAdgEATQgDARgIAKQgHAJgNAAIgEAAgAWNDDIAAhwIBMAAIAAAQIg6AAIAABggANqDDIAAhMIgmAuIgHAAIgmguIAABMIgSAAIAAhyIAHAAIA1A/IA1g/IAFAAIAABygAJBDDIAAhgIgmAAIAAgQIBdAAIAAAQIgmAAIAABggAGRDDIg0g8IAug0IAXAAIgwAzIA1A9gAFJDDIAAhwIASAAIAABwgACuDDIAAhgIg1AAIAABgIgSAAIAAhwIBZAAIAABwgAAFDDIAAhMIglAuIgHAAIgmguIAABMIgSAAIAAhyIAGAAIA1A/IA0g/IAHAAIAABygAiLDDIAAhwIASAAIAABwgAjyDDIAAhwIASAAIAAAmIAaAAQAUABALAJQALALABAQQgBARgLAKQgLAKgUAAgAjgC0IAaAAQALgBAHgFQAGgGAAgKQAAgJgGgGQgGgFgMgBIgaAAgAkfDDIAAg0Ig3AAIAAA0IgSAAIAAhwIASAAIAAAsIA3AAIAAgsIASAAIAABwgAnRDDIAAhwIASAAIAAAmIAaAAQAUABALAKQALAKABAQQgBARgLAKQgLAKgUAAgAm/C0IAZAAQAMAAAHgHQAGgFAAgKQAAgJgHgGQgFgFgNgBIgZAAgAtSDDIAAhMIgnAuIgGAAIgnguIAABMIgSAAIAAhyIAHAAIA1A/IA1g/IAGAAIAABygAziDDIAAhgIg1AAIAABgIgSAAIAAhwIBZAAIAABwgAO8g8IAAhzIASAAIAABPIBEhRIAHAAIAAByIgSAAIAAhPIhFBSgANQhFQgNgHgIgNQgHgOgBgQQABgRAHgNQAIgNANgHQANgJARABQAQgBAOAJQANAHAIANQAHAOABAQQgBAQgHAOQgIANgNAHQgOAIgQABQgQgBgOgIgANZicQgJAGgFAJQgFAKgBAMQABAMAFAKQAFAJAJAGQAKAFALAAQALAAAKgFQAJgGAFgJQAGgKgBgMQABgMgGgKQgFgJgJgGQgJgFgMAAQgMAAgJAFgALQhFQgNgHgHgOQgIgPAAgTIAAgTQAAgSADgOQADgOAGgLQAIgKAOgIQANgIAXgDIAXgFIAOgEIAAARQgFADgKACIgUADQgUADgKAGQgMAFgEAJQgFAIgCAKQgBAKgBALQAIgKALgHQALgFAOgBQAPABANAHQAMAIAIANQAHANABAPQgBAQgIANQgHANgNAGQgOAIgQABQgRgBgNgIgALaiXQgJAFgFAIQgFAJgBAMQABALAFAJQAFAJAJAGQAJAFAMAAQAKAAAKgFQAIgGAGgJQAFgJAAgLQAAgMgFgJQgGgIgIgFQgKgGgKAAQgMAAgJAGgAJOhFQgNgHgIgNQgHgOAAgQQAAgRAHgNQAIgNAOgHQAMgJARABQARgBANAJQANAHAIANQAIAOAAAQQAAAQgIAOQgIANgNAHQgNAIgRABQgRgBgNgIgAJYicQgKAGgFAJQgFAKAAAMQAAAMAFAKQAFAJAJAGQAKAFALAAQALAAAJgFQAKgGAFgJQAGgKAAgMQAAgMgGgKQgFgJgJgGQgJgFgMAAQgMAAgIAFgAHchFQgNgHgIgNQgIgOAAgQQAAgQAIgOQAIgNANgHQANgJAQABQAQAAALAGQAMAHAIALIgNAKQgGgIgIgGQgJgEgKAAQgMAAgJAFQgJAGgGAJQgFAKAAAMQAAAMAFAKQAGAJAJAGQAJAFAMAAQALAAAHgEQAJgFAGgJIAMAKQgHALgMAHQgMAGgPABQgQAAgNgJgAgvhFQgNgHgHgOQgIgPABgTIAAgTQgBgSADgOQADgOAGgLQAIgKANgIQAOgIAWgDIAXgFIAOgEIAAARQgFADgKACIgTADQgUADgLAGQgKAFgFAJQgGAIgBAKQgBAKAAALQAHgKALgHQALgFANgBQAPABANAHQANAIAHANQAHANABAPQgBAQgHANQgIANgOAGQgMAIgQABQgSgBgMgIgAgliXQgJAFgFAIQgGAJABAMQgBALAGAJQAFAJAJAGQAJAFALAAQAMAAAHgFQAJgGAGgJQAFgJAAgLQAAgMgFgJQgGgIgJgFQgHgGgMAAQgLAAgJAGgAjchFQgOgHgHgNQgIgOAAgQQAAgQAHgOQAIgNANgHQANgJAQABQAOAAANAGQAKAHAIALQAGALAAAPIAAAIIgBAFIhZAAQACALAFAJQAFAIAKAFQAIAEALAAQALAAAIgEQAJgEAHgHIAKAMQgIAJgLAFQgMAGgOAAQgQAAgOgJgAifiCQAAgJgEgIQgFgHgHgEQgIgEgJABQgOgBgLAKQgKAIgDAOIBHAAIAAAAgAldhFQgNgHgHgOQgHgPAAgTIAAgTQgBgSAEgOQACgOAHgLQAIgKANgIQAOgIAWgDIAYgFIANgEIAAARQgFADgJACIgVADQgTADgLAGQgLAFgFAJQgFAIgCAKQgBAKAAALQAHgKALgHQALgFAOgBQAQABAMAHQANAIAHANQAIANAAAPQgBAQgHANQgIANgNAGQgNAIgQABQgSgBgNgIgAlTiXQgIAFgFAIQgGAJAAAMQAAALAGAJQAFAJAIAGQAJAFAMAAQALAAAJgFQAJgGAGgJQAEgJAAgLQAAgMgEgJQgGgIgJgFQgJgGgLAAQgMAAgJAGgAnVhFQgNgHgIgNQgIgOAAgQQAAgQAIgOQAHgNANgHQANgJAQABQAPAAAMAGQAKAHAHALQAHALABAPIgBAIIgBAFIhYAAQABALAFAJQAFAIAJAFQAKAEAKAAQALAAAIgEQAJgEAHgHIAKAMQgIAJgMAFQgLAGgOAAQgRAAgNgJgAmYiCQAAgJgFgIQgFgHgGgEQgIgEgJABQgPgBgKAKQgKAIgDAOIBHAAIAAAAgApIhFQgNgHgHgNQgJgOAAgQQAAgQAJgOQAHgNANgHQAOgJAQABQAPAAAMAGQAMAHAIALIgOAKQgGgIgHgGQgJgEgKAAQgMAAgKAFQgJAGgFAJQgFAKAAAMQAAAMAFAKQAFAJAJAGQAKAFAMAAQAKAAAIgEQAJgFAFgJIANAKQgHALgMAHQgMAGgPABQgQAAgOgJgAvWhFQgNgHgHgNQgJgOABgQQgBgRAJgNQAHgNAOgHQANgJAQABQAQgBAOAJQANAHAIANQAHAOABAQQgBAQgHAOQgIANgNAHQgOAIgQABQgQgBgOgIgAvNicQgJAGgFAJQgFAKAAAMQAAAMAFAKQAFAJAJAGQAKAFALAAQAMAAAJgFQAJgGAFgJQAFgKABgMQgBgMgFgKQgFgJgJgGQgJgFgMAAQgLAAgKAFgAyyhCQgLgGgHgKIAMgLQAFAHAHAFQAHAEALAAQAMAAAHgFQAGgFAAgKQAAgIgGgEQgGgGgNABIgLAAIAAgQIALAAQALAAAEgEQAFgFAAgHQAAgHgFgEQgFgEgKAAQgKAAgHADQgGAFgFAFIgMgKQAGgIAKgGQAKgFAOAAQARgBAKAJQAKAHAAAPQABAHgEAHQgDAGgHAEQAKAEAEAHQAFAIAAAJQAAAQgLAJQgMAJgTABQgOgBgLgFgA0nhFQgNgHgIgNQgHgOgBgQQABgRAHgNQAIgNAOgHQANgJAQABQARgBANAJQANAHAIANQAIAOAAAQQAAAQgIAOQgIANgNAHQgNAIgRABQgQgBgOgIgA0dicQgKAGgFAJQgFAKgBAMQABAMAFAKQAFAJAJAGQAJAFAMAAQALAAAJgFQAKgGAFgJQAGgKgBgMQABgMgGgKQgFgJgJgGQgJgFgMAAQgMAAgIAFgAt5g+IgCgBIAAgPIACAAIADAAQAKAAAFgSQAEgSABggIABgdIBLAAIAABwIgRAAIAAhgIgpAAIgBAOQgBAcgEATQgDASgHAJQgIAJgNAAIgEAAgAEpg/IAAhwIASAAIAAAnIAaAAQAUAAALAKQALAKABAQQgBARgLAKQgLAKgUAAgAE7hPIAaAAQALABAHgHQAGgFAAgJQAAgKgGgGQgGgGgMAAIgaAAgADmg/IAAhgIgnAAIAAgQIBeAAIAAAQIgmAAIAABggACig/IAAhwIASAAIAABwgAA8g/IAAhwIASAAIAAAnIAaAAQATAAALAKQAMAJAAARQAAARgMAKQgLAKgTAAgABOhPIAZAAQAMAAAHgFQAFgGAAgJQABgKgHgGQgGgGgMAAIgZAAgAr7g/IAAhwIASAAIAAAnIAbAAQATAAAMAKQAKAKABAQQgBARgKAKQgMAKgTAAgArphPIAaAAQAMABAGgHQAHgFAAgJQgBgKgGgGQgGgGgMAAIgaAAgAxcg/IAAhwIAuAAQARAAAKAIQAJAIABAOQAAAGgDAGQgDAGgGADQAJAEAHAGQAFAHAAAKQAAAPgLAKQgKAIgSABgAxKhPIAiAAQALAAAGgFQAFgFAAgIQAAgIgFgEQgHgEgKgBIgiAAgAxKiCIAdAAQAJAAAFgDQAFgEgBgHQABgHgFgFQgFgDgJAAIgdAAgA1qg/IAAiIIhSAAIAACIIgSAAIAAiYIB2AAIAACYgAPTjNQgJgKAAgQIAAgHIAPAAIAAAHQAAALAFAGQAGAGAJAAQAKAAAEgGQAGgGAAgLIAAgHIAPAAIAAAHQAAAQgKAKQgJAKgQAAQgQAAgKgKg");
	this.shape.setTransform(152.7,30.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt01, new cjs.Rectangle(0,0,386.1,58.8), null);


(lib.LOGO = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AxGDXQhNgFgzguQgLgKgEgRQgXgNgLgRQgFgJADgOIABgGQgPgKgEgHQgIgOALgRQgIgJgCgFQgCgIAAgJQACgOANgOQAVgZA8gTQAYgJAXgFIAngJIA6gJQAjgGAWgIQhNgNhJANQhMAPg+ApIAHgQQA+gpA/gNQBMgQBiARQAMgHADgLQgxgShKACQgkABgwALQg1ANgfARIANgQQAZgOAwgNQA1gOAoAAQAggBAVADQAWADAlAJQgEgIgZgKQgmgRg4ABQg+ABg1AXQARgLAOgGQAvgWBAACQAfAAAeALQAhALAUAUQAHAIACAIQAgAQALASQAEALgBAKQALAHAHAJQAGAJAAAHQADAPgIAKQAGACAEAGQAEAGAAAFQAGAWgbAWQgMALgZALQgXAMgXAFQgkAJgvAIIhGAMQAsAKApAAQA4AAA8gVQAfgKAUgKIgEAKQgnAXg7ANQgzALgigBQg5gDgugOQgRAEgMAGQAiAOAgAHQAZAFAkADQAgACAvgHQAxgIArgPIgGAJQgXAMgoAKQgnAKgZABQg8ADgtgKQghgGgtgTQgGAFgBAHQBHAlBIAEQBEADBQgYIgJAJQhPAfhKgEQg8gEg7gcIgHgDQAHALAgASQAoAVAnADQAeACAigEQAhgEAWgJIgRAJQgpAUgwAAIgPgBgAzUByIAFgJIgSgKQAAAJANAKgAzXBOIAYANQAHgEANgFIgggNIgMAJgAuFgXQgXARg2AOQgqALg6AJQhBALgZAGQgTAFgQAHQASAJASAGQAlgKAkgGIBWgQQA2gMAggPQArgUgPgWgAzzA3QACAEAFADIAIgGQgLgGgFgEQgCAEADAFgAurg7QgWAKgqALQgLADgxAJQg2AJgjAIQhJAPgdAXIAUAMQATgMAfgHQAggJBHgMQAfgDAmgJQAsgKAZgJQAUgHALgJQgBgCgMgGIgNgFIgBAAgAwdhPQhLAIhAATQhrAfAaAhQAEgEALgIQAXgOAkgKQAlgLBJgNQBNgOAkgKQgYgGgNgCIgRgBQgLAAgMACgAuVhHQAQAHAEADQAGgLgOgLQgEAGgIAGgAvlhhQALACAOAFIAYAGQADABAHgGQAHgFACgDQgQgHgagIQgLAKgPAFgAu8h9IAgAKQgBgKgVgOQgBADgJALgARIBVIAAgMIAMAAQAHAAAFgCQAEgDAEgIIAFgLIgmhUIAQAAIAdBFIAehFIAPgBIgtBkQgIAWgVAAIgPgBgAKHBVIAAh4IAOAAIAAAOQAGgIAIgEQAJgEALAAIAAgBQATAAAMAOQANAOAAASQAAATgNAOQgMANgTAAQgJAAgKgEQgIgDgGgHIAAAtgAKegQQgJAJABAPQgBAQAJAIQAKAJAMAAIAAAAQAOAAAJgJQAJgJAAgPQAAgOgJgJQgJgJgOAAQgMAAgKAIgAlaBVIAAh6IAWAAIAAAMQAKgOAUAAIAAAAQATAAAMAOQANANAAATQAAAUgNAOQgMANgTAAQgSAAgJgLIAAAqgAk8gLQgGAHAAALQAAALAGAHQAHAHAJAAIABAAQAJAAAHgHQAHgIAAgKQAAgKgHgHQgGgHgLAAQgJAAgHAGgAosAmIAOgPQAJAKAQAAQAQAAAAgJQAAgEgEgCQgCgDgHAAIgRAAIAAgRIAQAAQAGAAABgCQADgCAAgEQAAgIgMAAQgRAAgHAKIgOgPQANgQAZAAQAQAAALAHQAKAIAAAMQAAALgKAHIAAABQANAHAAANQABANgMAHQgLAIgSAAQgaAAgNgRgAPlA2IAAhZIAPAAIAAA8IA5g+IAGAAIAABZIgPAAIAAg9Ig5A/gAB7AvQgIgIAAgMQAAgMAJgHQAKgHAPAAIAXAAIAAgDQAAgHgEgEQgFgFgIAAQgMAAgMANIgMgPQAPgTAYAAQASAAAKALQALAJAAATIAAA0IgXAAIAAgJQgKALgRAAQgPAAgJgHgACMAaQAAAFAEADQAEADAGAAIAAgBQAHAAAGgFQAFgEAAgIIAAgBIgTAAQgNAAAAAIgAjeApQgOgNAAgVQABgTAOgNQANgOAVAAQAUAAAOAOQAOAOAAATQAAATgOAOQgOANgUAAQgVAAgOgNgAjMgJQgHAHAAAKQAAALAHAGQAGAHALAAQAJAAAHgHQAHgIAAgJQAAgKgHgHQgGgHgKAAIAAAAQgLAAgGAHgAqGAvQgJgIAAgMQAAgLAJgIQAKgHAPAAIAXAAIAAgDQAAgHgFgEQgEgFgIAAQgLAAgNANIgNgPQAQgTAYAAQASAAALALQAKAJAAATIAAA0IgXAAIAAgJQgKALgSAAQgOAAgIgHgAp2AaQAAAFAEADQAEADAFAAIAAgBQAJAAAEgFQAGgEAAgIIAAgBIgTAAQgNAAAAAIgAMDApQgNgNAAgUQAAgSAMgOQAOgNATAAQARAAAMALQAMALAAARIgBgBIgBALIhGAAQACAMAIAJQAKAIANAAQAPAAAMgMIAJAKQgOAPgWAAQgVAAgNgNgAMQgSQgKAHgCALIA6AAQgCgLgGgHQgIgHgLAAQgMAAgHAHgAATAoQgOgPAAgYIAAgHQAAggAOgRQANgQAcgHIAcgHIAGAVIgbAHQgRAEgJAIQgJAIgBAOQALgLAQAAIAAgBQASAAAMANQANANAAASQAAASgNAOQgOANgVAAQgVAAgNgOgAAlgGQgHAGAAAJQAAAJAHAHQAGAGAKAAQAKAAAGgGQAGgHABgJQgBgJgGgGQgHgHgJAAQgJAAgHAHgArnA0IAAh3IBNAAIAAAXIg0AAIAABggAUGA0IAAg7IgeAjIgFAAIgfgjIAAA7IgOAAIAAhZIAFAAIArAwIAqgwIAFAAIAABZgAO2A0IAAg7IgeAjIgGAAIgegjIAAA7IgPAAIAAhZIAGAAIAqAwIAqgwIAFAAIAABZgAJYA0IAAhqIg/AAIAABqIgOAAIAAh3IBcAAIAAB3gAG1AwQgFgFABgGQgBgGAFgFQAFgEAFAAQAHAAAEAEQAFAFAAAGQgBAGgDAFQgEAEgIAAQgGAAgEgEgAGKA0IgmgwIAAAwIgZAAIAAhZIAZAAIAAAoIAjgoIAcAAIgjAoIAmAxgAEZA0IAAgkIgiAAIAAAkIgaAAIAAhZIAaAAIAAAhIAiAAIAAghIAYAAIAABZgAgpA0IAAgrIgXAYIgIAAIgWgYIAAArIgZAAIAAhbIAJAAIArAuIArguIAIAAIAABbgAmNA0IAAhEIghAAIAABEIgZAAIAAhZIBSAAIAABZg");
	this.shape.setTransform(0.1,0.5438);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGO, new cjs.Rectangle(-130,-21,260.2,43.1), null);


(lib.legal_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal_1, new cjs.Rectangle(0,0,441,71), null);


(lib.girl_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.girl();
	this.instance.parent = this;
	this.instance.setTransform(-51,-50,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.girl_1, new cjs.Rectangle(-51,-50,101.5,99), null);


(lib.CARD = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.KARD();
	this.instance.parent = this;
	this.instance.setTransform(-64,-41,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.CARD, new cjs.Rectangle(-64,-41,130,90), null);


(lib.btn_main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Оформить_карту copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#562737").s().p("ALrBsIgJgCIAAgPIAIABIAFAAQAJAAAGgDQAGgEAFgLIAGgNIguhsIATAAIAlBZIAlhZIASAAIg2B/QgHAPgKAHQgJAGgMAAIgJAAgAIGBqIAAiZIAQAAIAAASQAIgKAKgFQALgFAOAAQAQAAAMAIQANAHAHANQAHAOAAAPQAAARgHANQgHANgNAIQgMAIgQAAQgNAAgLgFQgKgFgHgJIAAA6gAIsgdQgJAFgFAJQgHAJAAAOQAAAPAHAJQAFAKAIAEQAKAFAKAAQALgBAJgFQAIgFAGgKQAFgJAAgNQAAgLgFgJQgFgKgJgGQgJgFgLAAQgKAAgJAEgAl4BqIAAiZIARAAIAAASQAGgKAMgFQAKgFAOAAQAQAAANAIQAMAHAHANQAIAOAAAPQAAARgIANQgHANgMAIQgNAIgQAAQgMAAgLgFQgLgFgHgJIAAA6gAlSgdQgJAFgGAJQgFAJAAAOQAAAPAFAJQAGAKAIAEQAJAFAKAAQAMgBAJgFQAJgFAFgKQAFgJAAgNQAAgLgFgJQgFgKgJgGQgJgFgMAAQgKAAgIAEgApkBqIAAgnQgTgBgOgHQgPgHgIgNQgHgNAAgSQgBgQAJgNQAIgNAOgHQAPgHASgBIAAg6IASAAIAAA6QASABAOAHQAOAHAJANQAHANABARQgBARgHANQgJANgOAHQgOAHgSABIAAAngApTAzQAVgBAMgLQANgLAAgUQAAgSgNgLQgMgLgVgBgAqFgVQgMALAAATQAAATAMALQAMALAVABIAAhUQgVABgMALgAGeA/QgIgEgGgHQgFgHAAgKQABgOAKgJQALgIASAAIAkAAIAAgJQAAgOgIgHQgHgHgMAAQgLAAgIAFQgIAEgGAJIgMgKQAIgMAMgGQAMgGAOAAQANAAAKAFQAJAFAGAKQAFAKABAPIAABEIgRAAIAAgOQgGAIgKAEQgJAFgNAAQgLAAgJgEgAGjAWQgFAEAAAIQAAAGADAEQACAEAGACQAGACAFAAQAKAAAHgEQAJgEAEgHQAEgHABgJIAAgDIgiAAQgMAAgGAEgAhYBDIAAhyIASAAIAABPIBDhRIAGAAIAABxIgRAAIAAhOIhEBRgAnoA7QgNgIgIgNQgHgNgBgRQABgQAHgNQAIgNANgHQANgIARAAQAQAAAOAIQANAHAIANQAHAOABAPQgBARgHANQgIANgNAIQgOAHgQABQgQgBgOgHgAnfgbQgJAFgFAKQgFAJgBALQABAMAFAKQAFAJAJAGQAKAFALAAQALAAAJgFQAKgGAFgJQAGgKgBgMQABgLgGgJQgFgKgJgFQgJgGgMAAQgMAAgJAGgAsoA4QgTgKgKgSQgLgRAAgWQAAgWALgSQAKgSATgKQARgKAWAAQAWAAASAKQARAKAMASQAKASAAAWQAAAWgKARQgMASgRAKQgSALgWAAQgWAAgRgLgAsfhAQgOAIgIANQgIAOAAASQAAARAIAOQAIAOAOAIQANAIARAAQASAAANgIQANgIAIgOQAJgOAAgRQAAgSgJgNQgIgOgNgIQgNgJgSAAQgRAAgNAJgAKmBAIAAhfIglAAIAAgQIBcAAIAAAQIglAAIAABfgAFuBAIgzg8IAvgzIAWAAIgwAyIA1A9gAEmBAIAAhvIASAAIAABvgACABAIAAhvIATAAIAAAnIAaAAQAUAAAKAJQALAKABAQQgBARgLAKQgKAKgUAAgACTAxIAZAAQAMAAAHgGQAFgGABgJQAAgKgHgGQgGgFgMAAIgZAAgAA5BAIAAhfIgmAAIAAgQIBdAAIAAAQIgmAAIAABfgAiKBAIAAhKIgmAsIgHAAIgmgsIAABKIgSAAIAAhxIAHAAIA1A+IA1g+IAGAAIAABxg");
	this.shape.setTransform(-1.15,-2.175);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CECECE").s().rr(-109.05,-23.75,218.1,47.5,2);
	this.shape_1.setTransform(0.025,-3.2638,1,1.1253);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.btn, new cjs.Rectangle(-109,-30,218.1,53.5), null);


(lib.BGSOLID = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.BGSOLID, new cjs.Rectangle(0,0,728,90), null);


(lib.BGRED = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.BGgirlRED();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.BGRED, new cjs.Rectangle(0,0,728,90), null);


(lib.BGMAIN = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.BG();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.BGMAIN, new cjs.Rectangle(0,0,728,90), null);


(lib.TXT3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt01
	this.instance = new lib.txt03();
	this.instance.parent = this;
	this.instance.setTransform(190,-52.6,1,1,0,0,0,193,29.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:22.4,alpha:1},19,cjs.Ease.quadInOut).wait(50).to({y:97.4,alpha:0},20,cjs.Ease.quadInOut).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-73,315.6,195.5);


(lib.TXT2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt01
	this.instance = new lib.txt02();
	this.instance.parent = this;
	this.instance.setTransform(190,-52.6,1,1,0,0,0,193,29.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:22.4,alpha:1},19,cjs.Ease.quadInOut).wait(50).to({y:97.4,alpha:0},20,cjs.Ease.quadInOut).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-75,299.9,197.6);


(lib.TXT1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt01
	this.instance = new lib.txt01();
	this.instance.parent = this;
	this.instance.setTransform(190,-52.6,1,1,0,0,0,193,29.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:22.4,alpha:1},19,cjs.Ease.quadOut).wait(50).to({y:97.4,alpha:0},20,cjs.Ease.quadInOut).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-75,299.4,197.8);


(lib.TXT = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt03
	this.instance = new lib.TXT3("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(149.7,23.9,1,1,0,0,0,149.7,23.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(138).to({_off:false},0).to({_off:true},90).wait(1));

	// txt02
	this.instance_1 = new lib.TXT2("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(149.7,23.9,1,1,0,0,0,149.7,23.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(69).to({_off:false},0).to({_off:true},90).wait(70));

	// txt01
	this.instance_2 = new lib.TXT1("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(149.7,23.9,1,1,0,0,0,149.7,23.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({_off:true},90).wait(139));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1,-75,316.6,197.8);


(lib.legal_mov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal_1();
	this.instance.parent = this;
	this.instance.setTransform(220.5,35.5,1,1,0,0,0,220.5,35.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},19).wait(60).to({alpha:0},20).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,441,71);


(lib.CARD_MOV = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// CARD2
	this.instance = new lib.CARD();
	this.instance.parent = this;
	this.instance.setTransform(0,-95.55);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:0},31,cjs.Ease.cubicInOut).wait(1).to({x:5,y:-5},10,cjs.Ease.quintInOut).wait(13).to({y:84.95},20,cjs.Ease.quadInOut).wait(3));

	// CARD1
	this.instance_1 = new lib.CARD();
	this.instance_1.parent = this;
	this.instance_1.setTransform(0,-95.55);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:0},31,cjs.Ease.cubicInOut).wait(1).to({x:-4,y:5},10,cjs.Ease.quintInOut).wait(12).to({y:94.95},20,cjs.Ease.quadInOut).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68,-136.5,139,280.5);


(lib.BTN_MOV = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.btn();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},29,cjs.Ease.quadOut).wait(10).to({alpha:0},20,cjs.Ease.quadIn).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-109,-30,218.1,53.5);


(lib.movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// LEGAL
	this.instance = new lib.legal_mov("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(495.5,45.5,1,1,0,0,0,220.5,35.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(362).to({_off:false},0).to({_off:true},100).wait(7));

	// GIRL
	this.instance_1 = new lib.girl_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(659,123);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({y:53,alpha:1},19,cjs.Ease.quadInOut).wait(313).to({y:133,alpha:0},20,cjs.Ease.quadIn).wait(108));

	// BTN
	this.instance_2 = new lib.BTN_MOV("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(496,45,0.69,0.69);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(234).to({_off:false},0).wait(29).to({mode:"single",startPosition:29},0).wait(78).to({mode:"synched",startPosition:39,loop:false},0).to({_off:true},21).wait(107));

	// CARD
	this.instance_3 = new lib.CARD_MOV("synched",0,false);
	this.instance_3.parent = this;
	this.instance_3.setTransform(330,46);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(215).to({_off:false},0).wait(44).to({mode:"single",startPosition:44},0).wait(82).to({mode:"synched",startPosition:54,loop:false},0).to({_off:true},21).wait(107));

	// MASK (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Az8TdQoEoEAArZQAArYIEoEQIEoELZAAQLYAAIEIEQIEIEAALYQAALZoEIEQoEIErYAAQrZAAoEoEg");
	var mask_graphics_1 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_2 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_3 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_4 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_5 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_6 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_7 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_8 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_9 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_10 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_11 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_12 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_13 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_14 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_15 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_16 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_17 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_18 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_19 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_441 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_442 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_443 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_444 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_445 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_446 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_447 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_448 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_449 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_450 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_451 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_452 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_453 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_454 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_455 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_456 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_457 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_458 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_459 = new cjs.Graphics().p("AzcTdQoEoEAArZQAArYIEoEQIEoELYAAQLZAAIEIEQIEIEAALYQAALZoEIEQoEIErZAAQrYAAoEoEg");
	var mask_graphics_460 = new cjs.Graphics().p("AzpTdQoEoEAArZQAArYIEoEQIEoELZAAQLYAAIEIEQIEIEAALYQAALZoEIEQoEIErYAAQrZAAoEoEg");
	var mask_graphics_461 = new cjs.Graphics().p("AzvTdQoFoEAArZQAArYIFoEQIDoELZAAQLYAAIEIEQIFIEAALYQAALZoFIEQoEIErYAAQrZAAoDoEg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-179.3,y:46}).wait(1).to({graphics:mask_graphics_1,x:-155.5956,y:46}).wait(1).to({graphics:mask_graphics_2,x:-130.1454,y:46}).wait(1).to({graphics:mask_graphics_3,x:-106.1496,y:46}).wait(1).to({graphics:mask_graphics_4,x:-83.608,y:46}).wait(1).to({graphics:mask_graphics_5,x:-62.5208,y:46}).wait(1).to({graphics:mask_graphics_6,x:-42.8878,y:46}).wait(1).to({graphics:mask_graphics_7,x:-24.7091,y:46}).wait(1).to({graphics:mask_graphics_8,x:-7.9848,y:46}).wait(1).to({graphics:mask_graphics_9,x:7.2853,y:46}).wait(1).to({graphics:mask_graphics_10,x:21.1011,y:46}).wait(1).to({graphics:mask_graphics_11,x:33.4626,y:46}).wait(1).to({graphics:mask_graphics_12,x:44.3698,y:46}).wait(1).to({graphics:mask_graphics_13,x:53.8227,y:46}).wait(1).to({graphics:mask_graphics_14,x:61.8213,y:46}).wait(1).to({graphics:mask_graphics_15,x:68.3657,y:46}).wait(1).to({graphics:mask_graphics_16,x:73.4557,y:46}).wait(1).to({graphics:mask_graphics_17,x:77.0914,y:46}).wait(1).to({graphics:mask_graphics_18,x:79.2729,y:46}).wait(1).to({graphics:mask_graphics_19,x:80,y:46}).wait(422).to({graphics:mask_graphics_441,x:80,y:46}).wait(1).to({graphics:mask_graphics_442,x:78.7,y:46}).wait(1).to({graphics:mask_graphics_443,x:74.8,y:46}).wait(1).to({graphics:mask_graphics_444,x:68.3,y:46}).wait(1).to({graphics:mask_graphics_445,x:59.2,y:46}).wait(1).to({graphics:mask_graphics_446,x:47.5,y:46}).wait(1).to({graphics:mask_graphics_447,x:33.2,y:46}).wait(1).to({graphics:mask_graphics_448,x:16.3,y:46}).wait(1).to({graphics:mask_graphics_449,x:-3.2,y:46}).wait(1).to({graphics:mask_graphics_450,x:-25.3,y:46}).wait(1).to({graphics:mask_graphics_451,x:-50,y:46}).wait(1).to({graphics:mask_graphics_452,x:-74.7,y:46}).wait(1).to({graphics:mask_graphics_453,x:-96.8,y:46}).wait(1).to({graphics:mask_graphics_454,x:-116.3,y:46}).wait(1).to({graphics:mask_graphics_455,x:-133.2,y:46}).wait(1).to({graphics:mask_graphics_456,x:-147.5,y:46}).wait(1).to({graphics:mask_graphics_457,x:-159.2,y:46}).wait(1).to({graphics:mask_graphics_458,x:-168.3,y:46}).wait(1).to({graphics:mask_graphics_459,x:-174.8,y:46}).wait(1).to({graphics:mask_graphics_460,x:-177.4,y:46}).wait(1).to({graphics:mask_graphics_461,x:-178.05,y:46}).wait(1).to({graphics:null,x:0,y:0}).wait(7));

	// LOGO
	this.instance_4 = new lib.LOGO();
	this.instance_4.parent = this;
	this.instance_4.setTransform(127.1,46.45,0.7827,0.7827,0,0,0,0.1,0.6);

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({_off:true},462).wait(7));

	// BGRED
	this.instance_5 = new lib.BGRED();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364,45,1,1,0,0,0,364,45);

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({_off:true},462).wait(7));

	// TXT
	this.instance_6 = new lib.TXT("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(430.7,45.9,1,1,0,0,0,149.7,23.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(9).to({_off:false},0).to({_off:true},230).wait(230));

	// BG
	this.instance_7 = new lib.BGMAIN();
	this.instance_7.parent = this;
	this.instance_7.setTransform(364,45,1,1,0,0,0,364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(469));

	// BGSOLID
	this.instance_8 = new lib.BGSOLID();
	this.instance_8.parent = this;
	this.instance_8.setTransform(364,45,1,1,0,0,0,364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(469));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2484,-90.5,4040,280.5);


// stage content:
(lib.gpb_prem_girl_728x90_review = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// movie
	this.instance = new lib.movie();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// button
	this.instance_1 = new lib.btn_main();
	this.instance_1.parent = this;
	this.instance_1.setTransform(364,45,3.0333,0.225);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn_main(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape_1.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(5.4,-85.1,723.6,307.2);
// library properties:
lib.properties = {
	id: 'F66FE7A2AC3D5941AE55BF9D2D3ACE18',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F66FE7A2AC3D5941AE55BF9D2D3ACE18'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;