(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"gzprmbnk_save_300x600_review_atlas_", frames: [[522,0,178,444],[0,0,520,726]]}
];


// symbols:



(lib.bondarchuk = function() {
	this.initialize(ss["gzprmbnk_save_300x600_review_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.legal = function() {
	this.initialize(ss["gzprmbnk_save_300x600_review_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt0102 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ArYElIAAjYIAoAAIAAAUQAIgLANgGQANgGARAAQAWAAASALQARAKAKATQAKASAAAZQAAAYgKATQgKASgRALQgSALgWAAQgPAAgMgFQgMgFgJgJIAABIgAqZB1QgJAFgFAKQgGAJAAAQQAAAPAGAKQAFAJAJAFQAKAFAKAAQALAAAJgGQAKgFAFgKQAGgKAAgNQAAgOgGgKQgFgJgKgFQgJgGgLAAQgKAAgKAEgAjYEZIAAgtIh9AAIAAifIArAAIAAB7IA2AAIAAh7IArAAIAAB7IAbAAIAABRgAhzDlQgTgLgLgSQgMgUAAgXQAAgXALgUQALgSATgLQASgKAYgBQAWAAARAKQARAJAJASQAJAQAAAVIAAANIgCAKIhvAAQAEAQALAHQAMAJARAAQANAAALgFQALgEAJgHIASAdQgNAMgQAFQgQAHgSAAQgZAAgUgLgAgpCNQgBgKgEgIQgFgGgIgEQgHgEgJAAQgOAAgKAIQgKAJgEAPIBIAAIAAAAgAGFDlQgTgMgLgSQgLgTAAgXQAAgYALgTQALgSATgLQAUgKAYgBQAYABATAKQATALALATQALASABAYQgBAXgLASQgLAUgTALQgUALgYgBQgYABgTgLgAGTB9QgLANAAATQAAATALAMQALAMATAAQASgBALgMQALgLABgTQgBgTgLgNQgLgMgSABQgTgBgLAMgAnzDlQgTgMgLgSQgLgTAAgXQAAgYALgTQALgSATgLQAUgKAYgBQAYABATAKQATALALATQALASABAYQgBAXgLASQgLAUgTALQgUALgYgBQgYABgTgLgAnlB9QgLANAAATQAAATALAMQALAMATAAQASgBALgMQALgLABgTQgBgTgLgNQgLgMgSABQgTgBgLAMgAKpDsIAAhMIgmArIgPAAIgmgrIAABMIgrAAIAAiiIAOAAIBLBTIBKhTIAOAAIAACigAD0DsIAAh6IgxAAIAAglICNAAIAAAlIgxAAIAAB6gACDDsIAAg/Ig7AAIAAA/IgrAAIAAifIArAAIAAA6IA7AAIAAg6IAqAAIAACfgAsqDsIAAh6Ig4AAIAAB6IgrAAIAAifICOAAIAACfgANBDFIAsgwIgsgxIAcgYIA+BDIAAAMIg+BDgALwDFIArgwIgrgxIAbgYIA+BDIAAAMIg+BDgAlTAMIAAjXIAnAAIAAAUQAJgMANgGQANgGAQAAQAXAAARALQARALAKASQAKATAAAXQAAAZgKASQgKATgRALQgRALgXAAQgPAAgMgFQgMgFgIgJIAABIgAkUikQgJAFgGAKQgGAJAAAPQAAAQAGAJQAGAKAJAFQAJAFAKgBQAMABAJgGQAJgFAGgKQAFgKAAgNQAAgNgFgKQgGgKgJgGQgJgFgMAAQgKAAgJAEgAImgpIAAiiIArAAIAABWIBYhaIAOAAIAACiIgrAAIAAhWIhYBagAiAgwQgMgGgGgKQgHgLAAgOQAAgVAQgMQAQgNAcAAIAoAAIAAgGQAAgOgHgHQgIgIgPAAQgMABgKAFQgKAGgKALIgWgbQAOgRARgIQARgIAVAAQAUAAAQAHQAPAIAIAQQAJAPAAAWIAABeIgoAAIAAgPQgIAIgMAGQgNAFgPAAQgRAAgNgHgAhnhmQgGAEAAAIQAAAIAGAFQAGAEALAAQAOAAAJgJQAKgIAAgOIAAgCIgiAAQgLAAgFAEgAq4gqIgMgDIAAglIAJABIAIAAQAJAAAHgDQAIgCAGgIIhPiiIAxAAIA1BzIAyhzIAuAAIhICeQgIARgJAOQgIAMgNAHQgNAGgTABIgMgBgAC7grIgHgCIAAgkIADABIADAAQAJABAGgKQAFgIADgTQACgTAAgfIABglIB+AAIAACeIgrAAIAAh6IgrAAIAAAMQgBAngGAZQgFAZgMAMQgMAMgTAAIgKgBgAHTgtIAAgwIgRAAIgnAwIgxAAIAtg3QgQgGgIgNQgJgMAAgRQAAgaARgPQASgOAdAAIBIAAIAACegAGoiiQgGAFAAAJQAAAJAGAFQAGAGAKgBIAbAAIAAgmIgbAAQgLAAgFAFgAAbgtIAAieIBJAAQAQgBANAGQAMAFAIAKQAHAKAAAOQAAAJgDAHQgEAIgGAFQAMAFAGAJQAHAKAAANQAAAOgIALQgHALgNAGQgMAGgRAAgABEhNIAmAAQAKAAAGgFQAGgFAAgHQAAgJgGgEQgGgEgKAAIgmAAgABEiNIAeAAQAJgBAFgEQAFgDAAgHQAAgIgFgDQgFgEgJAAIgeAAgAmlgtIAAh6Ig4AAIAAB6IgrAAIAAieICOAAIAACegAtIh+IAAgMIA/hDIAbAYIgrAxIArAwIgbAZgAuah+IAAgMIA+hDIAcAYIgrAxIArAwIgcAZgAJVjrQgMgHgHgMQgHgNAAgQIAAgJIAiAAIAAAIQAAANAGAGQAFAHAKAAQAKAAAFgHQAGgGAAgNIAAgIIAiAAIAAAJQAAAZgPAOQgPAPgZABQgQAAgNgHg");
	this.shape.setTransform(95.325,38.35);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0102, new cjs.Rectangle(0,0,190.2,72.4), null);


(lib.txt0101 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AKaA5QgJgFgGgKQgFgJAAgMQAAgMAFgJQAGgIAJgGQAJgFAMAAQAMAAAIAFQAIAFAFAIQAEAHABALIgBAGIgBAFIg4AAQADAIAFAEQAGAEAJAAQAGAAAFgCIALgGIAJAPQgHAGgIADQgIADgJAAQgMAAgLgGgAK/ANQABgFgDgDQgDgEgDgBQgEgCgFAAQgHAAgEADQgFAFgDAHIAkAAIAAAAgAHpA5QgJgFgFgKQgGgJAAgMQAAgMAGgJQAFgIAJgGQAKgFAMAAQAMAAAJAFQAIAFAGAJIgQALQgDgFgFgDQgEgDgGAAQgHAAgEACQgFADgCAFQgDAFAAAGQAAAKAFAGQAGAGAKAAQAGAAAEgDQAFgDADgGIAQAMQgGAJgIAFQgJAGgMAAQgMAAgKgGgAFOA/IAAhQIAVAAIAAAqIAsgsIAHAAIAABQIgVAAIAAgrIgsAtgAiGA5QgKgFgGgKQgFgJAAgMQAAgMAFgJQAGgIAJgGQAJgFAMAAQAMAAAHAFQAJAFAFAIQAEAHAAALIAAAGIgBAFIg4AAQADAIAGAEQAFAEAJAAQAGAAAGgCIAKgGIAJAPQgHAGgIADQgIADgJAAQgMAAgKgGgAhiANQABgFgDgDQgDgEgDgBQgEgCgFAAQgGAAgFADQgFAFgDAHIAkAAIAAAAgAlAA/IAAhQIAWAAIAAAqIAsgsIAHAAIAABQIgWAAIAAgrIgsAtgAnvA5QgJgGgGgJQgGgJABgMQgBgMAGgJQAGgIAJgGQAJgFAMAAQANAAAJAFQAKAGAFAIQAGAJAAAMQAAAMgGAJQgFAJgKAGQgJAFgNABQgMgBgJgFgAnoAGQgFAGgBAJQABAKAFAGQAGAGAIAAQAKAAAFgGQAGgGAAgKQAAgJgGgGQgFgGgKAAQgIAAgGAGgAqqA8QgGgEgDgFQgEgFABgHQAAgLAIgGQAIgGANAAIAUAAIAAgEQABgGgEgEQgEgCgHgBQgGAAgGACQgFADgEAFIgMgMQAIgIAIgEQAJgEAKAAQALAAAHAEQAHADAFAIQAEAGAAAMIAAAvIgTAAIAAgIQgFAFgGACQgGADgIAAQgIAAgHgDgAqdAgQgEACAAAEQAAAEAEADQADACAFAAQAHAAAFgFQAEgEAAgHIAAgBIgRAAQgFAAgCACgAhBA+IgEgBIAAgSIACAAIACAAQAEAAADgEQACgEACgKQABgJAAgQIAAgRIA+AAIAABOIgUAAIAAg9IgWAAIAAAGQAAAUgDAMQgDANgFAFQgGAGgLAAIgEAAgAL1A9IAAg9IgYAAIAAgRIBGAAIAAARIgYAAIAAA9gAJfA9IAAgcIgIACIgJABQgPgBgJgJQgIgIAAgRIAAgSIAUAAIAAARQAAAIAFAEQADAEAIAAIAHAAIAGgCIAAgfIAWAAIAABOgAEiA9IAAhOIAWAAIAABOgADVA9IAAhOIAVAAIAAAVIAOAAQAJAAAIAEQAHADAFAGQAEAGAAAJQAAAKgEAGQgFAGgHADQgIAEgJAAgADqArIAOAAQAFAAADgDQADgCAAgFQAAgFgDgDQgDgCgFAAIgOAAgACpA9IAAggIgeAAIAAAgIgVAAIAAhOIAVAAIAAAcIAeAAIAAgcIAVAAIAABOgAAgA9IAAhOIAVAAIAAAVIAPAAQAJAAAHAEQAIADAEAGQAFAGgBAJQABAJgFAHQgEAGgIADQgHAEgJAAgAA1ArIAOAAQAFAAADgDQAEgCAAgFQAAgFgEgDQgDgCgFAAIgOAAgAjRA9IAAg9IgZAAIAAgRIBHAAIAAARIgZAAIAAA9gAlrA9IAAg9IgdAAIAAA9IgVAAIAAhOIBHAAIAABOgAolA9IgggqIAAAqIgVAAIAAhOIAVAAIAAAjIAfgjIAYAAIgeAjIAhArgAreA9IAAguIguAAIAAAuIgWAAIAAhpIAWAAIAAApIAuAAIAAgpIAWAAIAABpgAFmghQgHgEgDgGQgEgGAAgIIAAgFIARAAIAAAEQABAGACAEQADADAFAAQAFAAACgDQADgEABgGIAAgEIAQAAIAAAEQABANgIAIQgHAHgNAAQgIAAgGgDg");
	this.shape.setTransform(83.3,12.275);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt0101, new cjs.Rectangle(0,0,166.2,24.1), null);


(lib.txt02 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhVGkQgJgEgFgJQgFgHAAgLQABgQALgJQAMgJAVAAIAeAAIAAgFQAAgKgFgGQgGgGgLAAQgJAAgIAFQgHAEgIAIIgQgUQAKgMANgGQANgHAQAAQAPABALAFQAMAGAGALQAFAMAAARIAABGIgcAAIAAgMQgHAHgJAEQgJAEgMAAQgNAAgJgFgAhDF7QgEAEAAAFQAAAHAFADQAEADAIAAQALAAAHgGQAHgHAAgKIAAgCIgZAAQgIAAgFADgAnlGkQgJgEgFgJQgFgHAAgLQABgQALgJQAMgJAVAAIAeAAIAAgFQAAgKgFgGQgGgGgLAAQgJAAgIAFQgHAEgIAIIgQgUQAKgMANgGQANgHAQAAQAPABALAFQAMAGAGALQAGAMAAARIAABGIgdAAIAAgMQgHAHgJAEQgJAEgMAAQgNAAgJgFgAnTF7QgEAEAAAFQAAAHAFADQAEADAIAAQALAAAHgGQAHgHAAgKIAAgCIgZAAQgIAAgFADgArMGgQgOgHgJgOQgIgPAAgSQAAgRAIgOQAJgOAOgIQAOgJASAAQASABANAHQANAJAIANIgXARQgFgHgHgFQgGgFgKAAQgKAAgHAEQgHAEgDAIQgEAHAAAJQAAAPAIAJQAJAJAOAAQAJAAAHgFQAHgEAFgIIAXASQgIANgNAIQgNAIgSAAQgSAAgOgJgAiZGmIgvg/IAAA/IggAAIAAh3IAgAAIAAA4IAtg4IAlAAIgtA3IAxBAgAlsGmIAAh3IA3AAQAMAAAJAEQAKAEAFAHQAFAIABAKQAAAIgDAFQgCAGgFAEQAIADAFAHQAFAHAAAKQAAAKgFAJQgGAHgJAFQgKAFgMAAgAlOGOIAdAAQAIAAAEgDQAFgEAAgGQAAgGgFgDQgEgEgIAAIgdAAgAlOFeIAXAAQAHAAAEgEQADgCAAgGQAAgGgDgCQgEgCgHgBIgXAAgApIGmIAAhbIglAAIAAgcIBpAAIAAAcIgkAAIAABbgAEeDDQgPgIgIgOQgIgOAAgRQAAgTAIgNQAIgPAOgHQAOgJASAAQAQAAANAHQANAIAHANQAHAMAAAQIgBAJIgBAIIhUAAQADALAJAHQAIAFAOAAQAJAAAIgCQAJgEAHgGIANAWQgKAJgMAFQgMAEgNAAQgTAAgPgIgAFVCBQAAgHgEgGQgDgFgGgDQgGgDgGAAQgLAAgHAGQgIAHgDALIA2AAIAAAAgApcDDQgPgIgIgOQgIgOAAgRQAAgTAIgNQAIgPAOgHQAOgJASAAQAQAAANAHQANAIAHANQAHAMAAAQIgBAJIgBAIIhUAAQADALAJAHQAIAFAOAAQAJAAAIgCQAJgEAHgGIANAWQgKAJgMAFQgMAEgNAAQgTAAgPgIgAolCBQAAgHgEgGQgDgFgGgDQgGgDgGAAQgLAAgHAGQgIAHgDALIA2AAIAAAAgAA4DIIAAh2IAgAAIAABbIAmAAIAAhbIAhAAIAABbIAmAAIAAhbIAgAAIAAB2gAgJDIIAAh2IAfAAIAAB2gAh9DIIAAh2IAgAAIAAAiIAVAAQAOAAAMAFQALAFAGAJQAHAKAAANQAAAOgHAJQgGAJgLAGQgMAEgOAAgAhdCtIAUAAQAJAAAEgDQAFgEAAgIQAAgHgFgEQgFgEgIABIgUAAgAkCDIIAAh2IA3AAQAMAAAKADQAJAFAGAHQAFAIAAAKQAAAHgDAGQgCAFgFAEQAJAEAFAGQAFAHAAAKQAAALgGAIQgFAIgKAFQgJAEgNAAgAjjCwIAdAAQAHAAAFgDQAEgEAAgGQAAgFgEgEQgFgDgHAAIgdAAgAjjCAIAWAAQAHAAAEgDQAEgCAAgGQAAgGgEgCQgEgDgHAAIgWAAgAmHDIIAAg4IgdAgIgLAAIgcggIAAA4IggAAIAAh5IAKAAIA4A+IA4g+IAKAAIAAB5gArNDIIAAhbIgkAAIAAgbIBpAAIAAAbIglAAIAABbgALMAVIABhHIAlAAIgNBHgAENgZQgPgJgIgOQgIgNAAgSQAAgSAIgOQAIgOAOgIQAOgIASgBQAQABANAHQANAHAHANQAHAMAAAQIgBAJIgBAIIhUAAQADAMAJAGQAIAGAOAAQAJAAAIgDQAJgEAHgFIANAWQgKAIgMAFQgMAFgNAAQgTgBgPgHgAFEhbQAAgIgEgGQgDgFgGgDQgGgCgGAAQgLAAgHAGQgIAHgDALIA2AAIAAAAgAkhgZQgOgJgJgOQgIgOAAgRQAAgSAIgOQAJgOAOgIQAOgIASgBQASABAPAIQAOAIAIAOQAJAOAAASQAAARgJAOQgIAOgPAJQgOAHgSABQgSgBgOgHgAkXhnQgIAJAAAPQAAAOAIAJQAJAJANAAQAOAAAIgJQAJgJAAgOQAAgOgJgKQgIgJgOAAQgNAAgJAJgApAgZQgOgJgIgOQgJgOAAgRQAAgSAJgOQAIgOAOgIQAPgIASgBQASABAOAIQAPAIAIAOQAIAOABASQgBARgIAOQgIAOgPAJQgOAHgSABQgSgBgPgHgAo1hnQgJAJAAAPQAAAOAJAJQAIAJAOAAQANAAAJgJQAIgJAAgOQAAgOgIgKQgJgJgNAAQgOAAgIAJgAiogSIgHAAIgGgCIAAgaIACAAIADAAQAHAAAEgGQAEgHACgOIACgmIAAgcIBeAAIAAB3IggAAIAAhcIggAAIAAAJQgBAfgEASQgEATgJAJQgIAIgOAAIgBAAgAJMgUIAAh3IAgAAIAAAiIAVAAQAPAAALAGQALAFAGAIQAHAKAAAOQAAANgHAJQgGAKgLAFQgLAFgPAAgAJsgwIAUAAQAJAAAEgDQAFgEAAgHQAAgHgFgEQgFgEgIAAIgUAAgAF+gUIAAh3IAgAAIAABbIAmAAIAAhbIAgAAIAABbIAmAAIAAhbIAgAAIAAB3gAC0gUIAAglIgNAAIgdAlIglAAIAigpQgMgFgHgKQgGgJgBgNQABgTANgKQANgLAWgBIA2AAIAAB3gACThrQgFADAAAHQAAAGAFAEQAFAEAHABIAVAAIAAgeIgVAAQgIAAgEAFgAAugUIAAgwIgsAAIAAAwIgfAAIAAh3IAfAAIAAArIAsAAIAAgrIAgAAIAAB3gAl7gUIAAhcIgqAAIAABcIggAAIAAh3IBqAAIAAB3gAqagUIAAhcIgqAAIAABcIggAAIAAh3IBrAAIAAB3gAJDj3QgPgIgIgOQgJgOAAgSQAAgRAIgOQAJgOAOgJQAOgIARAAQARAAANAHQAMAHAHANQAHAMAAARIgBAJIgBAIIhTAAQADAMAIAFQAJAHANgBQAKAAAIgCQAIgEAHgFIAOAVQgKAJgMAFQgMAEgOAAQgTAAgOgIgAJ6k5QgBgIgDgFQgEgFgFgDQgGgDgHAAQgKAAgIAHQgHAGgDALIA2AAIAAAAgAouj3QgPgIgIgOQgIgOAAgSQAAgRAIgOQAIgOAOgJQAOgIASAAQAQAAANAHQANAHAHANQAHAMAAARIgBAJIgBAIIhUAAQADAMAJAFQAIAHAOgBQAJAAAIgCQAJgEAHgFIANAVQgKAJgMAFQgMAEgNAAQgTAAgPgIgAn3k5QAAgIgEgFQgDgFgGgDQgGgDgGAAQgLAAgHAHQgIAGgDALIA2AAIAAAAgAgoj3QgOgJgJgNQgIgOAAgSQAAgSAIgNQAJgOAOgJQAOgIASAAQARAAAPAIQAOAJAIAOQAJANAAASQAAASgJAOQgIANgPAJQgOAIgRAAQgSAAgOgIgAgelEQgIAJAAAOQAAAOAIAKQAJAIANABQANgBAIgIQAJgKAAgOQAAgOgJgJQgIgJgNAAQgNAAgJAJgAi7j4QgOgIgIgRQgIgPAAgWIAAgSQAAgSADgQQAEgPAIgLQAJgMAQgHQAQgHAZgEIAZgDIALgDIAAAeIgLACIgZAEQgVACgLAGQgLAGgEAKQgEALAAAPQAHgKAKgGQALgEAOAAQAQgBAMAJQANAHAHANQAHAOAAARQAAASgIANQgIAOgOAHQgOAIgTAAQgTAAgPgJgAivlBQgIAJgBANQAAAJAEAGQAEAIAHADQAHAFAJAAQAIAAAHgFQAHgDAEgIQAEgGAAgJQAAgNgJgJQgIgIgNAAQgOAAgIAIgABQjwIgHAAIgGgBIAAgbIACAAIADAAQAHAAAEgGQAEgGACgPIACglIAAgcIBeAAIAAB3IggAAIAAhcIggAAIAAAJQgBAegEASQgEATgJAJQgIAJgOAAIgBgBgAFdjxIAAh3IAgAAIAABbIAmAAIAAhbIAgAAIAABbIAmAAIAAhbIAgAAIAAB3gADbjxIAAh3IAgAAIAAAiIAWAAQAOAAALAFQALAFAHAJQAGAKAAANQAAAOgGAJQgHAKgLAEQgLAGgOAAgAD7kNIAVAAQAIAAAFgEQAEgDAAgIQAAgGgEgFQgFgDgIAAIgVAAgAlZjxIAAg5IgdAgIgLAAIgcggIAAA5IggAAIAAh6IAKAAIA4A+IA4g+IAKAAIAAB6gAqJjxIAAg7QgHADgJABQgIABgJAAQgUABgOgIQgOgGgHgOQgIgPAAgUIAAgrIAgAAIAAAoQAAASAJAJQAJAJASAAIAOgBQAHgBAHgDIAAhHIAgAAIAACfg");
	this.shape.setTransform(78.425,50.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt02, new cjs.Rectangle(0,0,156.7,100.6), null);


(lib.txt_stavka_6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AlMETQgxgbgegwQgegwgBg/QAAglALgeQAKgdASgdQATgdAXgfICUjNICQAAIiJC/IAEAAQAyAAAtAZQAtAaAbAtQAcArABA9QgBA+gdAwQgfAvgxAcQgxAbg7ABQg7gBgxgbgAkmASQgcAcgBAsQABAsAcAcQAcAcAqABQArgBAbgcQAbgcABgsQgBgsgbgcQgbgagrgBQgqABgcAagAEwEeQgUgMgNgUQgMgUAAgaQAAgZAMgUQANgUAUgLQAVgMAZAAQAaAAAVAMQAVALAMAUQAMAUABAZQgBAagMAUQgMAUgVAMQgVAMgagBQgZABgVgMgAFEC0QgJALgBARQABASAJAKQAKALARAAQAQAAAJgLQAKgKAAgSQAAgRgKgLQgJgKgQAAQgRAAgKAKgABtEkIDNlkIA7AAIjNFkgABUBfQgVgMgMgVQgNgUAAgZQAAgZANgUQAMgUAVgKQAVgMAagBQAZABAVAMQAVAKALAUQANAUABAZQgBAZgNAUQgLAVgVAMQgVALgZAAQgaAAgVgLgABpgJQgJAJgBARQABASAJAKQAKALAQAAQAPAAAKgLQAKgLAAgRQAAgRgKgJQgKgLgPAAQgQAAgKALg");
	this.shape.setTransform(94.2,62.25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt_stavka_6, new cjs.Rectangle(0,0,224.7,117.2), null);


(lib.txt_stavka = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACiCwIAAgSIgsAAIAAASIgRAAIAAghIAHAAQAEgEABgIQACgJABgNIAAgQIA0AAIAAAyIAKAAIAAAhgACEBwIgCASQgCAIgCAFIAYAAIAAgjIgSAAgADOCbQgIgFgEgHQgFgIAAgJQAAgKAFgIQAEgHAIgFQAIgEAKAAQAKAAAHAEQAIAFAFAHQAEAIAAAKQAAAJgEAIQgFAHgIAFQgIAEgJAAQgKAAgIgEgADUBxQgFAFAAAIQAAAHAFAFQAEAFAIAAQAHAAAFgFQAEgFAAgHQAAgIgEgFQgFgFgHAAQgIAAgEAFgAApCbQgIgFgFgHQgEgIAAgJQAAgKAEgIQAFgHAIgFQAIgEAJAAQAKAAAIAEQAIAFAEAHQAFAIAAAKQAAAJgFAIQgEAHgIAFQgIAEgKAAQgKAAgHgEgAAuBxQgEAFAAAIQAAAHAEAFQAFAFAHAAQAIAAAEgFQAFgFAAgHQAAgIgFgFQgEgFgIAAQgHAAgFAFgAiKCdQgFgDgCgEQgDgEAAgGQAAgJAGgFQAHgFALAAIAQAAIAAgCQAAgGgDgDQgDgDgGAAQgFAAgEADQgEACgEAEIgJgLQAGgHAHgDQAHgDAIAAQAJAAAGADQAGADADAGQAEAGAAAKIAAAmIgQAAIAAgGQgEADgFACQgFACgGAAQgHAAgFgCgAiACHQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAAAQAAAEACACQADABAEAAQAGAAADgDQAEgEAAgFIAAgBIgNAAQgFAAgCACgAlpCdQgFgDgCgEQgDgEAAgGQAAgJAGgFQAHgFALAAIAQAAIAAgCQAAgGgDgDQgDgDgGAAQgFAAgEADQgEACgEAEIgJgLQAGgHAHgDQAHgDAIAAQAJAAAGADQAGADADAGQAEAGAAAKIAAAmIgQAAIAAgGQgEADgFACQgFACgGAAQgHAAgFgCgAlfCHQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAAAQAAAEACACQADABAEAAQAGAAADgDQAEgEAAgFIAAgBIgNAAQgFAAgCACgAnqCbQgIgFgEgHQgFgIAAgJQAAgKAFgIQAEgHAIgFQAIgEAJAAQAKAAAHAEQAHAEAEAIIgMAJIgGgGQgEgDgFAAQgFAAgEACQgEADgCADQgCAEAAAGQAAAHAEAFQAFAFAIAAQAFAAAEgCQADgDADgEIAMAJQgEAIgHAEQgHAEgKAAQgJAAgIgEgAHpCeIgOgVIgOAVIgUAAIAYghIgWggIATAAIANATIAMgTIAUAAIgWAfIAXAigAGcCeIAAhBIARAAIAABBgAFcCeIAAhBIASAAIAAATIALAAQAIAAAGADQAGACAEAFQADAFAAAIQAAAHgDAFQgEAFgGADQgGADgIAAgAFuCPIALAAQAEAAADgCQACgCAAgEQAAgEgCgCQgDgCgEAAIgLAAgAESCeIAAhBIAeAAQAHAAAFADQAFACADAEQADAEAAAFQAAAEgCADQgBADgCACQAEACADAEQADAEAAAFQAAAGgDAEQgDAFgFACQgGADgGAAgAEjCRIAQAAQAEAAACgCQADgCAAgDQAAgEgDgBQgCgCgEAAIgQAAgAEjB2IAMAAQAEAAACgBQABgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQAAgBgBAAQAAgBgBAAIgGgBIgMAAgAggCeIAAhBIAuAAIAAAPIgdAAIAAAygAixCeIgZgiIAAAiIgSAAIAAhBIASAAIAAAeIAYgeIAUAAIgYAeIAaAjgAkmCeIAAhBIAeAAQAHAAAFADQAFACADAEQADAEAAAFQAAAEgCADQgBADgCACQAEACADAEQADAEAAAFQAAAGgDAEQgDAFgFACQgGADgGAAgAkVCRIAQAAQAEAAACgCQADgCAAgDQAAgEgDgBQgCgCgEAAIgQAAgAkVB2IAMAAQAEAAACgBQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAIgGgBIgMAAgAmhCeIAAgyIgTAAIAAgPIA5AAIAAAPIgUAAIAAAygAliAfIAAgsIhsAAIAAAsIgpAAIAAhRIARAAQAKgJAEgVQAEgUABggIACgoIB+AAIAAB6IAbAAIAABRgAmrh+QgBAagEATQgEATgGAMIA8AAIAAhVIgtAAgAkAgVQgTgLgLgSQgLgTgBgYQABgXALgTQALgSATgLQATgLAYAAQAYAAATALQATALAMATQALASAAAXQAAAYgLASQgMATgTALQgTALgYAAQgYAAgTgLgAjyh8QgMAMAAAUQAAATAMAMQALALASABQASgBALgMQAMgLAAgTQAAgTgMgNQgLgMgSAAQgSAAgLAMg");
	this.shape.setTransform(52.825,92.775);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.txt_stavka, new cjs.Rectangle(0,0,224.7,117.2), null);


(lib.LOGO = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aq2BuQgtgugBhAQABg/AtgtQAuguBBAAQBAAAAvAuQAtAtAAA/QAABAgtAuQgvAthAAAQhBAAgugtgAqyhpQgsAsAAA9QAAA+AsAsQAsArA/AAQA/AAArgrQAtgsAAg+QAAg9gtgsQgrgsg/AAQg/AAgsAsgApOByQgogCgcgZQgGgGgCgIQgLgHgHgJQgDgFACgHIABgEQgIgFgCgEQgEgHAFgKIgFgHQgBgEAAgEQABgHAGgIQANgNAegLIAagGIAVgGIAegFQATgDALgDQgogIgnAIQgoAHghAWIADgJQAhgVAigHQAogIA0AJQAGgEACgGQgagJgnAAQgUABgZAGQgdAHgPAIIAHgIQAMgIAagGQAcgIAWAAIAcABIAfAHQgCgDgEgDIgKgEQgUgJgeABQggAAgcAMQAKgGAGgDQAZgLAiAAQARABAQAGQARAFAKALQAEAEABAEQARAJAGAJQACAGgBAGQAHADADAGQAEAEAAAEQABAIgFAFQAEACACADIACAFQADAMgOAMQgHAFgMAGQgOAGgLADIgsAJIglAGQAYAGAVgBQAeAAAggLQAQgFAKgGIgBAGQgVAMggAIQgbAFgSgBQgcgBgagIIgQAGQASAHARAEQANADAUABQARACAYgFQAagDAXgJIgEAFQgLAGgVAGQgWAFgMAAQgfACgZgFQgRgDgYgKQgEACAAAEQAmATAmADQAkABArgNIgGAGQgqAQgngCQgfgCgggPIgDgCQADAHARAIQAWAMAUACQAQABASgCQARgDANgEIgKAEQgVALgaAAIgIgBgAqZA8IADgEIgKgGQAAAFAHAFgAqbApIANAHIAKgEIgQgHQgFABgCADgAnogMQgLAJgeAHQgVAGgfAFQgjAGgNADIgTAGIATAJQAVgGASgDIAugJQAdgGARgIQAWgKgIgMgAqqAdIAEAEIAEgEIgJgFQAAADABACgAn7gfQgMAGgXAFIgfAGIgwAJQgnAJgPALIAGAEIAFADQALgHAPgEQAUgEAjgGIAkgHQAYgEAOgFQAJgEAHgFIgHgEIgHgDIAAAAgAo4gqQgmAEgkALQg4ARANAQIAIgGQAMgHATgGQAVgFAmgHQApgIATgFIgUgEIgIAAIgNAAgAnwgmIAKAGQACgDgBgDQgBgCgDgDIgHAFgAobgzIAOADIANAEQABABAEgEIAEgEQgJgEgNgEQgHAFgHADgAoEhCIARAGQgBgHgMgHIgEAIgAitBBIABgcQAKAEAKAAQAHAAAFgEQADgFAAgEQAAgNgQAAIgNAAIAAgcIANAAQAFAAAFgCQAFgEABgHQAAgIgHgDQgDgCgFAAQgJAAgJAEIAAgeQAOgDAOAAQATAAAKALQAJALAAANQAAANgGAIQgFAIgJADIAAABQAJACAGAIQAHAIAAAOQAAATgMALQgMAKgRAAQgSAAgMgHgAB4AwQgLgTAAgdQAAgdALgSQANgWAaAAQAaAAANAWQAMASAAAdQAAAdgMATQgNAWgagBQgaABgNgWgACOAAQAAAkARABQARgBAAgkQAAgkgRAAQgRAAAAAkgAHwBEIgEgXIgVAAIgEAXIggAAIAbiHIAnAAIAcCHgAHbAOIAMAAIgFgogALABDIgRg2IgIAAIAAA2IgfAAIAAiGIAfAAIAAAxIAGAAIASgxIAiAAIgYBAIAcBGgAJUBDIAAg2IgXAAIAAA2IgeAAIAAiGIAeAAIAAAxIAXAAIAAgxIAfAAIAACGgAFcBDIAAiGIBJAAIAAAhIgqAAIAAASIAGAAQARgBALAIQAQAJAAAXQgBAbgSAKQgLAIgOgBgAF7AoIAFAAQAEAAAEgCQAFgFAAgJQAAgOgNAAIgFAAgAEnBDIAAhRIgTAXIgTgXIAABRIghAAIAAiGIAbAAIAZAgIAYggIAbAAIAACGgAAQBDIAAiGIArAAQAVAAALAQQAKANgBAQQAAARgJAMQgKAQgWAAIgKAAIAAAsgAAxgGIAHAAQAMAAAAgQQAAgPgMAAIgHAAgAggBDIAAhlIgXAAIAABlIggAAIAAiGIBWAAIAACGgAjXBDIgEgXIgWAAIgEAXIggAAIAbiGIAoAAIAbCGgAjsAOIAMAAIgGgogAlSBDIAAiGIBBAAIAAAiIgiAAIAABkg");
	this.shape.setTransform(74.05,15.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.LOGO, new cjs.Rectangle(0,0,148.1,31), null);


(lib.legal_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.legal_1, new cjs.Rectangle(0,0,260,363), null);


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AkfEgIAAo/II/AAIAAI/g");
	mask.setTransform(28.75,28.75);

	// Layer_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C5C7C9").s().p("AjlEgQgYAAgQgRQgRgRgBgYIAAnLQABgYARgQQAQgRAYgBIHLAAQAYABAQARQARAQABAYIAAHLQgBAYgRARQgQARgYAAgAkLkLQgPAQgBAWIAAHLQABAWAPAQQAQAPAWAAIHLAAQAWAAAQgPQAPgQAAgWIAAnLQAAgWgPgQQgQgPgWgBInLAAQgWABgQAPg");
	this.shape.setTransform(28.75,28.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00B159").s().p("AALA1IgpgpIAHgHIAfAgQAGAGAGgGIAgghIAXAXIgbAbQgIAIgKAAQgLAAgIgJgAhKgaIAbgcQAIgHAKgBQALAAAIAJIApAqIgGAHIggggQgGgHgGAGIggAig");
	this.shape_1.setTransform(12.475,47.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#11499E").s().p("AgPBDQgUAAgSgSIgVgWIAXgWIAuAvQANANAIACgAAGgzQgNgNgIgBIAfgBQAUAAASATIAVAVIgXAWg");
	this.shape_2.setTransform(12.475,47.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#11499E").s().p("AgOBGIAAgFIgPAAIAAAFIgFAAIAAgKIACAAQADgDAAgIIAAgHIARAAIAAASIADAAIAAAKgAgYAyQAAAHgCADIAIAAIAAgOIgGAAgAATBBIAAgXIAKAAQAIAAAAAFQAAAEgEABIAAABQAFAAAAAFQAAAHgIAAgAAYA9IAEAAQABAAABAAQAAgBABAAQAAAAABgBQAAAAAAgBQAAgBAAgBQgBAAAAgBQgBAAAAAAQgBAAgBAAIgEAAgAAYAzIAEAAQABAAABAAQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAgBAAIgEAAgAgHA1QAAgFAEgEQADgDADAAQAMAAAAAMQAAAMgMAAQgKAAAAgMgAgBA1QAAAIAEAAQAGAAAAgIQAAgHgGAAQgEAAAAAHgAgrBBIAAgEQgCAEgFAAQgIAAAAgHQAAgIALAAIAEAAIAAgBQAAgDgFAAQgEAAgDACIAAgFIAIgCQAJAAAAAJIAAAPgAg0A6QAAABAAAAQABABAAAAQAAAAABABQAAAAABAAQAGAAAAgGIAAgBIgBAAQgIAAAAAEgAhEBBIAAgTIgGAAIAAAFQAAAJgBACQgCADgEAAIgDAAIABgFIABAAQADAAAAgJIAAgJIARAAIAAAXgAhbBBIgHgLIgBAAIAAALIgFAAIAAgXIAFAAIAAAKIABAAIAHgKIAGAAIgIALIAJAMgAiCBBIAAgfIAJAAQAKAAAAAHQAAAGgFABIAAABQAHABAAAGQAAAJgMAAgAh8A8IADAAQAFAAAAgFQAAgEgFAAIgDAAgAh8AuIADAAQAEAAAAgEQAAgDgFAAIgCAAgAhUAWIAAgfIAFAAIAAAEIAAAAQACgEAFAAQAJAAAAAKQAAAMgJAAQgEAAgCgDIAAAMgAhOABQAAAHAFAAQAEAAAAgHQAAgGgEAAQgFAAAAAGgAB/ANIAAgJIgDAAIgEAJIgHAAIAFgKQgEgBAAgEQAAgHAHAAIALAAIAAAWgAB3gCQAAABAAAAQABABAAAAQABAAAAAAQABAAABAAIAEAAIAAgFIgEAAQgBAAgBAAQAAAAgBAAQAAABgBAAQAAABAAABgABnANIAAgPIgJAPIgGAAIAAgWIAFAAIAAAPIAKgPIAGAAIAAAWgABMANIAAgKIgJAAIAAAKIgFAAIAAgWIAFAAIAAAIIAJAAIAAgIIAGAAIAAAWgAAzANIAAgEQgCAEgFAAQgIAAAAgHQAAgHALAAIADABIABAAIAAgBQAAgEgFAAQgEAAgDACIAAgFIAIgBQAJAAAAAIIAAAOgAAqAGQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAGAAAAgGIAAgBIgBAAQgIAAAAAEgAAOANIAAgWIAKAAQAIAAAAAFQAAAEgEAAIAAABQAFAAAAAFQAAAHgIAAgAATAJIAEAAQABAAABAAQAAgBABAAQAAAAABgBQAAAAAAgBQAAgDgEAAIgEAAgAATAAIAEAAQABAAAAAAQABgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEAAgAgMABQAAgKALAAQALAAAAAKQAAAMgLAAQgLAAAAgMgAgGABQAAAIAFAAQAFAAAAgIQAAgGgFAAQgFAAAAAGgAgUANIgEgGIgBgDIgFAJIgHAAIAIgMIgHgKIAHAAIAEAIIACgDIACgFIAHAAIgHAKIAHAMgAgtANIAAgEQgCAEgFAAQgIAAAAgHQAAgHALAAIADABIABAAIAAgBQAAgEgFAAQgEAAgDACIAAgFIAIgBQAJAAAAAIIAAAOgAg2AGQAAABAAAAQAAABABAAQAAAAABABQAAAAABAAQAGAAAAgGIAAgBIgBAAQgIAAAAAEgAhkANIAAgSIgGAAIAAgEIATAAIAAAEIgHAAIAAASgAiDgCQAAgQAQAAIAHACIgBAFIgGgBQgKAAAAAKQAAAKAKAAQAEAAACgCIABAGIgIABQgPAAAAgPgAARgtQAAgHAKAAIAEAAIAAgBQAAgEgFAAQgDAAgEACIAAgFQADgBAFAAQAKAAAAAIIAAAPIgGAAIAAgEQgCAEgFAAQgHAAAAgHgAAWgtQAAABAAAAQABABAAAAQABAAAAABQABAAABAAQAFAAAAgGIAAgBIgBAAQgIAAAAAEgAgngyQAAgLALAAQAKAAAAAMIAAABIgPAAQAAAGAGAAIAHgCIAAAFIgHABQgMAAAAgMgAghg0IAJAAQAAgFgFAAQgEAAAAAFgAhPgyQAAgLAMAAIAFAAIAAAFIgEgBQgHAAAAAHQAAAIAHAAIAEgBIAAAEIgFABQgMAAAAgMgAh+gpQgFgFAAgIQAAgPAQAAIAHABIgBAFIgGgBQgKAAAAAKQAAALAKAAQAEAAACgCIABAGIgIABQgGAAgEgDgAAHgmIAAgRIgGARIgEAAIgEgOIgCgDIAAARIgFAAIAAgXIAIAAIAEANIABAEIABAAIAAgEIAEgNIAIAAIAAAXgAg1gmIAAgTIgHAAIAAgEIATAAIAAAEIgHAAIAAATgAhYgmIAAgQIgKAQIgGAAIAAgXIAGAAIAAAMIgBAEIABAAIAJgQIAGAAIAAAXg");
	this.shape_3.setTransform(38.675,47.825);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhgBEIAAg1IAIAAIAAAHIABAAQADgHAJAAQAPAAAAATQAAATgQAAQgHAAgDgGIgBAAIABAVgAhWAiQAAALAIAAQAIAAAAgLQAAgMgIAAQgIAAAAAMgABsAqQAAgNASAAIAFABIABAAIAAgCQAAgGgIAAQgGAAgGADIAAgIQAFgCAIAAQAQAAAAAOIAAAYIgJAAIAAgGIAAAAQgCAGgKAAQgMAAAAgLgAB1AqQAAAEAGAAQAJAAAAgJIAAgBIgCAAQgNAAAAAGgAAeAwQgFgFAAgJQAAgJAFgFQAFgFAJAAQATAAAAATQAAAJgGAFQgFAFgIAAQgJAAgFgFgAAjAiQAAAMAJAAQAJAAAAgMQAAgMgJAAQgJAAAAAMgAg3AqQAAgNASAAIAFABIABAAIAAgCQAAgGgIAAQgGAAgGADIAAgIQAGgCAIAAQAQAAAAAOIAAAYIgKAAIAAgGQgCAGgJAAQgNAAAAgLgAgtAqQAAAEAFAAQAJAAAAgJIAAgBIgBAAQgNAAAAAGgAigAvQgFgFAAgIQAAgIAFgFQAGgGAJAAIAIABIAAAHIgGgBQgFAAgDADQgEAEAAAFQAAAMALAAIAHgBIABAHQgFABgFAAQgJAAgFgGgAjOAqQAAgNASAAIAGABIABAAIAAgCQAAgGgJAAQgFAAgGADIAAgIQAFgCAIAAQAQAAAAAOIAAAYIgJAAIAAgGQgEAGgIAAQgNAAAAgLgAjEAqQAAAEAGAAQAJAAAAgJIAAgBIgCAAQgNAAAAAGgAjxAyIABgHQAHADAFAAQAHAAAAgFQAAgFgHAAIgFAAIAAgGIAFAAQAFAAAAgEQAAgEgGAAQgFAAgFACIAAgHQAGgCAGAAQAOAAAAAJQAAAHgGACQAIABAAAIQAAALgRAAQgHAAgGgDgADoA1IAAgmIAKAAIAAAmgADCA1IAAgmIAKAAIAAANIAHAAQAQAAAAANQAAAMgPAAgADMAuIAGAAQAHAAAAgFQAAgGgHAAIgGAAgACwA1IAAgQIgQAAIAAAQIgJAAIAAgmIAJAAIAAAOIAQAAIAAgOIAJAAIAAAmgABGA1IAAgmIASAAQAMAAAAAJQAAAHgHACQAJABAAAIQAAALgOAAgABPAuIAGAAQAHAAAAgFQAAgFgHAAIgGAAgABPAeIAGAAQAGAAAAgEQAAgEgGAAIgGAAgAAKA1IgGgKIgCgFIAAAAIgCAFIgFAKIgLAAIAMgUIgLgSIAMAAIAEAJIACAEIAAAAIACgEIAFgJIALAAIgMASIANAUgAh6A1IAAgfIgMAAIAAgHIAhAAIAAAHIgMAAIAAAfgAgqgHIAAgJIgaAAIAAAJIgIAAIAAgRIAEAAQAEgFAAgNIAAgMIAdAAIAAAeIAGAAIAAARgAg7gpQAAAMgEAFIAPAAIAAgWIgLAAgAh0gbQAAgMASAAIAHAAIAAgCQAAgGgJAAQgGAAgFADIAAgIQAFgCAIAAQAQAAAAAOIAAAYIgJAAIAAgGQgEAGgIAAQgNAAAAgLgAhqgbQAAAFAGAAQAJAAAAgKIAAgBIgCAAQgNAAAAAGgAifgQIAAgIIACAAQADAAABgEIABgKIAAgQIAdAAIAAAmIgJAAIAAgeIgMAAIAAAIQAAAOgCAEQgCAEgHAAgAAKgQIAAgmIAJAAIAAAmgAgbgQIAAgmIAJAAIAAAOIAIAAQAOAAAAAMQAAAMgOAAgAgSgXIAGAAQAHAAAAgFQAAgGgHAAIgGAAgAisgQIgMgSIgBAAIAAASIgJAAIAAgmIAJAAIAAARIABAAIALgRIALAAIgNASIAPAUgAjugQIAAgzIAQAAQARAAAAANQAAAJgIACQAKACAAAKQAAAPgUAAgAjkgYIAFAAQAJAAAAgHQAAgHgJAAIgFAAgAjkguIAFAAQAIAAAAgHQAAgGgJAAIgEAAg");
	this.shape_4.setTransform(28.025,13.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#11499E").s().p("AkeC+IAAlCQAAgYARgRQARgQAYgBIHJAAQAYABARAQQARARAAAYIAAFCg");
	this.shape_5.setTransform(28.725,19.15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AjkEfQgYAAgRgRQgRgRAAgYIAAnJQAAgYARgRQARgRAYAAIHJAAQAYAAARARQARARAAAYIAAHJQAAAYgRARQgRARgYAAg");
	this.shape_6.setTransform(28.725,28.775);

	var maskedShapeInstanceList = [this.shape,this.shape_1,this.shape_2,this.shape_3,this.shape_4,this.shape_5,this.shape_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,57.5,57.5), null);


(lib.butt_wh = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0057B5").s().p("ACMBLIAAhqIALAAIAAANQAFgHAHgEQAJgDAIAAQAMAAAJAGQAIAEAFAJQAFAKAAAKQAAAMgFAKQgFAIgIAGQgJAFgMABQgIgBgHgDQgIgDgFgGIAAAngACmgSQgGADgEAHQgEAGAAAJQAAALAEAGQAEAHAGADQAGADAHAAQAIAAAGgEQAGgDAEgHQAEgHgBgJQABgHgEgGQgDgHgHgEQgGgEgIAAQgHAAgGADgABsBFIAAgWIg+AAIAAAWIgMAAIAAghIAJAAQAFgHADgLQACgMAAgOIABgXIA1AAIAABDIANAAIAAAhgABBgIQgBAPgCAMQgCALgEAGIAnAAIAAg4IgdAAgAJ5ArQgJgGgGgIQgGgKAAgMQAAgKAGgJQAFgJAJgFQAJgGAMAAQAKAAAIAEQAHAFAFAIQAFAIAAAJIAAAFIgBAFIg9AAQAAAHAEAGQAEAGAGADQAGADAIAAQAHAAAGgDQAGgCAFgFIAHAHQgGAHgIAEQgHADgKABQgMgBgJgFgAKjABQAAgHgDgFQgEgFgEgDQgFgCgHAAQgKAAgHAGQgHAGgCAKIAxAAIAAAAgAIdArQgJgGgFgIQgGgKAAgMQAAgKAGgJQAFgJAIgFQAJgGAMAAQAKAAAIAEQAIAFAFAIQAEAIABAJIgBAFIgBAFIg9AAQABAHADAGQAEAGAGADQAHADAIAAQAGAAAGgDQAHgCAEgFIAHAHQgGAHgHAEQgIADgJABQgMgBgKgFgAJHABQAAgHgCgFQgEgFgFgDQgFgCgGAAQgLAAgGAGQgIAGgBAKIAwAAIAAAAgAmbAuQgGgDgEgFQgDgFAAgGQAAgLAIgFQAHgHANAAIAZAAIAAgFQAAgKgGgFQgEgFgJAAQgIAAgFAEQgGACgEAHIgIgHQAFgJAJgEQAIgEAKAAQAJAAAHADQAGAEAEAHQAEAHAAAKIAAAwIgMAAIAAgKQgEAFgGADQgHADgJABQgIgBgGgCgAmXASQgFACAAAFQABAFACACQACADAEACQADABAFAAQAGAAAGgDQAFgCAEgFQADgGAAgGIAAgCIgYAAQgHAAgFAEgApAAtQgHgFgGgHIAJgHQADAEAFAEQAFADAIAAQAIAAAEgEQAFgDAAgHQAAgFgFgEQgEgEgIABIgJAAIAAgLIAJAAQAHAAADgCQAEgDAAgFQAAgFgEgDQgEgDgHAAQgGAAgFADQgEACgEAFIgIgIQADgGAIgDQAHgEAKAAQAMAAAGAGQAIAFAAAKQgBAFgCAEQgCAEgEADQAGADADAEQAEAFgBAHQAAAMgIAFQgHAHgOABQgKgBgHgDgAFiAqQgKgFgEgKQgGgKAAgNIAAgMQAAgMACgLQABgJAFgIQAGgHAJgFQAKgFAPgDIARgDIAKgEIAAANIgKADIgPACQgNADgIAEQgIADgEAGQgDAGgBAGIgBAPQAFgHAIgEQAHgEAKgBQALABAIAFQAJAGAGAIQAEAJABAKQgBALgEAJQgGAIgJAGQgJAFgLAAQgNAAgIgGgAFogOQgGAEgEAGQgDAFAAAIQAAAIADAGQAEAHAGADQAGADAJABQAHgBAGgDQAHgDAEgHQADgGAAgIQAAgIgDgFQgEgGgHgEQgGgEgHAAQgJAAgGAEgAD/AqQgJgFgFgJQgGgJAAgMQAAgKAGgKQAFgJAJgEQAJgGAMAAQAMAAAIAGQAKAEAFAKQAGAJgBAKQABAMgGAJQgFAJgKAFQgJAGgLAAQgMAAgJgGgAEFgRQgGAEgEAHQgDAGAAAHQAAAJADAGQAEAHAGAEQAGADAJABQAHgBAHgDQAGgEAEgHQAEgGAAgJQAAgHgEgGQgEgHgGgEQgGgEgIAAQgIAAgHAEgAghAqQgJgFgFgJQgGgJAAgMQAAgKAGgKQAFgJAJgEQAJgGAMAAQALAAAIAGQAKAEAFAKQAGAJgBAKQABAMgGAJQgFAJgKAFQgIAGgLAAQgMAAgJgGgAgbgRQgGAEgEAHQgDAGAAAHQAAAJADAGQAEAHAGAEQAGADAJABQAHgBAGgDQAGgEAEgHQAEgGAAgJQAAgHgEgGQgEgHgGgEQgFgEgIAAQgIAAgHAEgAqZAwIgEgBIAAgLIAEABIAEAAQAFAAAEgDQAEgDADgGIgqhTIAOAAIAjBFIAhhFIAMAAIgmBQIgIAPQgEAFgGAEQgEACgIAAIgEAAgAHnAvIAAgkIgmAAIAAAkIgMAAIAAhOIAMAAIAAAfIAmAAIAAgfIANAAIAABOgAhXAvIAAhDIgmAAIAABDIgMAAIAAhOIA/AAIAABOgAkHAvIAAhOIAMAAIAAAbIASAAQAOAAAIAHQAHAHABALQgBALgHAIQgIAHgOAAgAj7AkIASAAQAIgBAFgEQAEgDAAgHQAAgGgEgEQgFgFgJAAIgRAAgAk+AvIAAhDIgbAAIAAgLIBBAAIAAALIgbAAIAABDgAnJAvIAAgkIgmAAIAAAkIgMAAIAAhOIAMAAIAAAfIAmAAIAAgfIANAAIAABOg");
	this.shape.setTransform(-0.2,0.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Az/DVQgMAAgGgKIgCgKIAAmBQAAgMAKgFQAFgDAFAAMAn/AAAQAMAAAGAKQACAFAAAFIAAGBQAAAMgKAFIgKADg");
	this.shape_1.setTransform(0,0.275);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.butt_wh, new cjs.Rectangle(-130,-21.2,260,42.8), null);


(lib.butt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACMBLIAAhqIALAAIAAANQAFgHAHgEQAJgDAIAAQAMAAAJAGQAIAEAFAJQAFAKAAAKQAAAMgFAKQgFAIgIAGQgJAFgMABQgIgBgHgDQgIgDgFgGIAAAngACmgSQgGADgEAHQgEAGAAAJQAAALAEAGQAEAHAGADQAGADAHAAQAIAAAGgEQAGgDAEgHQAEgHgBgJQABgHgEgGQgDgHgHgEQgGgEgIAAQgHAAgGADgABsBFIAAgWIg+AAIAAAWIgMAAIAAghIAJAAQAFgHADgLQACgMAAgOIABgXIA1AAIAABDIANAAIAAAhgABBgIQgBAPgCAMQgCALgEAGIAnAAIAAg4IgdAAgAJ5ArQgJgGgGgIQgGgKAAgMQAAgKAGgJQAFgJAJgFQAJgGAMAAQAKAAAIAEQAHAFAFAIQAFAIAAAJIAAAFIgBAFIg9AAQAAAHAEAGQAEAGAGADQAGADAIAAQAHAAAGgDQAGgCAFgFIAHAHQgGAHgIAEQgHADgKABQgMgBgJgFgAKjABQAAgHgDgFQgEgFgEgDQgFgCgHAAQgKAAgHAGQgHAGgCAKIAxAAIAAAAgAIdArQgJgGgFgIQgGgKAAgMQAAgKAGgJQAFgJAIgFQAJgGAMAAQAKAAAIAEQAIAFAFAIQAEAIABAJIgBAFIgBAFIg9AAQABAHADAGQAEAGAGADQAHADAIAAQAGAAAGgDQAHgCAEgFIAHAHQgGAHgHAEQgIADgJABQgMgBgKgFgAJHABQAAgHgCgFQgEgFgFgDQgFgCgGAAQgLAAgGAGQgIAGgBAKIAwAAIAAAAgAmbAuQgGgDgEgFQgDgFAAgGQAAgLAIgFQAHgHANAAIAZAAIAAgFQAAgKgGgFQgEgFgJAAQgIAAgFAEQgGACgEAHIgIgHQAFgJAJgEQAIgEAKAAQAJAAAHADQAGAEAEAHQAEAHAAAKIAAAwIgMAAIAAgKQgEAFgGADQgHADgJABQgIgBgGgCgAmXASQgFACAAAFQABAFACACQACADAEACQADABAFAAQAGAAAGgDQAFgCAEgFQADgGAAgGIAAgCIgYAAQgHAAgFAEgApAAtQgHgFgGgHIAJgHQADAEAFAEQAFADAIAAQAIAAAEgEQAFgDAAgHQAAgFgFgEQgEgEgIABIgJAAIAAgLIAJAAQAHAAADgCQAEgDAAgFQAAgFgEgDQgEgDgHAAQgGAAgFADQgEACgEAFIgIgIQADgGAIgDQAHgEAKAAQAMAAAGAGQAIAFAAAKQgBAFgCAEQgCAEgEADQAGADADAEQAEAFgBAHQAAAMgIAFQgHAHgOABQgKgBgHgDgAFiAqQgKgFgEgKQgGgKAAgNIAAgMQAAgMACgLQABgJAFgIQAGgHAJgFQAKgFAPgDIARgDIAKgEIAAANIgKADIgPACQgNADgIAEQgIADgEAGQgDAGgBAGIgBAPQAFgHAIgEQAHgEAKgBQALABAIAFQAJAGAGAIQAEAJABAKQgBALgEAJQgGAIgJAGQgJAFgLAAQgNAAgIgGgAFogOQgGAEgEAGQgDAFAAAIQAAAIADAGQAEAHAGADQAGADAJABQAHgBAGgDQAHgDAEgHQADgGAAgIQAAgIgDgFQgEgGgHgEQgGgEgHAAQgJAAgGAEgAD/AqQgJgFgFgJQgGgJAAgMQAAgKAGgKQAFgJAJgEQAJgGAMAAQAMAAAIAGQAKAEAFAKQAGAJgBAKQABAMgGAJQgFAJgKAFQgJAGgLAAQgMAAgJgGgAEFgRQgGAEgEAHQgDAGAAAHQAAAJADAGQAEAHAGAEQAGADAJABQAHgBAHgDQAGgEAEgHQAEgGAAgJQAAgHgEgGQgEgHgGgEQgGgEgIAAQgIAAgHAEgAghAqQgJgFgFgJQgGgJAAgMQAAgKAGgKQAFgJAJgEQAJgGAMAAQALAAAIAGQAKAEAFAKQAGAJgBAKQABAMgGAJQgFAJgKAFQgIAGgLAAQgMAAgJgGgAgbgRQgGAEgEAHQgDAGAAAHQAAAJADAGQAEAHAGAEQAGADAJABQAHgBAGgDQAGgEAEgHQAEgGAAgJQAAgHgEgGQgEgHgGgEQgFgEgIAAQgIAAgHAEgAqZAwIgEgBIAAgLIAEABIAEAAQAFAAAEgDQAEgDADgGIgqhTIAOAAIAjBFIAhhFIAMAAIgmBQIgIAPQgEAFgGAEQgEACgIAAIgEAAgAHnAvIAAgkIgmAAIAAAkIgMAAIAAhOIAMAAIAAAfIAmAAIAAgfIANAAIAABOgAhXAvIAAhDIgmAAIAABDIgMAAIAAhOIA/AAIAABOgAkHAvIAAhOIAMAAIAAAbIASAAQAOAAAIAHQAHAHABALQgBALgHAIQgIAHgOAAgAj7AkIASAAQAIgBAFgEQAEgDAAgHQAAgGgEgEQgFgFgJAAIgRAAgAk+AvIAAhDIgbAAIAAgLIBBAAIAAALIgbAAIAABDgAnJAvIAAgkIgmAAIAAAkIgMAAIAAhOIAMAAIAAAfIAmAAIAAgfIANAAIAABOg");
	this.shape.setTransform(-0.2,0.55);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_3 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0057B5").s().p("Az/DVQgMAAgGgKIgCgKIAAmBQAAgMAKgFQAFgDAFAAMAn/AAAQAMAAAGAKQACAFAAAFIAAGBQAAAMgKAFIgKADg");
	this.shape_1.setTransform(0,0.275);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.butt, new cjs.Rectangle(-130,-21.2,260,42.8), null);


(lib.btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FF00").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-120,-200,240,400);


(lib.bondarchuk_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bondarchuk();
	this.instance.parent = this;
	this.instance.setTransform(-89,-222);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bondarchuk_1, new cjs.Rectangle(-89,-222,178,444), null);


(lib.BG_WH = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.BG_WH, new cjs.Rectangle(-150,-300,300,600), null);


(lib.BG_BLUE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0057B6").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.BG_BLUE, new cjs.Rectangle(-150,-300,300,600), null);


(lib.txt_stavka_mov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 6
	this.instance = new lib.txt_stavka_6();
	this.instance.parent = this;
	this.instance.setTransform(-69.7,26.6,1,1,0,0,0,112.3,58.6);
	this.instance.alpha = 0;

	this.instance_1 = new lib.txt_stavka();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-59.7,26.6,1,1,0,0,0,112.3,58.6);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance}]},19).to({state:[{t:this.instance}]},5).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},10).to({state:[{t:this.instance}]},5).to({state:[{t:this.instance_1}]},20).wait(1));
	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:110.3,alpha:1},19,cjs.Ease.cubicOut).wait(5).to({regY:58.5,scaleX:1.0999,scaleY:1.0999,x:112.5,y:25.35},10,cjs.Ease.cubicInOut).to({regY:58.6,scaleX:1,scaleY:1,x:110.3,y:26.6},10,cjs.Ease.quadIn).wait(5).to({_off:true,x:-59.7,alpha:0},20,cjs.Ease.cubicIn).wait(1));

	// Layer_1
	this.instance_2 = new lib.txt_stavka();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-69.7,26.6,1,1,0,0,0,112.3,58.6);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:110.3,alpha:1},19,cjs.Ease.cubicOut).wait(30).to({x:-59.7,alpha:0},20,cjs.Ease.cubicIn).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-180,-3.8,321.4,82.2);


(lib.TXT_MAIN = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// txt02
	this.instance = new lib.txt02();
	this.instance.parent = this;
	this.instance.setTransform(-132.6,42.3,1,1,0,0,0,78.4,50.3);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(75).to({_off:false},0).to({x:75.4,alpha:1},20,cjs.Ease.cubicInOut).wait(51).to({x:285.4,alpha:0},20,cjs.Ease.cubicIn).wait(1));

	// txt0102
	this.instance_1 = new lib.txt0102();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-115.9,58.2,1,1,0,0,0,95.1,36.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(4).to({_off:false},0).to({x:92.1,alpha:1},19,cjs.Ease.cubicOut).wait(52).to({x:302.1,alpha:0},20,cjs.Ease.cubicInOut).to({_off:true},1).wait(71));

	// txt0101
	this.instance_2 = new lib.txt0101();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-127.9,7.1,1,1,0,0,0,83.1,12.1);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:80.1,alpha:1},19,cjs.Ease.cubicOut).wait(52).to({x:290.1,alpha:0},20,cjs.Ease.cubicInOut).to({_off:true},1).wait(75));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-208,0,602.7,89.7);


(lib.legal_mov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.legal_1();
	this.instance.parent = this;
	this.instance.setTransform(130,181.5,1,1,0,0,0,130,181.5);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14).wait(65).to({alpha:0},15).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,260,363);


(lib.INSURE = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// flash0.ai
	this.instance = new lib.ClipGroup();
	this.instance.parent = this;
	this.instance.setTransform(-0.4,-0.4,0.8226,0.8226,0,0,0,28.7,28.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.INSURE, new cjs.Rectangle(-25,-25,49,49), null);


(lib.BUTT_blue_mov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.butt();
	this.instance.parent = this;
	this.instance.setTransform(0,-0.05,0.6,0.6,0,0,0,0,-0.1);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regY:0,scaleX:1,scaleY:1,y:0,alpha:1},14,cjs.Ease.quadOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-130,-21,260,42.6);


(lib.bondarchuk_mov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bondarchuk_1();
	this.instance.parent = this;
	this.instance.setTransform(180,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:0},19,cjs.Ease.cubicOut).wait(5).to({x:180},20,cjs.Ease.cubicIn).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89,-222,358,444);


(lib.InsureMov = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.INSURE();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:1},14).wait(5).to({alpha:0},13).to({_off:true},1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-24,-24,47.3,47.3);


(lib.movie = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// BUTT_Blue
	this.instance = new lib.BUTT_blue_mov("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(150,552);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(4).to({_off:false},0).wait(150).to({startPosition:14},0).to({alpha:0},15).to({_off:true},1).wait(98));

	// BONDARCHUK
	this.instance_1 = new lib.bondarchuk_mov("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(212,378);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).wait(20).to({mode:"single",startPosition:20},0).wait(125).to({mode:"synched",startPosition:24,loop:false},0).wait(114));

	// TXT_Percent
	this.instance_2 = new lib.txt_stavka_mov("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(88.3,244.2,1,1,0,0,0,68.3,39.2);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({_off:false},0).wait(20).to({mode:"single",startPosition:20},0).wait(69).to({mode:"synched",startPosition:24,loop:false},0).wait(22).to({mode:"single",startPosition:20},0).wait(34).to({mode:"synched",startPosition:49,loop:false},0).wait(114));

	// TXT
	this.instance_3 = new lib.TXT_MAIN("synched",0,false);
	this.instance_3.parent = this;
	this.instance_3.setTransform(113.3,137.35,1,1,0,0,0,92.4,44.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(268));

	// LOGO
	this.instance_4 = new lib.LOGO();
	this.instance_4.parent = this;
	this.instance_4.setTransform(121.65,42.2,1.36,1.36,0,0,0,74,15.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(268));

	// LEGAL
	this.instance_5 = new lib.legal_mov("synched",0,false);
	this.instance_5.parent = this;
	this.instance_5.setTransform(151,275.5,1,1,0,0,0,130,181.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(170).to({_off:false},0).wait(98));

	// Layer_1 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Eg8EA8EUgY4gY4AAAgjMUAAAgjLAY4gY5UAY5gY4AjLAAAUAjMAAAAY4AY4UAY5AY5AAAAjLUAAAAjMgY5AY4UgY4AY5gjMAAAUgjLAAAgY5gY5g");
	var mask_graphics_1 = new cjs.Graphics().p("Eg7yA7yUgYwgYxAAAgjBUAAAgjAAYwgYyUAYygYwAjAAAAUAjBAAAAYxAYwUAYxAYyAAAAjAUAAAAjBgYxAYxUgYxAYxgjBAAAUgjAAAAgYygYxg");
	var mask_graphics_2 = new cjs.Graphics().p("Eg66A66UgYagYZAAAgihUAAAgigAYagYaUAYagYaAigAAAUAihAAAAYZAYaUAYbAYaAAAAigUAAAAihgYbAYZUgYZAYbgihAAAUgigAAAgYagYbg");
	var mask_graphics_3 = new cjs.Graphics().p("Eg5eA5eUgX0gXzAAAghrUAAAghqAX0gX0UAX0gX0AhqAAAUAhrAAAAXzAX0UAX1AX0AAAAhqUAAAAhrgX1AXzUgXzAX1ghrAAAUghqAAAgX0gX1g");
	var mask_graphics_4 = new cjs.Graphics().p("Eg3eA3eUgW+gW+AAAgggUAAAggfAW+gW/UAW/gW+AgfAAAUAggAAAAW+AW+UAW/AW/AAAAgfUAAAAgggW/AW+UgW+AW/gggAAAUggfAAAgW/gW/g");
	var mask_graphics_5 = new cjs.Graphics().p("Eg04A04Q1615AA+/QAA++V616QV616e+AAQe/AAV5V6QV7V6AAe+QAAe/17V5Q15V7+/AAQ++AA1617g");
	var mask_graphics_6 = new cjs.Graphics().p("EgxuAxuQ0m0mAA9IQAA9HUm0nQUn0mdHAAQdIAAUmUmQUnUnAAdHQAAdI0nUmQ0mUn9IAAQ9HAA0n0ng");
	var mask_graphics_7 = new cjs.Graphics().p("Egt/At/QzDzDAA68QAA67TDzEQTEzDa7AAQa8AATDTDQTETEAAa7QAAa8zETDQzDTE68AAQ67AAzEzEg");
	var mask_graphics_8 = new cjs.Graphics().p("Egp0Ap0QxUxUAA4gQAA4fRUxVQRVxUYfAAQYgAARURUQRVRVAAYfQAAYgxVRUQxURV4gAAQ4fAAxVxVg");
	var mask_graphics_9 = new cjs.Graphics().p("EgmFAmFQvxvxAA2UQAA2TPxvyQPyvxWTAAQWUAAPxPxQPyPyAAWTQAAWUvyPxQvxPy2UAAQ2TAAvyvyg");
	var mask_graphics_10 = new cjs.Graphics().p("Egi7Ai7QududAA0eQAA0dOdueQOeudUdAAQUeAAOdOdQOeOeAAUdQAAUeueOdQudOe0eAAQ0dAAueueg");
	var mask_graphics_11 = new cjs.Graphics().p("EggVAgWQtZtZAAy9QAAy8NZtZQNZtZS8AAQS9AANZNZQNZNZAAS8QAAS9tZNZQtZNZy9AAQy8AAtZtZg");
	var mask_graphics_12 = new cjs.Graphics().p("A+VeVQsjskAAxxQAAxwMjslQMlsjRwAAQRxAAMkMjQMkMlAARwQAARxskMkQskMkxxAAQxwAAslskg");
	var mask_graphics_13 = new cjs.Graphics().p("A85c5Qr9r+AAw7QAAw6L9r/QL/r9Q6AAQQ7AAL+L9QL+L/AAQ6QAAQ7r+L+Qr+L+w7AAQw6AAr/r+g");
	var mask_graphics_14 = new cjs.Graphics().p("A8BcCQrnrnAAwbQAAwaLnrnQLnrnQaAAQQbAALnLnQLnLnAAQaQAAQbrnLnQrnLnwbAAQwaAArnrng");
	var mask_graphics_15 = new cjs.Graphics().p("A7vbwQrfrgAAwQQAAwPLfrgQLgrfQPAAQQQAALgLfQLfLgAAQPQAAQQrfLgQrgLfwQAAQwPAArgrfg");
	var mask_graphics_16 = new cjs.Graphics().p("A7zbzQrhrhAAwSQAAwRLhriQLirhQRAAQQSAALhLhQLhLiAAQRQAAQSrhLhQrhLhwSAAQwRAArirhg");
	var mask_graphics_17 = new cjs.Graphics().p("A7+b+QrlrlAAwZQAAwYLlrmQLmrlQYAAQQZAALlLlQLmLmAAQYQAAQZrmLlQrlLmwZAAQwYAArmrmg");
	var mask_graphics_18 = new cjs.Graphics().p("A8RcRQrtrtAAwkQAAwjLtruQLurtQjAAQQkAALtLtQLuLuAAQjQAAQkruLtQrtLuwkAAQwjAArurug");
	var mask_graphics_19 = new cjs.Graphics().p("A8pcpQr3r3AAwyQAAwxL3r4QL4r3QxAAQQyAAL3L3QL4L4AAQxQAAQyr4L3Qr3L4wyAAQwxAAr4r4g");
	var mask_graphics_20 = new cjs.Graphics().p("A88c8Qr/r/AAw9QAAw8L/sAQMAr/Q8AAQQ9AAL/L/QMAMAAAQ8QAAQ9sAL/Qr/MAw9AAQw8AAsAsAg");
	var mask_graphics_21 = new cjs.Graphics().p("A9HdHQsDsDAAxEQAAxDMDsEQMEsDRDAAQREAAMDMDQMEMEAARDQAAREsEMDQsDMExEAAQxDAAsEsEg");
	var mask_graphics_22 = new cjs.Graphics().p("A9LdLQsFsFAAxGQAAxFMFsGQMGsFRFAAQRGAAMFMFQMGMGAARFQAARGsGMFQsFMGxGAAQxFAAsGsGg");
	var mask_graphics_23 = new cjs.Graphics().p("A9IdIQsEsEAAxEQAAxDMEsFQMFsERDAAQREAAMEMEQMFMFAARDQAAREsFMEQsEMFxEAAQxDAAsFsFg");
	var mask_graphics_24 = new cjs.Graphics().p("A8/c/QsAsAAAw/QAAw+MAsBQMBsAQ+AAQQ/AAMAMAQMBMBAAQ+QAAQ/sBMAQsAMBw/AAQw+AAsBsBg");
	var mask_graphics_25 = new cjs.Graphics().p("A8ycyQr7r7AAw3QAAw2L7r8QL8r7Q2AAQQ3AAL7L7QL8L8AAQ2QAAQ3r8L7Qr7L8w3AAQw2AAr8r8g");
	var mask_graphics_26 = new cjs.Graphics().p("A8pcpQr3r3AAwyQAAwxL3r4QL4r3QxAAQQyAAL3L3QL4L4AAQxQAAQyr4L3Qr3L4wyAAQwxAAr4r4g");
	var mask_graphics_27 = new cjs.Graphics().p("A8mcmQr2r1AAwxQAAwvL2r3QL3r2QvAAQQwAAL3L2QL2L3AAQvQAAQxr2L1Qr3L3wwAAQwvAAr3r3g");
	var mask_graphics_154 = new cjs.Graphics().p("A8mcmQr2r1AAwxQAAwvL2r3QL3r2QvAAQQwAAL3L2QL2L3AAQvQAAQxr2L1Qr3L3wwAAQwvAAr3r3g");
	var mask_graphics_155 = new cjs.Graphics().p("A8hchQr0rzAAwuQAAwtL0r0QL0r0QtAAQQuAALzL0QL1L0AAQtQAAQur1LzQrzL1wuAAQwtAAr0r1g");
	var mask_graphics_156 = new cjs.Graphics().p("A8ScSQrtrtAAwlQAAwkLtruQLurtQkAAQQlAALtLtQLuLuAAQkQAAQlruLtQrtLuwlAAQwkAArurug");
	var mask_graphics_157 = new cjs.Graphics().p("A74b5QrjrjAAwWQAAwVLjrjQLjrjQVAAQQWAALjLjQLjLjAAQVQAAQWrjLjQrjLjwWAAQwVAArjrjg");
	var mask_graphics_158 = new cjs.Graphics().p("A7fbfQrYrYAAwHQAAwGLYrZQLZrYQGAAQQHAALYLYQLZLZAAQGQAAQHrZLYQrYLZwHAAQwGAArZrZg");
	var mask_graphics_159 = new cjs.Graphics().p("A7QbQQrSrSAAv+QAAv9LSrTQLTrSP9AAQP+AALSLSQLTLTAAP9QAAP+rTLSQrSLTv+AAQv9AArTrTg");
	var mask_graphics_160 = new cjs.Graphics().p("A7KbLQrRrQAAv7QAAv6LRrQQLQrRP6AAQP7AALQLRQLRLQAAP6QAAP7rRLQQrQLRv7AAQv6AArQrRg");
	var mask_graphics_161 = new cjs.Graphics().p("A7NbNQrRrRAAv8QAAv7LRrSQLSrRP7AAQP8AALRLRQLSLSAAP7QAAP8rSLRQrRLSv8AAQv7AArSrSg");
	var mask_graphics_162 = new cjs.Graphics().p("A7bbcQrXrXAAwFQAAwELXrXQLXrXQEAAQQFAALXLXQLXLXAAQEQAAQFrXLXQrXLXwFAAQwEAArXrXg");
	var mask_graphics_163 = new cjs.Graphics().p("A8DcEQroroAAwcQAAwbLoroQLoroQbAAQQcAALoLoQLoLoAAQbQAAQcroLoQroLowcAAQwbAArorog");
	var mask_graphics_164 = new cjs.Graphics().p("A9RdSQsIsIAAxKQAAxJMIsIQMIsIRJAAQRKAAMIMIQMIMIAARJQAARKsIMIQsIMIxKAAQxJAAsIsIg");
	var mask_graphics_165 = new cjs.Graphics().p("A/SfSQs9s9AAyVQAAyUM9s+QM+s9SUAAQSVAAM9M9QM+M+AASUQAASVs+M9Qs9M+yVAAQyUAAs+s+g");
	var mask_graphics_166 = new cjs.Graphics().p("EgiRAiSQuNuNAA0FQAA0EONuNQONuNUEAAQUFAAONONQONONAAUEQAAUFuNONQuNON0FAAQ0EAAuNuNg");
	var mask_graphics_167 = new cjs.Graphics().p("EgmdAmdQv7v7AA2iQAA2hP7v8QP8v7WhAAQWiAAP7P7QP8P8AAWhQAAWiv8P7Qv7P82iAAQ2hAAv8v8g");
	var mask_graphics_168 = new cjs.Graphics().p("EgsBAsBQyOyPAA5yQAA5xSOyQQSQyOZxAAQZyAASPSOQSPSQAAZxQAAZyyPSPQyPSP5yAAQ5xAAyQyPg");
	var mask_graphics_169 = new cjs.Graphics().p("EgzJAzKQ1M1MAA9+QAA99VM1MQVM1Md9AAQd+AAVMVMQVMVMAAd9QAAd+1MVMQ1MVM9+AAQ99AA1M1Mg");
	var mask_graphics_170 = new cjs.Graphics().p("Eg8EA8EUgY4gY4AAAgjMUAAAgjLAY4gY5UAY5gY4AjLAAAUAjMAAAAY4AY4UAY5AY5AAAAjLUAAAAjMgY5AY4UgY4AY5gjMAAAUgjLAAAgY5gY5g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:97.6901,y:108.6901}).wait(1).to({graphics:mask_graphics_1,x:97.7015,y:108.7015}).wait(1).to({graphics:mask_graphics_2,x:97.736,y:108.736}).wait(1).to({graphics:mask_graphics_3,x:97.7934,y:108.7934}).wait(1).to({graphics:mask_graphics_4,x:97.8737,y:108.8737}).wait(1).to({graphics:mask_graphics_5,x:97.9771,y:108.9771}).wait(1).to({graphics:mask_graphics_6,x:98.1033,y:109.1033}).wait(1).to({graphics:mask_graphics_7,x:98.2526,y:109.2526}).wait(1).to({graphics:mask_graphics_8,x:98.419,y:109.419}).wait(1).to({graphics:mask_graphics_9,x:98.5683,y:109.5683}).wait(1).to({graphics:mask_graphics_10,x:98.6945,y:109.6945}).wait(1).to({graphics:mask_graphics_11,x:98.7979,y:109.7979}).wait(1).to({graphics:mask_graphics_12,x:98.8782,y:109.8782}).wait(1).to({graphics:mask_graphics_13,x:98.9356,y:109.9356}).wait(1).to({graphics:mask_graphics_14,x:98.9701,y:109.9701}).wait(1).to({graphics:mask_graphics_15,x:98.933,y:109.933}).wait(1).to({graphics:mask_graphics_16,x:98.9308,y:109.9308}).wait(1).to({graphics:mask_graphics_17,x:98.9241,y:109.9241}).wait(1).to({graphics:mask_graphics_18,x:98.9128,y:109.9128}).wait(1).to({graphics:mask_graphics_19,x:98.8983,y:109.8983}).wait(1).to({graphics:mask_graphics_20,x:98.887,y:109.887}).wait(1).to({graphics:mask_graphics_21,x:98.8803,y:109.8803}).wait(1).to({graphics:mask_graphics_22,x:98.878,y:109.878}).wait(1).to({graphics:mask_graphics_23,x:98.8758,y:109.8758}).wait(1).to({graphics:mask_graphics_24,x:98.8691,y:109.8691}).wait(1).to({graphics:mask_graphics_25,x:98.859,y:109.859}).wait(1).to({graphics:mask_graphics_26,x:98.8522,y:109.8522}).wait(1).to({graphics:mask_graphics_27,x:98.9,y:109.9}).wait(127).to({graphics:mask_graphics_154,x:98.9,y:109.9}).wait(1).to({graphics:mask_graphics_155,x:98.9057,y:109.9057}).wait(1).to({graphics:mask_graphics_156,x:98.9228,y:109.9228}).wait(1).to({graphics:mask_graphics_157,x:98.9513,y:109.9513}).wait(1).to({graphics:mask_graphics_158,x:98.9797,y:109.9797}).wait(1).to({graphics:mask_graphics_159,x:98.9968,y:109.9968}).wait(1).to({graphics:mask_graphics_160,x:98.955,y:109.955}).wait(1).to({graphics:mask_graphics_161,x:98.9536,y:109.9536}).wait(1).to({graphics:mask_graphics_162,x:98.944,y:109.944}).wait(1).to({graphics:mask_graphics_163,x:98.918,y:109.918}).wait(1).to({graphics:mask_graphics_164,x:98.8673,y:109.8673}).wait(1).to({graphics:mask_graphics_165,x:98.7838,y:109.7838}).wait(1).to({graphics:mask_graphics_166,x:98.6591,y:109.6591}).wait(1).to({graphics:mask_graphics_167,x:98.4851,y:109.4851}).wait(1).to({graphics:mask_graphics_168,x:98.2536,y:109.2536}).wait(1).to({graphics:mask_graphics_169,x:97.9563,y:108.9563}).wait(1).to({graphics:mask_graphics_170,x:97.69,y:108.69}).wait(98));

	// BUTT_WH
	this.instance_6 = new lib.butt_wh();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,551.9);
	this.instance_6._off = true;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(34).to({_off:false},0).wait(215).to({alpha:0},15).wait(4));

	// BG_BLUE
	this.instance_7 = new lib.BG_BLUE();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,300);

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(268));

	// INSURANCE
	this.instance_8 = new lib.InsureMov("synched",0,false);
	this.instance_8.parent = this;
	this.instance_8.setTransform(49,476,1.25,1.25);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).wait(15).to({mode:"single",startPosition:15},0).wait(249));

	// BG_WH
	this.instance_9 = new lib.BG_WH();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(268));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-639,-428,1384,1094.3);


// stage content:
(lib.gzprmbnk_save_300x600_review = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// movie
	this.instance = new lib.movie();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// button
	this.instance_1 = new lib.btn();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150,300,1.25,1.5);
	new cjs.ButtonHelper(this.instance_1, 0, 1, 2, false, new lib.btn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-296,-135,937.4,787.4);
// library properties:
lib.properties = {
	id: 'F66FE7A2AC3D5941AE55BF9D2D3ACE18',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"gzprmbnk_save_300x600_review_atlas_.png", id:"gzprmbnk_save_300x600_review_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F66FE7A2AC3D5941AE55BF9D2D3ACE18'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;